/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';let ba={},ca={},da={},ea={},fa={},ha={},ia={},la={},na={},oa={},pa={},qa={},sa={},ta={},ua={},va={},wa={},xa={},za={},Aa={},Ba={},Ca={},Da={},Ea={},Ha={},Ia={},Ja={},Ka={},La={},Ma={},Na={},Oa={},Pa={},Qa={},Ra={},Sa={};
function p(a){let b=new URLSearchParams;b.append("code",a);for(let c=1;c<arguments.length;c++)b.append("v",arguments[c]);throw Error(`Minified Lexical error #${a}; visit https://lexical.dev/docs/error?${b} for the full message or `+"use the non-minified dev environment for full errors and additional helpful warnings.");}
let Ta="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement,Ua=Ta&&"documentMode"in document?document.documentMode:null,t=Ta&&/Mac|iPod|iPhone|iPad/.test(navigator.platform),Va=Ta&&/^(?!.*Seamonkey)(?=.*Firefox).*/i.test(navigator.userAgent),Xa=Ta&&"InputEvent"in window&&!Ua?"getTargetRanges"in new window.InputEvent("input"):!1,Ya=Ta&&/Version\/[\d.]+.*Safari/.test(navigator.userAgent),Za=Ta&&/iPad|iPhone|iPod/.test(navigator.userAgent)&&
!window.MSStream,$a=Ta&&/Android/.test(navigator.userAgent),ab=Ta&&/^(?=.*Chrome).*/i.test(navigator.userAgent),bb=Ta&&$a&&ab,cb=Ta&&/AppleWebKit\/[\d.]+/.test(navigator.userAgent)&&!ab,db=Ya||Za||cb?"\u00a0":"\u200b",eb=Va?"\u00a0":db,fb=/^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\ufb1d-\ufdfd\ufe70-\ufefc]/,gb=/^[^\u0591-\u07ff\ufb1d-\ufdfd\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]/,
hb={bold:1,code:16,highlight:128,italic:2,strikethrough:4,subscript:32,superscript:64,underline:8},ib={directionless:1,unmergeable:2},jb={center:2,end:6,justify:4,left:1,right:3,start:5},kb={2:"center",6:"end",4:"justify",1:"left",3:"right",5:"start"},ob={normal:0,segmented:2,token:1},pb={0:"normal",2:"segmented",1:"token"};function qb(...a){let b=[];for(let c of a)if(c&&"string"===typeof c)for(let [d]of c.matchAll(/\S+/g))b.push(d);return b}let rb=!1,sb=0;
function tb(a){sb=a.timeStamp}function ub(a,b,c){return b.__lexicalLineBreak===a||void 0!==a[`__lexicalKey_${c._key}`]}function vb(a){return a.getEditorState().read(()=>{let b=u();return null!==b?b.clone():null})}
function wb(a,b,c){rb=!0;let d=100<performance.now()-sb;try{v(a,()=>{let e=u()||vb(a);var f=new Map,g=a.getRootElement(),h=a._editorState,k=a._blockCursorElement;let m=!1,q="";for(var n=0;n<b.length;n++){var l=b[n],r=l.type,w=l.target,A=xb(w,h);if(!(null===A&&w!==g||x(A)))if("characterData"===r){if(l=d&&B(A))a:{l=e;r=w;var y=A;if(C(l)){var z=l.anchor.getNode();if(z.is(y)&&l.format!==z.getFormat()){l=!1;break a}}l=3===r.nodeType&&y.isAttached()}l&&(y=yb(a._window),r=l=null,null!==y&&y.anchorNode===
w&&(l=y.anchorOffset,r=y.focusOffset),w=w.nodeValue,null!==w&&zb(A,w,l,r,!1))}else if("childList"===r){m=!0;r=l.addedNodes;for(y=0;y<r.length;y++){z=r[y];var R=Ab(z),X=z.parentNode;null==X||z===k||null!==R||"BR"===z.nodeName&&ub(z,X,a)||(Va&&(R=z.innerText||z.nodeValue)&&(q+=R),X.removeChild(z))}l=l.removedNodes;r=l.length;if(0<r){y=0;for(z=0;z<r;z++)if(X=l[z],"BR"===X.nodeName&&ub(X,w,a)||k===X)w.appendChild(X),y++;r!==y&&(w===g&&(A=h._nodeMap.get("root")),f.set(w,A))}}}if(0<f.size)for(let [Wa,ma]of f)if(E(ma))for(f=
ma.getChildrenKeys(),g=Wa.firstChild,h=0;h<f.length;h++)k=a.getElementByKey(f[h]),null!==k&&(null==g?(Wa.appendChild(k),g=k):g!==k&&Wa.replaceChild(k,g),g=g.nextSibling);else B(ma)&&ma.markDirty();f=c.takeRecords();if(0<f.length){for(g=0;g<f.length;g++)for(k=f[g],h=k.addedNodes,k=k.target,n=0;n<h.length;n++)A=h[n],w=A.parentNode,null==w||"BR"!==A.nodeName||ub(A,k,a)||w.removeChild(A);c.takeRecords()}null!==e&&(m&&(e.dirty=!0,Bb(e)),Va&&Cb(a)&&e.insertRawText(q))})}finally{rb=!1}}
function Db(a){let b=a._observer;if(null!==b){let c=b.takeRecords();wb(a,c,b)}}function Eb(a){0===sb&&Fb(a).addEventListener("textInput",tb,!0);a._observer=new MutationObserver((b,c)=>{wb(a,b,c)})}function Gb(a,b){let c=a.__mode,d=a.__format;a=a.__style;let e=b.__mode,f=b.__format;b=b.__style;return(null===c||c===e)&&(null===d||d===f)&&(null===a||a===b)}function Hb(a,b){let c=a.mergeWithSibling(b),d=F()._normalizedNodes;d.add(a.__key);d.add(b.__key);return c}
function Ib(a,b){let c=a.mergeWithSibling(b),d=F()._normalizedNodes;d.add(a.__key);d.add(b.__key);return c}function Jb(a){if(""===a.__text&&a.isSimpleText()&&!a.isUnmergeable())a.remove();else{for(var b;null!==(b=a.getPreviousSibling())&&B(b)&&b.isSimpleText()&&!b.isUnmergeable();)if(""===b.__text)b.remove();else{Gb(b,a)&&(a=Hb(b,a));break}for(var c;null!==(c=a.getNextSibling())&&B(c)&&c.isSimpleText()&&!c.isUnmergeable();)if(""===c.__text)c.remove();else{Gb(a,c)&&Hb(a,c);break}}}
function Kb(a){Lb(a.anchor);Lb(a.focus);return a}function Mb(a){let b;null!==(b=a.getPreviousSibling())&&Nb(b)&&b.__type===a.__type&&(a=Ib(b,a));let c;null!==(c=a.getNextSibling())&&Nb(c)&&c.__type===a.__type&&Ib(a,c)}
function Lb(a){for(;"element"===a.type;){var b=a.getNode(),c=a.offset;c===b.getChildrenSize()?(b=b.getChildAtIndex(c-1),c=!0):(b=b.getChildAtIndex(c),c=!1);if(B(b)){a.set(b.__key,c?b.getTextContentSize():0,"text");break}else if(!E(b))break;a.set(b.__key,c?b.getChildrenSize():0,"element")}}let Ob=1,Pb="function"===typeof queueMicrotask?queueMicrotask:a=>{Promise.resolve().then(a)};
function Wb(a){let b=document.activeElement;if(null===b)return!1;let c=b.nodeName;return x(xb(a))&&("INPUT"===c||"TEXTAREA"===c||"true"===b.contentEditable&&null==b.__lexicalEditor)}function Xb(a,b,c){let d=a.getRootElement();try{return null!==d&&d.contains(b)&&d.contains(c)&&null!==b&&!Wb(b)&&Yb(b)===a}catch(e){return!1}}function Yb(a){for(;null!=a;){let b=a.__lexicalEditor;if(null!=b)return b;a=Zb(a)}return null}function $b(a){return a.isToken()||a.isSegmented()}
function ac(a){for(;null!=a;){if(3===a.nodeType)return a;a=a.firstChild}return null}function bc(a,b,c){let d=hb[b];if(null!==c&&(a&d)===(c&d))return a;a^=d;"subscript"===b?a&=~hb.superscript:"superscript"===b&&(a&=~hb.subscript);return a}function cc(a,b){if(null!=b)a.__key=b;else{G();99<dc&&p(14);b=F();var c=ec(),d=""+Ob++;c._nodeMap.set(d,a);E(a)?b._dirtyElements.set(d,!0):b._dirtyLeaves.add(d);b._cloneNotNeeded.add(d);b._dirtyType=1;a.__key=d}}
function fc(a){var b=a.getParent();if(null!==b){let e=a.getWritable();b=b.getWritable();var c=a.getPreviousSibling();a=a.getNextSibling();if(null===c)if(null!==a){var d=a.getWritable();b.__first=a.__key;d.__prev=null}else b.__first=null;else{d=c.getWritable();if(null!==a){let f=a.getWritable();f.__prev=d.__key;d.__next=f.__key}else d.__next=null;e.__prev=null}null===a?null!==c?(a=c.getWritable(),b.__last=c.__key,a.__next=null):b.__last=null:(a=a.getWritable(),null!==c?(c=c.getWritable(),c.__next=
a.__key,a.__prev=c.__key):a.__prev=null,e.__next=null);b.__size--;e.__parent=null}}function gc(a){99<dc&&p(14);var b=a.getLatest(),c=b.__parent,d=ec();let e=F(),f=d._nodeMap;d=e._dirtyElements;if(null!==c)a:for(;null!==c;){if(d.has(c))break a;let g=f.get(c);if(void 0===g)break;d.set(c,!1);c=g.__parent}b=b.__key;e._dirtyType=1;E(a)?d.set(b,!0):e._dirtyLeaves.add(b)}
function H(a){G();var b=F();let c=b._compositionKey;a!==c&&(b._compositionKey=a,null!==c&&(b=I(c),null!==b&&b.getWritable()),null!==a&&(a=I(a),null!==a&&a.getWritable()))}function hc(){return ic()?null:F()._compositionKey}function I(a,b){a=(b||ec())._nodeMap.get(a);return void 0===a?null:a}function Ab(a,b){let c=F();a=a[`__lexicalKey_${c._key}`];return void 0!==a?I(a,b):null}function xb(a,b){for(;null!=a;){let c=Ab(a,b);if(null!==c)return c;a=Zb(a)}return null}
function jc(a){let b=Object.assign({},a._decorators);return a._pendingDecorators=b}function kc(a){return a.read(()=>J().getTextContent())}function lc(a,b){v(a,()=>{var c=ec();if(!c.isEmpty())if("root"===b)J().markDirty();else{c=c._nodeMap;for(let [,d]of c)d.markDirty()}},null===a._pendingEditorState?{tag:"history-merge"}:void 0)}function J(){return ec()._nodeMap.get("root")}function Bb(a){G();let b=ec();null!==a&&(a.dirty=!0,a.setCachedNodes(null));b._selection=a}
function mc(a){var b=F(),c;a:{for(c=a;null!=c;){let d=c[`__lexicalKey_${b._key}`];if(void 0!==d){c=d;break a}c=Zb(c)}c=null}return null===c?(b=b.getRootElement(),a===b?I("root"):null):I(c)}function nc(a){return/[\uD800-\uDBFF][\uDC00-\uDFFF]/g.test(a)}function oc(a){let b=[];for(;null!==a;)b.push(a),a=a._parentEditor;return b}function pc(){return Math.random().toString(36).replace(/[^a-z]+/g,"").substr(0,5)}
function qc(a,b,c){b=yb(b._window);if(null!==b){var d=b.anchorNode,{anchorOffset:e,focusOffset:f}=b;if(null!==d&&(b=3===d.nodeType?d.nodeValue:null,d=xb(d),null!==b&&B(d))){if(b===db&&c){let g=c.length;b=c;f=e=g}null!==b&&zb(d,b,e,f,a)}}}
function zb(a,b,c,d,e){let f=a;if(f.isAttached()&&(e||!f.isDirty())){let m=f.isComposing(),q=b;(m||e)&&b[b.length-1]===db&&(q=b.slice(0,-1));b=f.getTextContent();if(e||q!==b)if(""===q)if(H(null),Ya||Za||cb)f.remove();else{let n=F();setTimeout(()=>{n.update(()=>{f.isAttached()&&f.remove()})},20)}else{e=f.getParent();b=rc();var g=f.getTextContentSize(),h=hc(),k=f.getKey();f.isToken()||null!==h&&k===h&&!m||C(b)&&(null!==e&&!e.canInsertTextBefore()&&0===b.anchor.offset||b.anchor.key===a.__key&&0===b.anchor.offset&&
!f.canInsertTextBefore()&&!m||b.focus.key===a.__key&&b.focus.offset===g&&!f.canInsertTextAfter()&&!m)?f.markDirty():(a=u(),C(a)&&null!==c&&null!==d&&(a.setTextNodeRange(f,c,f,d),f.isSegmented()&&(c=f.getTextContent(),c=K(c),f.replace(c),f=c)),f.setTextContent(q))}}}
function sc(a,b){if(b.isSegmented())return!0;if(!a.isCollapsed())return!1;a=a.anchor.offset;let c=b.getParentOrThrow(),d=b.isToken();return 0===a?((a=!b.canInsertTextBefore()||!c.canInsertTextBefore()&&!b.isComposing()||d)||(b=b.getPreviousSibling(),a=(B(b)||E(b)&&b.isInline())&&!b.canInsertTextAfter()),a):a===b.getTextContentSize()?!b.canInsertTextAfter()||!c.canInsertTextAfter()&&!b.isComposing()||d:!1}
function tc(a,b){void 0===a.__lexicalClassNameCache&&(a.__lexicalClassNameCache={});let c=a.__lexicalClassNameCache,d=c[b];if(void 0!==d)return d;a=a[b];return"string"===typeof a?(a=qb(a),c[b]=a):a}function uc(a,b,c,d,e){0!==c.size&&(c=d.__type,d=d.__key,b=b.get(c),void 0===b&&p(33,c),c=b.klass,b=a.get(c),void 0===b&&(b=new Map,a.set(c,b)),a=b.get(d),c="destroyed"===a&&"created"===e,(void 0===a||c)&&b.set(d,c?"updated":e))}
function vc(a,b,c){let d=a.getParent(),e=c;null!==d&&(b&&0===c?(e=a.getIndexWithinParent(),a=d):b||c!==a.getChildrenSize()||(e=a.getIndexWithinParent()+1,a=d));return a.getChildAtIndex(b?e-1:e)}
function wc(a,b){var c=F()._config.customGetAdjacentNode;if(c&&(c=c(a,b)))return c;c=a.offset;if("element"===a.type)return a=a.getNode(),vc(a,b,c);a=a.getNode();return b&&0===c||!b&&c===a.getTextContentSize()?(c=b?a.getPreviousSibling():a.getNextSibling(),null===c?vc(a.getParentOrThrow(),b,a.getIndexWithinParent()+(b?0:1)):c):null}function Cb(a){a=(a=Fb(a).event)&&a.inputType;return"insertFromPaste"===a||"insertFromPasteAsQuotation"===a}
function xc(a){return!L(a)&&!a.isLastChild()&&!a.isInline()}function yc(a,b){a=a._keyToDOMMap.get(b);void 0===a&&p(75,b);return a}function Zb(a){a=a.assignedSlot||a.parentElement;return null!==a&&11===a.nodeType?a.host:a}function zc(a,b){for(a=a.getParent();null!==a;){if(a.is(b))return!0;a=a.getParent()}return!1}function Fb(a){a=a._window;null===a&&p(78);return a}function Ac(a){for(a=a.getParentOrThrow();null!==a&&!Bc(a);)a=a.getParentOrThrow();return a}
function Bc(a){return L(a)||E(a)&&a.isShadowRoot()}function Cc(a){a=a.constructor.clone(a);cc(a,null);return a}function Dc(a){var b=F();let c=a.constructor.getType();b=b._nodes.get(c);void 0===b&&p(97);b=b.replace;return null!==b?(b=b(a),b instanceof a.constructor||p(98),b):a}function Ec(a,b){a=a.getParent();!L(a)||E(b)||x(b)||p(99)}function Fc(a){return(x(a)||E(a)&&!a.canBeEmpty())&&!a.isInline()}
function Gc(a,b,c){c.style.removeProperty("caret-color");b._blockCursorElement=null;b=a.parentElement;null!==b&&b.removeChild(a)}function yb(a){return Ta?(a||window).getSelection():null}function Hc(a){return 1===a.nodeType}function Ic(a){if(x(a)&&!a.isInline())return!0;if(!E(a)||Bc(a))return!1;var b=a.getFirstChild();b=null===b||Jc(b)||B(b)||b.isInline();return!a.isInline()&&!1!==a.canBeEmpty()&&b}
function Kc(a,b){for(;null!==a&&null!==a.getParent()&&!b(a);)a=a.getParentOrThrow();return b(a)?a:null}function Lc(a,b,c,d,e,f){for(a=a.getFirstChild();null!==a;){let g=a.__key;a.__parent===b&&(E(a)&&Lc(a,g,c,d,e,f),c.has(g)||f.delete(g),e.push(g));a=a.getNextSibling()}}
function Mc(a,b,c,d){a=a._nodeMap;b=b._nodeMap;let e=[];for(let [f]of d){let g=b.get(f);void 0===g||g.isAttached()||(E(g)&&Lc(g,f,a,b,e,d),a.has(f)||d.delete(f),e.push(f))}for(let f of e)b.delete(f);for(let f of c)d=b.get(f),void 0===d||d.isAttached()||(a.has(f)||c.delete(f),b.delete(f))}let M="",N="",Nc=null,Oc="",Pc,O,Qc,Rc=!1,Sc=!1,Tc,cd=null,dd,ed,fd,gd,hd,id;
function jd(a,b){let c=fd.get(a);if(null!==b){let d=kd(a);d.parentNode===b&&b.removeChild(d)}gd.has(a)||O._keyToDOMMap.delete(a);E(c)&&(a=ld(c,fd),md(a,0,a.length-1,null));void 0!==c&&uc(id,Qc,Tc,c,"destroyed")}function md(a,b,c,d){for(;b<=c;++b){let e=a[b];void 0!==e&&jd(e,d)}}function nd(a,b){a.setProperty("text-align",b)}
function od(a,b){var c=Pc.theme.indent;if("string"===typeof c){let d=a.classList.contains(c);0<b&&!d?a.classList.add(c):1>b&&d&&a.classList.remove(c)}c=getComputedStyle(a).getPropertyValue("--lexical-indent-base-value")||"40px";a.style.setProperty("padding-inline-start",0===b?"":`calc(${b} * ${c})`)}function pd(a,b){a=a.style;0===b?nd(a,""):1===b?nd(a,"left"):2===b?nd(a,"center"):3===b?nd(a,"right"):4===b?nd(a,"justify"):5===b?nd(a,"start"):6===b&&nd(a,"end")}
function qd(a,b,c){let d=gd.get(a);void 0===d&&p(60);let e=d.createDOM(Pc,O);var f=O._keyToDOMMap;e["__lexicalKey_"+O._key]=a;f.set(a,e);B(d)?e.setAttribute("data-lexical-text","true"):x(d)&&e.setAttribute("data-lexical-decorator","true");if(E(d)){a=d.__indent;f=d.__size;0!==a&&od(e,a);if(0!==f){--f;a=ld(d,gd);var g=N;N="";rd(a,d,0,f,e,null);sd(d,e);N=g}a=d.__format;0!==a&&pd(e,a);d.isInline()||td(null,d,e);xc(d)&&(M+="\n\n",Oc+="\n\n")}else f=d.getTextContent(),x(d)?(g=d.decorate(O,Pc),null!==g&&
ud(a,g),e.contentEditable="false"):B(d)&&(d.isDirectionless()||(N+=f)),M+=f,Oc+=f;null!==b&&(null!=c?b.insertBefore(e,c):(c=b.__lexicalLineBreak,null!=c?b.insertBefore(e,c):b.appendChild(e)));uc(id,Qc,Tc,d,"created");return e}function rd(a,b,c,d,e,f){let g=M;for(M="";c<=d;++c){qd(a[c],e,f);let h=gd.get(a[c]);null!==h&&null===Nc&&B(h)&&(Nc=h.getFormat())}xc(b)&&(M+="\n\n");e.__lexicalTextContent=M;M=g+M}function vd(a,b){a=b.get(a);return Jc(a)||x(a)&&a.isInline()}
function td(a,b,c){a=null!==a&&(0===a.__size||vd(a.__last,fd));b=0===b.__size||vd(b.__last,gd);a?b||(b=c.__lexicalLineBreak,null!=b&&c.removeChild(b),c.__lexicalLineBreak=null):b&&(b=document.createElement("br"),c.__lexicalLineBreak=b,c.appendChild(b))}
function sd(a,b){var c=b.__lexicalDir;if(b.__lexicalDirTextContent!==N||c!==cd){let f=""===N;if(f)var d=cd;else d=N,d=fb.test(d)?"rtl":gb.test(d)?"ltr":null;if(d!==c){let g=b.classList,h=Pc.theme;var e=null!==c?h[c]:void 0;let k=null!==d?h[d]:void 0;void 0!==e&&("string"===typeof e&&(e=qb(e),e=h[c]=e),g.remove(...e));null===d||f&&"ltr"===d?b.removeAttribute("dir"):(void 0!==k&&("string"===typeof k&&(c=qb(k),k=h[d]=c),void 0!==k&&g.add(...k)),b.dir=d);Sc||(a.getWritable().__dir=d)}cd=d;b.__lexicalDirTextContent=
N;b.__lexicalDir=d}}function ld(a,b){let c=[];for(a=a.__first;null!==a;){let d=b.get(a);void 0===d&&p(101);c.push(a);a=d.__next}return c}
function wd(a,b){var c=fd.get(a),d=gd.get(a);void 0!==c&&void 0!==d||p(61);var e=Rc||ed.has(a)||dd.has(a);let f=yc(O,a);if(c===d&&!e)return E(c)?(d=f.__lexicalTextContent,void 0!==d&&(M+=d,Oc+=d),d=f.__lexicalDirTextContent,void 0!==d&&(N+=d)):(d=c.getTextContent(),B(c)&&!c.isDirectionless()&&(N+=d),Oc+=d,M+=d),f;c!==d&&e&&uc(id,Qc,Tc,d,"updated");d.updateDOMProperties(c,f,Pc);if(d.updateDOM(c,f,Pc))return d=qd(a,null,null),null===b&&p(62),b.replaceChild(d,f),jd(a,null),d;if(E(c)&&E(d)){a=d.__indent;
a!==c.__indent&&od(f,a);a=d.__format;a!==c.__format&&pd(f,a);if(e){a=N;N="";Nc=null;e=M;var g=c.__size,h=d.__size;M="";if(1===g&&1===h){var k=c.__first,m=d.__first;if(k===m)wd(k,f);else{b=kd(k);var q=qd(m,null,null);f.replaceChild(q,b);jd(k,null)}k=gd.get(m);null===Nc&&B(k)&&(Nc=k.getFormat())}else{b=ld(c,fd);var n=ld(d,gd);if(0===g)0!==h&&rd(n,d,0,h-1,f,null);else if(0===h)0!==g&&(k=null==f.__lexicalLineBreak,md(b,0,g-1,k?null:f),k&&(f.textContent=""));else{q=b;b=n;n=g-1;g=h-1;let w=f.firstChild,
A=0;for(h=0;A<=n&&h<=g;){var l=q[A],r=b[h];if(l===r)w=xd(wd(r,f)),A++,h++;else{void 0===k&&(k=new Set(q));void 0===m&&(m=new Set(b));let y=m.has(l),z=k.has(r);y?(z?(l=yc(O,r),l===w?w=xd(wd(r,f)):(null!=w?f.insertBefore(l,w):f.appendChild(l),wd(r,f)),A++):qd(r,f,w),h++):(w=xd(kd(l)),jd(l,f),A++)}r=gd.get(r);null!==r&&null===Nc&&B(r)&&(Nc=r.getFormat())}k=A>n;m=h>g;k&&!m?(k=b[g+1],k=void 0===k?null:O.getElementByKey(k),rd(b,d,h,g,f,k)):m&&!k&&md(q,A,n,f)}}xc(d)&&(M+="\n\n");f.__lexicalTextContent=M;
M=e+M;sd(d,f);yd(d)&&null!=Nc&&Nc!==d.__textFormat&&d.setTextFormat(Nc);N=a;Nc=null;L(d)||d.isInline()||td(c,d,f)}xc(d)&&(M+="\n\n",Oc+="\n\n")}else c=d.getTextContent(),x(d)?(e=d.decorate(O,Pc),null!==e&&ud(a,e)):B(d)&&!d.isDirectionless()&&(N+=c),M+=c,Oc+=c;!Sc&&L(d)&&d.__cachedText!==Oc&&(d.getWritable().__cachedText=Oc);return f}function ud(a,b){let c=O._pendingDecorators,d=O._decorators;if(null===c){if(d[a]===b)return;c=jc(O)}c[a]=b}
function xd(a){a=a.nextSibling;null!==a&&a===O._blockCursorElement&&(a=a.nextSibling);return a}function kd(a){let b=hd.get(a);void 0===b&&p(75,a);return b}let zd=Object.freeze({}),Gd=[["keydown",Ad],["pointerdown",Bd],["compositionstart",Cd],["compositionend",Dd],["input",Ed],["click",Fd],["cut",zd],["copy",zd],["dragstart",zd],["dragover",zd],["dragend",zd],["paste",zd],["focus",zd],["blur",zd],["drop",zd]];Xa&&Gd.push(["beforeinput",(a,b)=>Hd(a,b)]);
let Id=0,Jd=0,Kd=0,Ld=null,Md=new WeakMap,Nd=!1,Od=!1,Pd=!1,Qd=!1,Rd=[0,"",0,"root",0];
function Sd(a,b,c,d,e){let f=a.anchor,g=a.focus,h=f.getNode();var k=F();let m=yb(k._window),q=null!==m?m.anchorNode:null,n=f.key;k=k.getElementByKey(n);let l=c.length;return n!==g.key||!B(h)||(!e&&(!Xa||Kd<d+50)||h.isDirty()&&2>l||nc(c))&&f.offset!==g.offset&&!h.isComposing()||$b(h)||h.isDirty()&&1<l||(e||!Xa)&&null!==k&&!h.isComposing()&&q!==ac(k)||null!==m&&null!==b&&(!b.collapsed||b.startContainer!==m.anchorNode||b.startOffset!==m.anchorOffset)||h.getFormat()!==a.format||h.getStyle()!==a.style||
sc(a,h)}function Td(a,b){return null!==a&&null!==a.nodeValue&&3===a.nodeType&&0!==b&&b!==a.nodeValue.length}
function Ud(a,b,c){let {anchorNode:d,anchorOffset:e,focusNode:f,focusOffset:g}=a;if(Nd&&(Nd=!1,Td(d,e)&&Td(f,g)))return;v(b,()=>{if(!c)Bb(null);else if(Xb(b,d,f)){var h=u();if(C(h)){var k=h.anchor,m=k.getNode();if(h.isCollapsed()){"Range"===a.type&&a.anchorNode===a.focusNode&&(h.dirty=!0);var q=Fb(b).event;q=q?q.timeStamp:performance.now();let [A,y,z,R,X]=Rd;var n=J();n=!1===b.isComposing()&&""===n.getTextContent();q<X+200&&k.offset===z&&k.key===R?(h.format=A,h.style=y):"text"===k.type?(B(m)||p(141),
h.format=m.getFormat(),h.style=m.getStyle()):"element"!==k.type||n||(k=k.getNode(),k instanceof Vd&&0===k.getChildrenSize()?h.format=k.getTextFormat():h.format=0,h.style="")}else{var l=k.key,r=h.focus.key;k=h.getNodes();m=k.length;var w=h.isBackward();q=w?g:e;n=w?e:g;let A=w?r:l;l=w?l:r;r=255;w=!1;for(let y=0;y<m;y++){let z=k[y],R=z.getTextContentSize();if(B(z)&&0!==R&&!(0===y&&z.__key===A&&q===R||y===m-1&&z.__key===l&&0===n)&&(w=!0,r&=z.getFormat(),0===r))break}h.format=w?r:0}}S(b,ba,void 0)}})}
function Fd(a,b){v(b,()=>{let c=u();var d=yb(b._window);let e=rc();if(d)if(C(c)){let g=c.anchor;var f=g.getNode();"element"===g.type&&0===g.offset&&c.isCollapsed()&&!L(f)&&1===J().getChildrenSize()&&f.getTopLevelElementOrThrow().isEmpty()&&null!==e&&c.is(e)?(d.removeAllRanges(),c.dirty=!0):3!==a.detail||c.isCollapsed()||(d=c.focus.getNode(),f!==d&&(E(f)?f.select(0):f.getParentOrThrow().select(0)))}else"touch"===a.pointerType&&(f=d.anchorNode,null!==f&&(f=f.nodeType,1===f||3===f))&&(d=Wd(e,d,b,a),
Bb(d));S(b,ca,a)})}function Bd(a,b){let c=a.target;a=a.pointerType;c instanceof Node&&"touch"!==a&&v(b,()=>{x(xb(c))||(Od=!0)})}function Xd(a){if(!a.getTargetRanges)return null;a=a.getTargetRanges();return 0===a.length?null:a[0]}function Yd(a,b){return a!==b||E(a)||E(b)||!a.isToken()||!b.isToken()}
function Hd(a,b){let c=a.inputType,d=Xd(a);"deleteCompositionText"===c||Va&&Cb(b)||"insertCompositionText"!==c&&v(b,()=>{var e=u();if("deleteContentBackward"===c){if(null===e){var f=rc();if(!C(f))return;Bb(f.clone())}if(C(e)){f=e.anchor.key===e.focus.key;if(229===Jd&&a.timeStamp<Id+30&&b.isComposing()&&f)H(null),Id=0,setTimeout(()=>{v(b,()=>{H(null)})},30),C(e)&&(f=e.anchor.getNode(),f.markDirty(),e.format=f.getFormat(),B(f)||p(142),e.style=f.getStyle());else{H(null);a.preventDefault();var g=e.anchor.getNode().getTextContent();
e=0===e.anchor.offset&&e.focus.offset===g.length;bb&&f&&!e||S(b,da,!0)}return}}if(C(e)){f=a.data;null!==Ld&&qc(!1,b,Ld);e.dirty&&null===Ld||!e.isCollapsed()||L(e.anchor.getNode())||null===d||e.applyDOMRange(d);Ld=null;var h=e.focus;g=e.anchor.getNode();h=h.getNode();if("insertText"===c||"insertTranspose"===c)"\n"===f?(a.preventDefault(),S(b,ea,!1)):"\n\n"===f?(a.preventDefault(),S(b,fa,void 0)):null==f&&a.dataTransfer?(f=a.dataTransfer.getData("text/plain"),a.preventDefault(),e.insertRawText(f)):
null!=f&&Sd(e,d,f,a.timeStamp,!0)?(a.preventDefault(),S(b,ha,f)):Ld=f,Kd=a.timeStamp;else switch(a.preventDefault(),c){case "insertFromYank":case "insertFromDrop":case "insertReplacementText":S(b,ha,a);break;case "insertFromComposition":H(null);S(b,ha,a);break;case "insertLineBreak":H(null);S(b,ea,!1);break;case "insertParagraph":H(null);Pd&&!Za?(Pd=!1,S(b,ea,!1)):S(b,fa,void 0);break;case "insertFromPaste":case "insertFromPasteAsQuotation":S(b,ia,a);break;case "deleteByComposition":Yd(g,h)&&S(b,
la,a);break;case "deleteByDrag":case "deleteByCut":S(b,la,a);break;case "deleteContent":S(b,da,!1);break;case "deleteWordBackward":S(b,na,!0);break;case "deleteWordForward":S(b,na,!1);break;case "deleteHardLineBackward":case "deleteSoftLineBackward":S(b,oa,!0);break;case "deleteContentForward":case "deleteHardLineForward":case "deleteSoftLineForward":S(b,oa,!1);break;case "formatStrikeThrough":S(b,pa,"strikethrough");break;case "formatBold":S(b,pa,"bold");break;case "formatItalic":S(b,pa,"italic");
break;case "formatUnderline":S(b,pa,"underline");break;case "historyUndo":S(b,qa,void 0);break;case "historyRedo":S(b,sa,void 0)}}})}
function Ed(a,b){a.stopPropagation();v(b,()=>{var c=u(),d=a.data,e=Xd(a);if(null!=d&&C(c)&&Sd(c,e,d,a.timeStamp,!1)){Qd&&(Zd(b,d),Qd=!1);var f=c.anchor,g=f.getNode();e=yb(b._window);if(null===e)return;let h=f.offset;if(f=Xa&&!c.isCollapsed()&&B(g)&&null!==e.anchorNode)g=g.getTextContent().slice(0,h)+d+g.getTextContent().slice(h+c.focus.offset),e=e.anchorNode,f=g===(3===e.nodeType?e.nodeValue:null);f||S(b,ha,d);d=d.length;Va&&1<d&&"insertCompositionText"===a.inputType&&!b.isComposing()&&(c.anchor.offset-=
d);Ya||Za||cb||!b.isComposing()||(Id=0,H(null))}else qc(!1,b,null!==d?d:void 0),Qd&&(Zd(b,d||void 0),Qd=!1);G();c=F();Db(c)});Ld=null}function Cd(a,b){v(b,()=>{let c=u();if(C(c)&&!b.isComposing()){let d=c.anchor,e=c.anchor.getNode();H(d.key);(a.timeStamp<Id+30||"element"===d.type||!c.isCollapsed()||e.getFormat()!==c.format||B(e)&&e.getStyle()!==c.style)&&S(b,ha,eb)}})}
function Zd(a,b){var c=a._compositionKey;H(null);if(null!==c&&null!=b){if(""===b){b=I(c);a=ac(a.getElementByKey(c));null!==a&&null!==a.nodeValue&&B(b)&&zb(b,a.nodeValue,null,null,!0);return}if("\n"===b[b.length-1]&&(c=u(),C(c))){b=c.focus;c.anchor.set(b.key,b.offset,b.type);S(a,Ba,null);return}}qc(!0,a,b)}function Dd(a,b){Va?Qd=!0:v(b,()=>{Zd(b,a.data)})}
function Ad(a,b){Id=a.timeStamp;Jd=a.keyCode;if(!b.isComposing()){var {keyCode:c,shiftKey:d,ctrlKey:e,metaKey:f,altKey:g}=a;if(!S(b,ta,a)){if(39!==c||e||f||g)if(39!==c||g||d||!e&&!f)if(37!==c||e||f||g)if(37!==c||g||d||!e&&!f)if(38!==c||e||f)if(40!==c||e||f)if(13===c&&d)Pd=!0,S(b,Ba,a);else if(32===c)S(b,Ca,a);else if(t&&e&&79===c)a.preventDefault(),Pd=!0,S(b,ea,!0);else if(13!==c||d){var h=t?g||f?!1:8===c||72===c&&e:e||g||f?!1:8===c;h?8===c?S(b,Da,a):(a.preventDefault(),S(b,da,!0)):27===c?S(b,Ea,
a):(h=t?d||g||f?!1:46===c||68===c&&e:e||g||f?!1:46===c,h?46===c?S(b,Ha,a):(a.preventDefault(),S(b,da,!1)):8===c&&(t?g:e)?(a.preventDefault(),S(b,na,!0)):46===c&&(t?g:e)?(a.preventDefault(),S(b,na,!1)):t&&f&&8===c?(a.preventDefault(),S(b,oa,!0)):t&&f&&46===c?(a.preventDefault(),S(b,oa,!1)):66===c&&!g&&(t?f:e)?(a.preventDefault(),S(b,pa,"bold")):85===c&&!g&&(t?f:e)?(a.preventDefault(),S(b,pa,"underline")):73===c&&!g&&(t?f:e)?(a.preventDefault(),S(b,pa,"italic")):9!==c||g||e||f?90===c&&!d&&(t?f:e)?(a.preventDefault(),
S(b,qa,void 0)):(h=t?90===c&&f&&d:89===c&&e||90===c&&e&&d,h?(a.preventDefault(),S(b,sa,void 0)):$d(b._editorState._selection)?(h=d?!1:67===c?t?f:e:!1,h?(a.preventDefault(),S(b,Na,a)):(h=d?!1:88===c?t?f:e:!1,h?(a.preventDefault(),S(b,Oa,a)):65===c&&(t?f:e)&&(a.preventDefault(),S(b,Pa,a)))):!Va&&65===c&&(t?f:e)&&(a.preventDefault(),S(b,Pa,a))):S(b,Ia,a))}else Pd=!1,S(b,Ba,a);else S(b,Aa,a);else S(b,za,a);else S(b,xa,a);else S(b,wa,a);else S(b,va,a);else S(b,ua,a);(e||d||g||f)&&S(b,Sa,a)}}}
function ae(a){let b=a.__lexicalEventHandles;void 0===b&&(b=[],a.__lexicalEventHandles=b);return b}let be=new Map;
function ce(a){var b=a.target;let c=yb(null==b?null:9===b.nodeType?b.defaultView:b.ownerDocument.defaultView);if(null!==c){var d=Yb(c.anchorNode);if(null!==d){Od&&(Od=!1,v(d,()=>{var h=rc(),k=c.anchorNode;null!==k&&(k=k.nodeType,1===k||3===k)&&(h=Wd(h,c,d,a),Bb(h))}));b=oc(d);b=b[b.length-1];var e=b._key,f=be.get(e),g=f||b;g!==d&&Ud(c,g,!1);Ud(c,d,!0);d!==b?be.set(e,d):f&&be.delete(e)}}}
function de(a,b){var c=a.ownerDocument,d=Md.get(c);(void 0===d||1>d)&&c.addEventListener("selectionchange",ce);Md.set(c,d||1);a.__lexicalEditor=b;c=ae(a);for(d=0;d<Gd.length;d++){let [e,f]=Gd[d],g="function"===typeof f?h=>{!0!==h._lexicalHandled&&(h._lexicalHandled=!0,(b.isEditable()||"click"===e)&&f(h,b))}:h=>{if(!0!==h._lexicalHandled&&(h._lexicalHandled=!0,b.isEditable()))switch(e){case "cut":return S(b,Oa,h);case "copy":return S(b,Na,h);case "paste":return S(b,ia,h);case "dragstart":return S(b,
Ka,h);case "dragover":return S(b,La,h);case "dragend":return S(b,Ma,h);case "focus":return S(b,Qa,h);case "blur":return S(b,Ra,h);case "drop":return S(b,Ja,h)}};a.addEventListener(e,g);c.push(()=>{a.removeEventListener(e,g)})}}
function ee(a,b,c){G();var d=a.__key;let e=a.getParent();if(null!==e){var f=u();if(C(f)&&E(a)){var {anchor:g,focus:h}=f;var k=g.getNode();var m=h.getNode();zc(k,a)&&g.set(a.__key,0,"element");zc(m,a)&&h.set(a.__key,0,"element")}k=f;m=!1;if(C(k)&&b){f=k.anchor;let q=k.focus;f.key===d&&(fe(f,a,e,a.getPreviousSibling(),a.getNextSibling()),m=!0);q.key===d&&(fe(q,a,e,a.getPreviousSibling(),a.getNextSibling()),m=!0)}else $d(k)&&b&&a.isSelected()&&a.selectPrevious();C(k)&&b&&!m?(d=a.getIndexWithinParent(),
fc(a),ge(k,e,d,-1)):fc(a);c||Bc(e)||e.canBeEmpty()||!e.isEmpty()||ee(e,b);b&&L(e)&&e.isEmpty()&&e.selectEnd()}}
class he{static getType(){p(64,this.name)}static clone(){p(65,this.name)}constructor(a){this.__type=this.constructor.getType();this.__next=this.__prev=this.__parent=null;cc(this,a)}getType(){return this.__type}isInline(){p(137,this.constructor.name)}isAttached(){for(var a=this.__key;null!==a;){if("root"===a)return!0;a=I(a);if(null===a)break;a=a.__parent}return!1}isSelected(a){a=a||u();if(null==a)return!1;let b=a.getNodes().some(c=>c.__key===this.__key);return B(this)?b:C(a)&&"element"===a.anchor.type&&
"element"===a.focus.type&&a.anchor.key===a.focus.key&&a.anchor.offset===a.focus.offset?!1:b}getKey(){return this.__key}getIndexWithinParent(){var a=this.getParent();if(null===a)return-1;a=a.getFirstChild();let b=0;for(;null!==a;){if(this.is(a))return b;b++;a=a.getNextSibling()}return-1}getParent(){let a=this.getLatest().__parent;return null===a?null:I(a)}getParentOrThrow(){let a=this.getParent();null===a&&p(66,this.__key);return a}getTopLevelElement(){let a=this;for(;null!==a;){let b=a.getParent();
if(Bc(b))return E(a)||p(138),a;a=b}return null}getTopLevelElementOrThrow(){let a=this.getTopLevelElement();null===a&&p(67,this.__key);return a}getParents(){let a=[],b=this.getParent();for(;null!==b;)a.push(b),b=b.getParent();return a}getParentKeys(){let a=[],b=this.getParent();for(;null!==b;)a.push(b.__key),b=b.getParent();return a}getPreviousSibling(){let a=this.getLatest().__prev;return null===a?null:I(a)}getPreviousSiblings(){let a=[];var b=this.getParent();if(null===b)return a;for(b=b.getFirstChild();null!==
b&&!b.is(this);)a.push(b),b=b.getNextSibling();return a}getNextSibling(){let a=this.getLatest().__next;return null===a?null:I(a)}getNextSiblings(){let a=[],b=this.getNextSibling();for(;null!==b;)a.push(b),b=b.getNextSibling();return a}getCommonAncestor(a){let b=this.getParents();var c=a.getParents();E(this)&&b.unshift(this);E(a)&&c.unshift(a);a=b.length;var d=c.length;if(0===a||0===d||b[a-1]!==c[d-1])return null;c=new Set(c);for(d=0;d<a;d++){let e=b[d];if(c.has(e))return e}return null}is(a){return null==
a?!1:this.__key===a.__key}isBefore(a){if(this===a)return!1;if(a.isParentOf(this))return!0;if(this.isParentOf(a))return!1;var b=this.getCommonAncestor(a);let c=this;for(;;){var d=c.getParentOrThrow();if(d===b){d=c.getIndexWithinParent();break}c=d}for(c=a;;){a=c.getParentOrThrow();if(a===b){b=c.getIndexWithinParent();break}c=a}return d<b}isParentOf(a){let b=this.__key;if(b===a.__key)return!1;for(;null!==a;){if(a.__key===b)return!0;a=a.getParent()}return!1}getNodesBetween(a){let b=this.isBefore(a),c=
[],d=new Set;for(var e=this;null!==e;){var f=e.__key;d.has(f)||(d.add(f),c.push(e));if(e===a)break;f=E(e)?b?e.getFirstChild():e.getLastChild():null;if(null!==f)e=f;else if(f=b?e.getNextSibling():e.getPreviousSibling(),null!==f)e=f;else{e=e.getParentOrThrow();d.has(e.__key)||c.push(e);if(e===a)break;f=e;do if(null===f&&p(68),e=b?f.getNextSibling():f.getPreviousSibling(),f=f.getParent(),null!==f)null!==e||d.has(f.__key)||c.push(f);else break;while(null===e)}}b||c.reverse();return c}isDirty(){let a=
F()._dirtyLeaves;return null!==a&&a.has(this.__key)}getLatest(){let a=I(this.__key);null===a&&p(113);return a}getWritable(){G();var a=ec(),b=F();a=a._nodeMap;let c=this.__key,d=this.getLatest(),e=d.__parent;b=b._cloneNotNeeded;var f=u();null!==f&&f.setCachedNodes(null);if(b.has(c))return gc(d),d;f=d.constructor.clone(d);f.__parent=e;f.__next=d.__next;f.__prev=d.__prev;E(d)&&E(f)?(yd(d)&&yd(f)&&(f.__textFormat=d.__textFormat),f.__first=d.__first,f.__last=d.__last,f.__size=d.__size,f.__indent=d.__indent,
f.__format=d.__format,f.__dir=d.__dir):B(d)&&B(f)&&(f.__format=d.__format,f.__style=d.__style,f.__mode=d.__mode,f.__detail=d.__detail);b.add(c);f.__key=c;gc(f);a.set(c,f);return f}getTextContent(){return""}getTextContentSize(){return this.getTextContent().length}createDOM(){p(70)}updateDOM(){p(71)}updateDOMProperties(){}exportDOM(a){return{element:this.createDOM(a._config,a)}}exportJSON(){p(72)}static importJSON(){p(18,this.name)}static transform(){return null}remove(a){ee(this,!0,a)}replace(a,b){G();
var c=u();null!==c&&(c=c.clone());Ec(this,a);let d=this.getLatest(),e=this.__key,f=a.__key,g=a.getWritable();a=this.getParentOrThrow().getWritable();let h=a.__size;fc(g);let k=d.getPreviousSibling(),m=d.getNextSibling(),q=d.__prev,n=d.__next,l=d.__parent;ee(d,!1,!0);null===k?a.__first=f:k.getWritable().__next=f;g.__prev=q;null===m?a.__last=f:m.getWritable().__prev=f;g.__next=n;g.__parent=l;a.__size=h;b&&(E(this)&&E(g)||p(139),this.getChildren().forEach(r=>{g.append(r)}));C(c)&&(Bb(c),b=c.anchor,c=
c.focus,b.key===e&&ie(b,g),c.key===e&&ie(c,g));hc()===e&&H(f);return g}insertAfter(a,b=!0){G();Ec(this,a);var c=this.getWritable();let d=a.getWritable();var e=d.getParent();let f=u();var g=!1,h=!1;if(null!==e){var k=a.getIndexWithinParent();fc(d);C(f)&&(h=e.__key,g=f.anchor,e=f.focus,g="element"===g.type&&g.key===h&&g.offset===k+1,h="element"===e.type&&e.key===h&&e.offset===k+1)}e=this.getNextSibling();k=this.getParentOrThrow().getWritable();let m=d.__key,q=c.__next;null===e?k.__last=m:e.getWritable().__prev=
m;k.__size++;c.__next=m;d.__next=q;d.__prev=c.__key;d.__parent=c.__parent;b&&C(f)&&(b=this.getIndexWithinParent(),ge(f,k,b+1),c=k.__key,g&&f.anchor.set(c,b+2,"element"),h&&f.focus.set(c,b+2,"element"));return a}insertBefore(a,b=!0){G();Ec(this,a);var c=this.getWritable();let d=a.getWritable(),e=d.__key;fc(d);let f=this.getPreviousSibling(),g=this.getParentOrThrow().getWritable(),h=c.__prev,k=this.getIndexWithinParent();null===f?g.__first=e:f.getWritable().__next=e;g.__size++;c.__prev=e;d.__prev=h;
d.__next=c.__key;d.__parent=c.__parent;c=u();b&&C(c)&&(b=this.getParentOrThrow(),ge(c,b,k));return a}isParentRequired(){return!1}createParentElementNode(){return je()}selectStart(){return this.selectPrevious()}selectEnd(){return this.selectNext(0,0)}selectPrevious(a,b){G();let c=this.getPreviousSibling(),d=this.getParentOrThrow();return null===c?d.select(0,0):E(c)?c.select():B(c)?c.select(a,b):(a=c.getIndexWithinParent()+1,d.select(a,a))}selectNext(a,b){G();let c=this.getNextSibling(),d=this.getParentOrThrow();
return null===c?d.select():E(c)?c.select(0,0):B(c)?c.select(a,b):(a=c.getIndexWithinParent(),d.select(a,a))}markDirty(){this.getWritable()}}function ke(a,b,c){c=c||b.getParentOrThrow().getLastChild();let d=b;for(b=[b];d!==c;)d.getNextSibling()||p(140),d=d.getNextSibling(),b.push(d);for(let e of b)a=a.insertAfter(e)}
class le extends he{static getType(){return"linebreak"}static clone(a){return new le(a.__key)}constructor(a){super(a)}getTextContent(){return"\n"}createDOM(){return document.createElement("br")}updateDOM(){return!1}static importDOM(){return{br:a=>{a:{var b=a.parentElement;if(null!==b){let c=b.firstChild;if(c===a||c.nextSibling===a&&me(c))if(b=b.lastChild,b===a||b.previousSibling===a&&me(b)){a=!0;break a}}a=!1}return a?null:{conversion:ne,priority:0}}}}static importJSON(){return oe()}exportJSON(){return{type:"linebreak",
version:1}}}function ne(){return{node:oe()}}function oe(){return Dc(new le)}function Jc(a){return a instanceof le}function me(a){return 3===a.nodeType&&/^( |\t|\r?\n)+$/.test(a.textContent||"")}function pe(a,b){return b&16?"code":b&128?"mark":b&32?"sub":b&64?"sup":null}function qe(a,b){return b&1?"strong":b&2?"em":"span"}
function re(a,b,c,d,e){a=d.classList;d=tc(e,"base");void 0!==d&&a.add(...d);d=tc(e,"underlineStrikethrough");let f=!1,g=b&8&&b&4;var h=c&8&&c&4;void 0!==d&&(h?(f=!0,g||a.add(...d)):g&&a.remove(...d));for(let k in hb)h=hb[k],d=tc(e,k),void 0!==d&&(c&h?!f||"underline"!==k&&"strikethrough"!==k?(0===(b&h)||g&&"underline"===k||"strikethrough"===k)&&a.add(...d):b&h&&a.remove(...d):b&h&&a.remove(...d))}
function se(a,b,c){let d=b.firstChild;c=c.isComposing();a+=c?db:"";if(null==d)b.textContent=a;else if(b=d.nodeValue,b!==a)if(c||Va){c=b.length;let e=a.length,f=0,g=0;for(;f<c&&f<e&&b[f]===a[f];)f++;for(;g+f<c&&g+f<e&&b[c-g-1]===a[e-g-1];)g++;a=[f,c-f-g,a.slice(f,e-g)];let [h,k,m]=a;0!==k&&d.deleteData(h,k);d.insertData(h,m)}else d.nodeValue=a}function te(a,b){b=document.createElement(b);b.appendChild(a);return b}
class ue extends he{static getType(){return"text"}static clone(a){return new ue(a.__text,a.__key)}constructor(a,b){super(b);this.__text=a;this.__format=0;this.__style="";this.__detail=this.__mode=0}getFormat(){return this.getLatest().__format}getDetail(){return this.getLatest().__detail}getMode(){let a=this.getLatest();return pb[a.__mode]}getStyle(){return this.getLatest().__style}isToken(){return 1===this.getLatest().__mode}isComposing(){return this.__key===hc()}isSegmented(){return 2===this.getLatest().__mode}isDirectionless(){return 0!==
(this.getLatest().__detail&1)}isUnmergeable(){return 0!==(this.getLatest().__detail&2)}hasFormat(a){a=hb[a];return 0!==(this.getFormat()&a)}isSimpleText(){return"text"===this.__type&&0===this.__mode}getTextContent(){return this.getLatest().__text}getFormatFlags(a,b){let c=this.getLatest().__format;return bc(c,a,b)}canHaveFormat(){return!0}createDOM(a){var b=this.__format,c=pe(this,b);let d=qe(this,b),e=document.createElement(null===c?d:c),f=e;this.hasFormat("code")&&e.setAttribute("spellcheck","false");
null!==c&&(f=document.createElement(d),e.appendChild(f));c=f;se(this.__text,c,this);a=a.theme.text;void 0!==a&&re(d,0,b,c,a);b=this.__style;""!==b&&(e.style.cssText=b);return e}updateDOM(a,b,c){let d=this.__text;var e=a.__format,f=this.__format,g=pe(this,e);let h=pe(this,f);var k=qe(this,e);let m=qe(this,f);if((null===g?k:g)!==(null===h?m:h))return!0;if(g===h&&k!==m)return e=b.firstChild,null==e&&p(48),a=g=document.createElement(m),se(d,a,this),c=c.theme.text,void 0!==c&&re(m,0,f,a,c),b.replaceChild(g,
e),!1;k=b;null!==h&&null!==g&&(k=b.firstChild,null==k&&p(49));se(d,k,this);c=c.theme.text;void 0!==c&&e!==f&&re(m,e,f,k,c);f=this.__style;a.__style!==f&&(b.style.cssText=f);return!1}static importDOM(){return{"#text":()=>({conversion:ve,priority:0}),b:()=>({conversion:we,priority:0}),code:()=>({conversion:xe,priority:0}),em:()=>({conversion:xe,priority:0}),i:()=>({conversion:xe,priority:0}),s:()=>({conversion:xe,priority:0}),span:()=>({conversion:ye,priority:0}),strong:()=>({conversion:xe,priority:0}),
sub:()=>({conversion:xe,priority:0}),sup:()=>({conversion:xe,priority:0}),u:()=>({conversion:xe,priority:0})}}static importJSON(a){let b=K(a.text);b.setFormat(a.format);b.setDetail(a.detail);b.setMode(a.mode);b.setStyle(a.style);return b}exportDOM(a){({element:a}=super.exportDOM(a));null!==a&&Hc(a)||p(132);a.style.whiteSpace="pre-wrap";this.hasFormat("bold")&&(a=te(a,"b"));this.hasFormat("italic")&&(a=te(a,"i"));this.hasFormat("strikethrough")&&(a=te(a,"s"));this.hasFormat("underline")&&(a=te(a,"u"));
return{element:a}}exportJSON(){return{detail:this.getDetail(),format:this.getFormat(),mode:this.getMode(),style:this.getStyle(),text:this.getTextContent(),type:"text",version:1}}selectionTransform(){}setFormat(a){let b=this.getWritable();b.__format="string"===typeof a?hb[a]:a;return b}setDetail(a){let b=this.getWritable();b.__detail="string"===typeof a?ib[a]:a;return b}setStyle(a){let b=this.getWritable();b.__style=a;return b}toggleFormat(a){let b=this.getFormat();a=bc(b,a,null);return this.setFormat(a)}toggleDirectionless(){let a=
this.getWritable();a.__detail^=1;return a}toggleUnmergeable(){let a=this.getWritable();a.__detail^=2;return a}setMode(a){a=ob[a];if(this.__mode===a)return this;let b=this.getWritable();b.__mode=a;return b}setTextContent(a){if(this.__text===a)return this;let b=this.getWritable();b.__text=a;return b}select(a,b){G();let c=u();var d=this.getTextContent();let e=this.__key;"string"===typeof d?(d=d.length,void 0===a&&(a=d),void 0===b&&(b=d)):b=a=0;if(C(c))d=hc(),d!==c.anchor.key&&d!==c.focus.key||H(e),c.setTextNodeRange(this,
a,this,b);else return ze(e,a,e,b,"text","text");return c}selectStart(){return this.select(0,0)}selectEnd(){let a=this.getTextContentSize();return this.select(a,a)}spliceText(a,b,c,d){let e=this.getWritable(),f=e.__text,g=c.length,h=a;0>h&&(h=g+h,0>h&&(h=0));let k=u();d&&C(k)&&(a+=g,k.setTextNodeRange(e,a,e,a));b=f.slice(0,h)+c+f.slice(h+b);e.__text=b;return e}canInsertTextBefore(){return!0}canInsertTextAfter(){return!0}splitText(...a){G();var b=this.getLatest(),c=b.getTextContent(),d=b.__key,e=hc(),
f=new Set(a);a=[];var g=c.length,h="";for(var k=0;k<g;k++)""!==h&&f.has(k)&&(a.push(h),h=""),h+=c[k];""!==h&&a.push(h);f=a.length;if(0===f)return[];if(a[0]===c)return[b];var m=a[0];c=b.getParentOrThrow();k=b.getFormat();let q=b.getStyle(),n=b.__detail;g=!1;b.isSegmented()?(h=K(m),h.__format=k,h.__style=q,h.__detail=n,g=!0):(h=b.getWritable(),h.__text=m);b=u();h=[h];m=m.length;for(let w=1;w<f;w++){var l=a[w],r=l.length;l=K(l).getWritable();l.__format=k;l.__style=q;l.__detail=n;let A=l.__key;r=m+r;
if(C(b)){let y=b.anchor,z=b.focus;y.key===d&&"text"===y.type&&y.offset>m&&y.offset<=r&&(y.key=A,y.offset-=m,b.dirty=!0);z.key===d&&"text"===z.type&&z.offset>m&&z.offset<=r&&(z.key=A,z.offset-=m,b.dirty=!0)}e===d&&H(A);m=r;h.push(l)}d=this.getPreviousSibling();e=this.getNextSibling();null!==d&&gc(d);null!==e&&gc(e);d=c.getWritable();e=this.getIndexWithinParent();g?(d.splice(e,0,h),this.remove()):d.splice(e,1,h);C(b)&&ge(b,c,e,f-1);return h}mergeWithSibling(a){var b=a===this.getPreviousSibling();b||
a===this.getNextSibling()||p(50);var c=this.__key;let d=a.__key,e=this.__text,f=e.length;hc()===d&&H(c);let g=u();if(C(g)){let h=g.anchor,k=g.focus;null!==h&&h.key===d&&(Ae(h,b,c,a,f),g.dirty=!0);null!==k&&k.key===d&&(Ae(k,b,c,a,f),g.dirty=!0)}c=a.__text;this.setTextContent(b?c+e:e+c);b=this.getWritable();a.remove();return b}isTextEntity(){return!1}}
function ye(a){a=a.style;let b=a.fontWeight,c="700"===b||"bold"===b,d="line-through"===a.textDecoration,e="italic"===a.fontStyle,f="underline"===a.textDecoration,g=a.verticalAlign;return{forChild:h=>{if(!B(h))return h;c&&h.toggleFormat("bold");d&&h.toggleFormat("strikethrough");e&&h.toggleFormat("italic");f&&h.toggleFormat("underline");"sub"===g&&h.toggleFormat("subscript");"super"===g&&h.toggleFormat("superscript");return h},node:null}}
function we(a){let b="normal"===a.style.fontWeight;return{forChild:c=>{B(c)&&!b&&c.toggleFormat("bold");return c},node:null}}let Be=new WeakMap;
function ve(a){null===a.parentElement&&p(129);for(var b=a.textContent||"",c,d=a.parentNode,e=[a];null!==d&&void 0===(c=Be.get(d))&&!("PRE"===d.nodeName||1===d.nodeType&&void 0!==d.style&&void 0!==d.style.whiteSpace&&d.style.whiteSpace.startsWith("pre"));)e.push(d),d=d.parentNode;c=void 0===c?d:c;for(d=0;d<e.length;d++)Be.set(e[d],c);if(null!==c){b=b.split(/(\r?\n|\t)/);a=[];e=b.length;for(c=0;c<e;c++)d=b[c],"\n"===d||"\r\n"===d?a.push(oe()):"\t"===d?a.push(Ce()):""!==d&&a.push(K(d));return{node:a}}b=
b.replace(/\r/g,"").replace(/[ \t\n]+/g," ");if(""===b)return{node:null};if(" "===b[0]){e=a;for(c=!0;null!==e&&null!==(e=Me(e,!1));)if(d=e.textContent||"",0<d.length){/[ \t\n]$/.test(d)&&(b=b.slice(1));c=!1;break}c&&(b=b.slice(1))}if(" "===b[b.length-1]){for(e=!0;null!==a&&null!==(a=Me(a,!0));)if(0<(a.textContent||"").replace(/^( |\t|\r?\n)+/,"").length){e=!1;break}e&&(b=b.slice(0,b.length-1))}return""===b?{node:null}:{node:K(b)}}
let Ne=new RegExp(/^(a|abbr|acronym|b|cite|code|del|em|i|ins|kbd|label|output|q|ruby|s|samp|span|strong|sub|sup|time|u|tt|var)$/,"i");function Me(a,b){for(;;){for(var c=void 0;null===(c=b?a.nextSibling:a.previousSibling);)if(a=a.parentElement,null===a)return null;a=c;if(1===a.nodeType&&(c=a.style.display,""===c&&null===a.nodeName.match(Ne)||""!==c&&!c.startsWith("inline")))return null;for(;null!==(c=b?a.firstChild:a.lastChild);)a=c;if(3===a.nodeType)return a;if("BR"===a.nodeName)return null}}
let Oe={code:"code",em:"italic",i:"italic",s:"strikethrough",strong:"bold",sub:"subscript",sup:"superscript",u:"underline"};function xe(a){let b=Oe[a.nodeName.toLowerCase()];return void 0===b?{node:null}:{forChild:c=>{B(c)&&!c.hasFormat(b)&&c.toggleFormat(b);return c},node:null}}function K(a=""){return Dc(new ue(a))}function B(a){return a instanceof ue}
class Pe extends ue{static getType(){return"tab"}static clone(a){let b=new Pe(a.__key);b.__text=a.__text;b.__format=a.__format;b.__style=a.__style;return b}constructor(a){super("\t",a);this.__detail=2}static importDOM(){return null}static importJSON(a){let b=Ce();b.setFormat(a.format);b.setStyle(a.style);return b}exportJSON(){return{...super.exportJSON(),type:"tab",version:1}}setTextContent(){p(126)}setDetail(){p(127)}setMode(){p(128)}canInsertTextBefore(){return!1}canInsertTextAfter(){return!1}}
function Ce(){return Dc(new Pe)}function Qe(a){return a instanceof Pe}
class Re{constructor(a,b,c){this._selection=null;this.key=a;this.offset=b;this.type=c}is(a){return this.key===a.key&&this.offset===a.offset&&this.type===a.type}isBefore(a){let b=this.getNode(),c=a.getNode(),d=this.offset;a=a.offset;if(E(b)){var e=b.getDescendantByIndex(d);b=null!=e?e:b}E(c)&&(e=c.getDescendantByIndex(a),c=null!=e?e:c);return b===c?d<a:b.isBefore(c)}getNode(){let a=I(this.key);null===a&&p(20);return a}set(a,b,c){let d=this._selection,e=this.key;this.key=a;this.offset=b;this.type=c;
ic()||(hc()===e&&H(a),null!==d&&(d.setCachedNodes(null),d.dirty=!0))}}function Se(a,b,c){return new Re(a,b,c)}function Te(a,b){let c=b.__key,d=a.offset,e="element";if(B(b))e="text",b=b.getTextContentSize(),d>b&&(d=b);else if(!E(b)){var f=b.getNextSibling();if(B(f))c=f.__key,d=0,e="text";else if(f=b.getParent())c=f.__key,d=b.getIndexWithinParent()+1}a.set(c,d,e)}function ie(a,b){if(E(b)){let c=b.getLastDescendant();E(c)||B(c)?Te(a,c):Te(a,b)}else Te(a,b)}
function Ue(a,b,c,d){let e=a.getNode(),f=e.getChildAtIndex(a.offset),g=K(),h=L(e)?je().append(g):g;g.setFormat(c);g.setStyle(d);null===f?e.append(h):f.insertBefore(h);a.is(b)&&b.set(g.__key,0,"text");a.set(g.__key,0,"text")}function Ve(a,b,c,d){a.key=b;a.offset=c;a.type=d}
class We{constructor(a){this._cachedNodes=null;this._nodes=a;this.dirty=!1}getCachedNodes(){return this._cachedNodes}setCachedNodes(a){this._cachedNodes=a}is(a){if(!$d(a))return!1;let b=this._nodes,c=a._nodes;return b.size===c.size&&Array.from(b).every(d=>c.has(d))}isCollapsed(){return!1}isBackward(){return!1}getStartEndPoints(){return null}add(a){this.dirty=!0;this._nodes.add(a);this._cachedNodes=null}delete(a){this.dirty=!0;this._nodes.delete(a);this._cachedNodes=null}clear(){this.dirty=!0;this._nodes.clear();
this._cachedNodes=null}has(a){return this._nodes.has(a)}clone(){return new We(new Set(this._nodes))}extract(){return this.getNodes()}insertRawText(){}insertText(){}insertNodes(a){let b=this.getNodes(),c=b.length;var d=b[c-1];if(B(d))d=d.select();else{let e=d.getIndexWithinParent()+1;d=d.getParentOrThrow().select(e,e)}d.insertNodes(a);for(a=0;a<c;a++)b[a].remove()}getNodes(){var a=this._cachedNodes;if(null!==a)return a;var b=this._nodes;a=[];for(let c of b)b=I(c),null!==b&&a.push(b);ic()||(this._cachedNodes=
a);return a}getTextContent(){let a=this.getNodes(),b="";for(let c=0;c<a.length;c++)b+=a[c].getTextContent();return b}}function C(a){return a instanceof Xe}
class Xe{constructor(a,b,c,d){this.anchor=a;this.focus=b;a._selection=this;b._selection=this;this._cachedNodes=null;this.format=c;this.style=d;this.dirty=!1}getCachedNodes(){return this._cachedNodes}setCachedNodes(a){this._cachedNodes=a}is(a){return C(a)?this.anchor.is(a.anchor)&&this.focus.is(a.focus)&&this.format===a.format&&this.style===a.style:!1}isCollapsed(){return this.anchor.is(this.focus)}getNodes(){var a=this._cachedNodes;if(null!==a)return a;a=this.anchor;var b=this.focus,c=a.isBefore(b),
d=c?a:b;c=c?b:a;a=d.getNode();b=c.getNode();let e=d.offset;d=c.offset;E(a)&&(c=a.getDescendantByIndex(e),a=null!=c?c:a);E(b)&&(c=b.getDescendantByIndex(d),null!==c&&c!==a&&b.getChildAtIndex(d)===c&&(c=c.getPreviousSibling()),b=null!=c?c:b);a=a.is(b)?E(a)&&0<a.getChildrenSize()?[]:[a]:a.getNodesBetween(b);ic()||(this._cachedNodes=a);return a}setTextNodeRange(a,b,c,d){Ve(this.anchor,a.__key,b,"text");Ve(this.focus,c.__key,d,"text");this._cachedNodes=null;this.dirty=!0}getTextContent(){let a=this.getNodes();
if(0===a.length)return"";let b=a[0],c=a[a.length-1],d=this.anchor,e=this.focus,f=d.isBefore(e),[g,h]=Ye(this),k="",m=!0;for(let q=0;q<a.length;q++){let n=a[q];if(E(n)&&!n.isInline())m||(k+="\n"),m=n.isEmpty()?!1:!0;else if(m=!1,B(n)){let l=n.getTextContent();if(n===b)if(n===c){if("element"!==d.type||"element"!==e.type||e.offset===d.offset)l=g<h?l.slice(g,h):l.slice(h,g)}else l=f?l.slice(g):l.slice(h);else n===c&&(l=f?l.slice(0,h):l.slice(0,g));k+=l}else!x(n)&&!Jc(n)||n===c&&this.isCollapsed()||(k+=
n.getTextContent())}return k}applyDOMRange(a){let b=F(),c=b.getEditorState()._selection;a=Ze(a.startContainer,a.startOffset,a.endContainer,a.endOffset,b,c);if(null!==a){var [d,e]=a;Ve(this.anchor,d.key,d.offset,d.type);Ve(this.focus,e.key,e.offset,e.type);this._cachedNodes=null}}clone(){let a=this.anchor,b=this.focus;return new Xe(Se(a.key,a.offset,a.type),Se(b.key,b.offset,b.type),this.format,this.style)}toggleFormat(a){this.format=bc(this.format,a,null);this.dirty=!0}setStyle(a){this.style=a;this.dirty=
!0}hasFormat(a){return 0!==(this.format&hb[a])}insertRawText(a){a=a.split(/(\r?\n|\t)/);let b=[],c=a.length;for(let d=0;d<c;d++){let e=a[d];"\n"===e||"\r\n"===e?b.push(oe()):"\t"===e?b.push(Ce()):b.push(K(e))}this.insertNodes(b)}insertText(a){var b=this.anchor,c=this.focus,d=this.isCollapsed()||b.isBefore(c),e=this.format,f=this.style;d&&"element"===b.type?Ue(b,c,e,f):d||"element"!==c.type||Ue(c,b,e,f);var g=this.getNodes(),h=g.length,k=d?c:b;c=(d?b:c).offset;var m=k.offset;b=g[0];B(b)||p(26);d=b.getTextContent().length;
var q=b.getParentOrThrow(),n=g[h-1];if(this.isCollapsed()&&c===d&&(b.isSegmented()||b.isToken()||!b.canInsertTextAfter()||!q.canInsertTextAfter()&&null===b.getNextSibling())){var l=b.getNextSibling();B(l)&&l.canInsertTextBefore()&&!$b(l)||(l=K(),l.setFormat(e),q.canInsertTextAfter()?b.insertAfter(l):q.insertAfter(l));l.select(0,0);b=l;if(""!==a){this.insertText(a);return}}else if(this.isCollapsed()&&0===c&&(b.isSegmented()||b.isToken()||!b.canInsertTextBefore()||!q.canInsertTextBefore()&&null===b.getPreviousSibling())){l=
b.getPreviousSibling();if(!B(l)||$b(l))l=K(),l.setFormat(e),q.canInsertTextBefore()?b.insertBefore(l):q.insertBefore(l);l.select();b=l;if(""!==a){this.insertText(a);return}}else if(b.isSegmented()&&c!==d)q=K(b.getTextContent()),q.setFormat(e),b.replace(q),b=q;else if(!(this.isCollapsed()||""===a||(l=n.getParent(),q.canInsertTextBefore()&&q.canInsertTextAfter()&&(!E(l)||l.canInsertTextBefore()&&l.canInsertTextAfter())))){this.insertText("");$e(this.anchor,this.focus,null);this.insertText(a);return}if(1===
h)if(b.isToken())a=K(a),a.select(),b.replace(a);else{g=b.getFormat();h=b.getStyle();if(c===m&&(g!==e||h!==f))if(""===b.getTextContent())b.setFormat(e),b.setStyle(f);else{g=K(a);g.setFormat(e);g.setStyle(f);g.select();0===c?b.insertBefore(g,!1):([h]=b.splitText(c),h.insertAfter(g,!1));g.isComposing()&&"text"===this.anchor.type&&(this.anchor.offset-=a.length);return}else if(Qe(b)){a=K(a);a.setFormat(e);a.setStyle(f);a.select();b.replace(a);return}b=b.spliceText(c,m-c,a,!0);""===b.getTextContent()?b.remove():
"text"===this.anchor.type&&(b.isComposing()?this.anchor.offset-=a.length:(this.format=g,this.style=h))}else{e=new Set([...b.getParentKeys(),...n.getParentKeys()]);l=E(b)?b:b.getParentOrThrow();f=E(n)?n:n.getParentOrThrow();q=n;if(!l.is(f)&&f.isInline()){do q=f,f=f.getParentOrThrow();while(f.isInline())}if("text"===k.type&&(0!==m||""===n.getTextContent())||"element"===k.type&&n.getIndexWithinParent()<m)if(B(n)&&!n.isToken()&&m!==n.getTextContentSize()){if(n.isSegmented()){var r=K(n.getTextContent());
n.replace(r);n=r}L(k.getNode())||"text"!==k.type||(n=n.spliceText(0,m,""));e.add(n.__key)}else k=n.getParentOrThrow(),k.canBeEmpty()||1!==k.getChildrenSize()?n.remove():k.remove();else e.add(n.__key);k=f.getChildren();m=new Set(g);n=l.is(f);l=l.isInline()&&null===b.getNextSibling()?l:b;for(r=k.length-1;0<=r;r--){let w=k[r];if(w.is(b)||E(w)&&w.isParentOf(b))break;w.isAttached()&&(!m.has(w)||w.is(q)?n||l.insertAfter(w,!1):w.remove())}if(!n)for(k=f,f=null;null!==k;){m=k.getChildren();n=m.length;if(0===
n||m[n-1].is(f))e.delete(k.__key),f=k;k=k.getParent()}b.isToken()?c===d?b.select():(a=K(a),a.select(),b.replace(a)):(b=b.spliceText(c,d-c,a,!0),""===b.getTextContent()?b.remove():b.isComposing()&&"text"===this.anchor.type&&(this.anchor.offset-=a.length));for(a=1;a<h;a++)b=g[a],e.has(b.__key)||b.remove()}}removeText(){this.insertText("")}formatText(a){if(this.isCollapsed())this.toggleFormat(a),H(null);else{var b=this.getNodes(),c=[];for(var d of b)B(d)&&c.push(d);var e=c.length;if(0===e)this.toggleFormat(a),
H(null);else{d=this.anchor;var f=this.focus,g=this.isBackward();b=g?f:d;d=g?d:f;var h=0,k=c[0];f="element"===b.type?0:b.offset;"text"===b.type&&f===k.getTextContentSize()&&(h=1,k=c[1],f=0);if(null!=k){g=k.getFormatFlags(a,null);var m=e-1,q=c[m];e="text"===d.type?d.offset:q.getTextContentSize();if(k.is(q))f!==e&&(0===f&&e===k.getTextContentSize()?k.setFormat(g):(a=k.splitText(f,e),a=0===f?a[0]:a[1],a.setFormat(g),"text"===b.type&&b.set(a.__key,0,"text"),"text"===d.type&&d.set(a.__key,e-f,"text")),
this.format=g);else{0!==f&&([,k]=k.splitText(f),f=0);k.setFormat(g);var n=q.getFormatFlags(a,g);0<e&&(e!==q.getTextContentSize()&&([q]=q.splitText(e)),q.setFormat(n));for(h+=1;h<m;h++){let l=c[h];if(!l.isToken()){let r=l.getFormatFlags(a,n);l.setFormat(r)}}"text"===b.type&&b.set(k.__key,f,"text");"text"===d.type&&d.set(q.__key,e,"text");this.format=g|n}}}}}insertNodes(a){if(0!==a.length){if("root"===this.anchor.key){this.insertParagraph();var b=u();C(b)||p(134);return b.insertNodes(a)}b=this.isBackward()?
this.focus:this.anchor;var c=Kc(b.getNode(),Ic);b=a[a.length-1];if("__language"in c&&E(c))if("__language"in a[0])this.insertText(a[0].getTextContent());else{var d=af(this);c.splice(d,0,a);b.selectEnd()}else if(a.some(g=>(E(g)||x(g))&&!g.isInline())){b=bf(a);a=b.getLastDescendant();var e=b.getChildren();b=E(c)&&c.isEmpty()?null:this.insertParagraph();d=e[e.length-1];var f=e[0];(g=>E(g)&&Ic(g)&&!g.isEmpty()&&E(c)&&(!c.isEmpty()||"__value"in c&&"__checked"in c))(f)&&(E(c)||p(135),c.append(...f.getChildren()),
f=e[1]);f&&ke(c,f);e=Kc(a,Ic);b&&E(e)&&("__value"in b&&"__checked"in b||Ic(d))&&(e.append(...b.getChildren()),b.remove());E(c)&&c.isEmpty()&&c.remove();a.selectEnd();a=E(c)?c.getLastChild():null;Jc(a)&&e!==c&&a.remove()}else E(c)||p(135),d=af(this),c.splice(d,0,a),b.selectEnd()}}insertParagraph(){if("root"===this.anchor.key){var a=je();J().splice(this.anchor.offset,0,[a]);a.select();return a}var b=af(this);a=Kc(this.anchor.getNode(),Ic);E(a)||p(136);b=(b=a.getChildAtIndex(b))?[b,...b.getNextSiblings()]:
[];return(a=a.insertNewAfter(this,!1))?(a.append(...b),a.selectStart(),a):null}insertLineBreak(a){var b=oe();this.insertNodes([b]);a&&(a=b.getParentOrThrow(),b=b.getIndexWithinParent(),a.select(b,b))}extract(){var a=this.getNodes(),b=a.length,c=b-1,d=this.anchor;let e=this.focus;var f=a[0];let g=a[c],[h,k]=Ye(this);if(0===b)return[];if(1===b)return B(f)&&!this.isCollapsed()?(a=h>k?k:h,c=f.splitText(a,h>k?h:k),a=0===a?c[0]:c[1],null!=a?[a]:[]):[f];b=d.isBefore(e);B(f)&&(d=b?h:k,d===f.getTextContentSize()?
a.shift():0!==d&&([,f]=f.splitText(d),a[0]=f));B(g)&&(f=g.getTextContent().length,b=b?k:h,0===b?a.pop():b!==f&&([g]=g.splitText(b),a[c]=g));return a}modify(a,b,c){var d=this.focus,e=this.anchor,f="move"===a,g=wc(d,b);if(x(g)&&!g.isIsolated())f&&g.isKeyboardSelectable()?(b=cf(),b.add(g.__key),Bb(b)):(a=b?g.getPreviousSibling():g.getNextSibling(),B(a)?(g=a.__key,b=b?a.getTextContent().length:0,d.set(g,b,"text"),f&&e.set(g,b,"text")):(c=g.getParentOrThrow(),E(a)?(c=a.__key,g=b?a.getChildrenSize():0):
(g=g.getIndexWithinParent(),c=c.__key,b||g++),d.set(c,g,"element"),f&&e.set(c,g,"element")));else if(e=F(),d=yb(e._window)){var h=e._blockCursorElement,k=e._rootElement;null===k||null===h||!E(g)||g.isInline()||g.canBeEmpty()||Gc(h,e,k);d.modify(a,b?"backward":"forward",c);if(0<d.rangeCount&&(g=d.getRangeAt(0),e=this.anchor.getNode(),e=L(e)?e:Ac(e),this.applyDOMRange(g),this.dirty=!0,!f)){f=this.getNodes();a=[];c=!1;for(h=0;h<f.length;h++)k=f[h],zc(k,e)?a.push(k):c=!0;c&&0<a.length&&(b?(b=a[0],E(b)?
b.selectStart():b.getParentOrThrow().selectStart()):(b=a[a.length-1],E(b)?b.selectEnd():b.getParentOrThrow().selectEnd()));if(d.anchorNode!==g.startContainer||d.anchorOffset!==g.startOffset)b=this.focus,f=this.anchor,d=f.key,g=f.offset,e=f.type,Ve(f,b.key,b.offset,b.type),Ve(b,d,g,e),this._cachedNodes=null}}}forwardDeletion(a,b,c){return!c&&("element"===a.type&&E(b)&&a.offset===b.getChildrenSize()||"text"===a.type&&a.offset===b.getTextContentSize())&&(a=b.getParent(),b=b.getNextSibling()||(null===
a?null:a.getNextSibling()),E(b)&&b.isShadowRoot())?!0:!1}deleteCharacter(a){let b=this.isCollapsed();if(this.isCollapsed()){var c=this.anchor,d=c.getNode();if(this.forwardDeletion(c,d,a))return;var e=this.focus,f=wc(e,a);if(x(f)&&!f.isIsolated()){f.isKeyboardSelectable()&&E(d)&&0===d.getChildrenSize()?(d.remove(),a=cf(),a.add(f.__key),Bb(a)):(f.remove(),F().dispatchCommand(ba,void 0));return}if(!a&&E(f)&&E(d)&&d.isEmpty()){d.remove();f.selectStart();return}this.modify("extend",a,"character");if(!this.isCollapsed()){f=
"text"===e.type?e.getNode():null;d="text"===c.type?c.getNode():null;if(null!==f&&f.isSegmented()){if(c=e.offset,e=f.getTextContentSize(),f.is(d)||a&&c!==e||!a&&0!==c){df(f,a,c);return}}else if(null!==d&&d.isSegmented()&&(c=c.offset,e=d.getTextContentSize(),d.is(f)||a&&0!==c||!a&&c!==e)){df(d,a,c);return}d=this.anchor;f=this.focus;c=d.getNode();e=f.getNode();if(c===e&&"text"===d.type&&"text"===f.type){var g=d.offset,h=f.offset;let k=g<h;e=k?g:h;h=k?h:g;g=h-1;e!==g&&(c=c.getTextContent().slice(e,h),
nc(c)||(a?f.offset=g:d.offset=g))}}else if(a&&0===c.offset&&("element"===c.type?c.getNode():c.getNode().getParentOrThrow()).collapseAtStart(this))return}this.removeText();a&&!b&&this.isCollapsed()&&"element"===this.anchor.type&&0===this.anchor.offset&&(a=this.anchor.getNode(),a.isEmpty()&&L(a.getParent())&&0===a.getIndexWithinParent()&&a.collapseAtStart(this))}deleteLine(a){this.isCollapsed()&&("text"===this.anchor.type&&this.modify("extend",a,"lineboundary"),0===(a?this.focus:this.anchor).offset&&
this.modify("extend",a,"character"));this.removeText()}deleteWord(a){if(this.isCollapsed()){let b=this.anchor,c=b.getNode();if(this.forwardDeletion(b,c,a))return;this.modify("extend",a,"word")}this.removeText()}isBackward(){return this.focus.isBefore(this.anchor)}getStartEndPoints(){return[this.anchor,this.focus]}}function $d(a){return a instanceof We}function ef(a){let b=a.offset;if("text"===a.type)return b;a=a.getNode();return b===a.getChildrenSize()?a.getTextContent().length:0}
function Ye(a){a=a.getStartEndPoints();if(null===a)return[0,0];let [b,c]=a;return"element"===b.type&&"element"===c.type&&b.key===c.key&&b.offset===c.offset?[0,0]:[ef(b),ef(c)]}function df(a,b,c){let d=a.getTextContent().split(/(?=\s)/g),e=d.length,f=0,g=0;for(let h=0;h<e;h++){let k=d[h],m=h===e-1;g=f;f+=k.length;if(b&&f===c||f>c||m){d.splice(h,1);m&&(g=void 0);break}}b=d.join("").trim();""===b?a.remove():(a.setTextContent(b),a.select(g,g))}
function ff(a,b,c,d){var e=b;if(1===a.nodeType){let h=!1;var f=a.childNodes,g=f.length;e===g&&(h=!0,e=g-1);let k=f[e];g=!1;k===d._blockCursorElement?(k=f[e+1],g=!0):null!==d._blockCursorElement&&e--;d=mc(k);if(B(d))e=h?d.getTextContentSize():0;else{f=mc(a);if(null===f)return null;if(E(f)){e=Math.min(f.getChildrenSize(),e);a=f.getChildAtIndex(e);if(b=E(a))b=a.getParent(),b=null===c||null===b||!b.canBeEmpty()||b!==c.getNode();b&&(c=h?a.getLastDescendant():a.getFirstDescendant(),null===c?(f=a,e=0):(a=
c,f=E(a)?a:a.getParentOrThrow()));B(a)?(d=a,f=null,e=h?a.getTextContentSize():0):a!==f&&h&&!g&&e++}else e=f.getIndexWithinParent(),e=0===b&&x(f)&&mc(a)===f?e:e+1,f=f.getParentOrThrow();if(E(f))return Se(f.__key,e,"element")}}else d=mc(a);return B(d)?Se(d.__key,e,"text"):null}
function gf(a,b,c){var d=a.offset,e=a.getNode();0===d?(d=e.getPreviousSibling(),e=e.getParent(),b)?(c||!b)&&null===d&&E(e)&&e.isInline()&&(b=e.getPreviousSibling(),B(b)&&(a.key=b.__key,a.offset=b.getTextContent().length)):E(d)&&!c&&d.isInline()?(a.key=d.__key,a.offset=d.getChildrenSize(),a.type="element"):B(d)&&(a.key=d.__key,a.offset=d.getTextContent().length):d===e.getTextContent().length&&(d=e.getNextSibling(),e=e.getParent(),b&&E(d)&&d.isInline()?(a.key=d.__key,a.offset=0,a.type="element"):(c||
b)&&null===d&&E(e)&&e.isInline()&&!e.canInsertTextAfter()&&(b=e.getNextSibling(),B(b)&&(a.key=b.__key,a.offset=0)))}function $e(a,b,c){if("text"===a.type&&"text"===b.type){var d=a.isBefore(b);let e=a.is(b);gf(a,d,e);gf(b,!d,e);e&&(b.key=a.key,b.offset=a.offset,b.type=a.type);d=F();d.isComposing()&&d._compositionKey!==a.key&&C(c)&&(d=c.anchor,c=c.focus,Ve(a,d.key,d.offset,d.type),Ve(b,c.key,c.offset,c.type))}}
function Ze(a,b,c,d,e,f){if(null===a||null===c||!Xb(e,a,c))return null;b=ff(a,b,C(f)?f.anchor:null,e);if(null===b)return null;d=ff(c,d,C(f)?f.focus:null,e);if(null===d||"element"===b.type&&"element"===d.type&&(a=mc(a),c=mc(c),x(a)&&x(c)))return null;$e(b,d,f);return[b,d]}function ze(a,b,c,d,e,f){let g=ec();a=new Xe(Se(a,b,e),Se(c,d,f),0,"");a.dirty=!0;return g._selection=a}function cf(){return new We(new Set)}
function hf(a){let b=a.getEditorState()._selection,c=yb(a._window);return C(b)||null==b?Wd(b,c,a,null):b.clone()}
function Wd(a,b,c,d){var e=c._window;if(null===e)return null;var f=(e=d||e.event)?e.type:void 0;d="selectionchange"===f;e=!rb&&(d||"beforeinput"===f||"compositionstart"===f||"compositionend"===f||"click"===f&&e&&3===e.detail||"drop"===f||void 0===f);let g;if(!C(a)||e){if(null===b)return null;e=b.anchorNode;f=b.focusNode;g=b.anchorOffset;b=b.focusOffset;if(d&&C(a)&&!Xb(c,e,f))return a.clone()}else return a.clone();c=Ze(e,g,f,b,c,a);if(null===c)return null;let [h,k]=c;return new Xe(h,k,C(a)?a.format:
0,C(a)?a.style:"")}function u(){return ec()._selection}function rc(){return F()._editorState._selection}
function ge(a,b,c,d=1){var e=a.anchor,f=a.focus,g=e.getNode(),h=f.getNode();if(b.is(g)||b.is(h)){g=b.__key;if(a.isCollapsed()){if(b=e.offset,c<=b&&0<d||c<b&&0>d)c=Math.max(0,b+d),e.set(g,c,"element"),f.set(g,c,"element"),jf(a)}else{let m=a.isBackward();h=m?f:e;var k=h.getNode();e=m?e:f;f=e.getNode();b.is(k)&&(k=h.offset,(c<=k&&0<d||c<k&&0>d)&&h.set(g,Math.max(0,k+d),"element"));b.is(f)&&(b=e.offset,(c<=b&&0<d||c<b&&0>d)&&e.set(g,Math.max(0,b+d),"element"))}jf(a)}}
function jf(a){var b=a.anchor,c=b.offset;let d=a.focus;var e=d.offset,f=b.getNode(),g=d.getNode();if(a.isCollapsed())E(f)&&(g=f.getChildrenSize(),g=(e=c>=g)?f.getChildAtIndex(g-1):f.getChildAtIndex(c),B(g)&&(c=0,e&&(c=g.getTextContentSize()),b.set(g.__key,c,"text"),d.set(g.__key,c,"text")));else{if(E(f)){let h=f.getChildrenSize();c=(a=c>=h)?f.getChildAtIndex(h-1):f.getChildAtIndex(c);B(c)&&(f=0,a&&(f=c.getTextContentSize()),b.set(c.__key,f,"text"))}E(g)&&(c=g.getChildrenSize(),e=(b=e>=c)?g.getChildAtIndex(c-
1):g.getChildAtIndex(e),B(e)&&(g=0,b&&(g=e.getTextContentSize()),d.set(e.__key,g,"text")))}}function kf(a,b){b=b.getEditorState()._selection;a=a._selection;if(C(a)){var c=a.anchor;let d=a.focus,e;"text"===c.type&&(e=c.getNode(),e.selectionTransform(b,a));"text"===d.type&&(c=d.getNode(),e!==c&&c.selectionTransform(b,a))}}
function fe(a,b,c,d,e){let f=null,g=0,h=null;null!==d?(f=d.__key,B(d)?(g=d.getTextContentSize(),h="text"):E(d)&&(g=d.getChildrenSize(),h="element")):null!==e&&(f=e.__key,B(e)?h="text":E(e)&&(h="element"));null!==f&&null!==h?a.set(f,g,h):(g=b.getIndexWithinParent(),-1===g&&(g=c.getChildrenSize()),a.set(c.__key,g,"element"))}function Ae(a,b,c,d,e){"text"===a.type?(a.key=c,b||(a.offset+=e)):a.offset>d.getIndexWithinParent()&&--a.offset}
function af(a){a.isCollapsed()||a.removeText();var b=a.anchor;a=b.getNode();for(b=b.offset;!Ic(a);)[a,b]=lf(a,b);return b}
function lf(a,b){var c=a.getParent();if(!c)return c=je(),J().append(c),c.select(),[J(),0];if(B(a)){var d=a.splitText(b);if(0===d.length)return[c,a.getIndexWithinParent()];a=0===b?0:1;a=d[0].getIndexWithinParent()+a;return[c,a]}if(!E(a)||0===b)return[c,a.getIndexWithinParent()];if(d=a.getChildAtIndex(b))b=new Xe(Se(a.__key,b,"element"),Se(a.__key,b,"element"),0,""),(b=a.insertNewAfter(b))&&b.append(d,...d.getNextSiblings());return[c,a.getIndexWithinParent()+1]}
function bf(a){let b=je(),c=null;for(let d=0;d<a.length;d++){let e=a[d],f=Jc(e);if(f||x(e)&&e.isInline()||E(e)&&e.isInline()||B(e)||e.isParentRequired()){if(null===c&&(c=e.createParentElementNode(),b.append(c),f))continue;null!==c&&c.append(e)}else b.append(e),c=null}return b}function Nb(a){return"object"===typeof a&&null!==a&&"mergeWithSibling"in a&&"function"===typeof a.mergeWithSibling}let T=null,U=null,V=!1,mf=!1,dc=0,nf={characterData:!0,childList:!0,subtree:!0};
function ic(){return V||null!==T&&T._readOnly}function G(){V&&p(13)}function ec(){null===T&&p(15);return T}function F(){null===U&&p(16);return U}function of(a,b,c){var d=b.__type;let e=a._nodes.get(d);void 0===e&&p(30,d);a=c.get(d);void 0===a&&(a=Array.from(e.transforms),c.set(d,a));c=a.length;for(d=0;d<c&&(a[d](b),b.isAttached());d++);}function pf(a,b){b=b._dirtyLeaves;a=a._nodeMap;for(let c of b)b=a.get(c),B(b)&&b.isAttached()&&b.isSimpleText()&&!b.isUnmergeable()&&Jb(b)}
function qf(a,b){let c=b._dirtyLeaves,d=b._dirtyElements;a=a._nodeMap;let e=hc(),f=new Map;var g=c;let h=g.size;for(var k=d,m=k.size;0<h||0<m;){if(0<h){b._dirtyLeaves=new Set;for(let q of g)g=a.get(q),B(g)&&g.isAttached()&&g.isSimpleText()&&!g.isUnmergeable()&&Jb(g),g&&Nb(g)&&!B(g)&&Mb(g),void 0!==g&&void 0!==g&&g.__key!==e&&g.isAttached()&&of(b,g,f),c.add(q);g=b._dirtyLeaves;h=g.size;if(0<h){dc++;continue}}b._dirtyLeaves=new Set;b._dirtyElements=new Map;for(let q of k)if(k=q[0],m=q[1],"root"===k||
m)g=a.get(k),void 0!==g&&void 0!==g&&g.__key!==e&&g.isAttached()&&of(b,g,f),void 0!==g&&Nb(g)&&Mb(g),d.set(k,m);g=b._dirtyLeaves;h=g.size;k=b._dirtyElements;m=k.size;dc++}b._dirtyLeaves=c;b._dirtyElements=d}function rf(a,b){var c=a.type,d=b.get(c);void 0===d&&p(17,c);c=d.klass;a.type!==c.getType()&&p(18,c.name);c=c.importJSON(a);a=a.children;if(E(c)&&Array.isArray(a))for(d=0;d<a.length;d++){let e=rf(a[d],b);c.append(e)}return c}
function sf(a,b){let c=T,d=V,e=U;T=a;V=!0;U=null;try{return b()}finally{T=c,V=d,U=e}}
function tf(a,b){let c=a._pendingEditorState,d=a._rootElement,e=a._headless||null===d;if(null!==c){var f=a._editorState,g=f._selection,h=c._selection,k=0!==a._dirtyType,m=T,q=V,n=U,l=a._updating,r=a._observer,w=null;a._pendingEditorState=null;a._editorState=c;if(!e&&k&&null!==r){U=a;T=c;V=!1;a._updating=!0;try{let D=a._dirtyType,P=a._dirtyElements,Q=a._dirtyLeaves;r.disconnect();var A=D,y=P,z=Q;N=Oc=M="";Rc=2===A;cd=null;O=a;Pc=a._config;Qc=a._nodes;Tc=O._listeners.mutation;dd=y;ed=z;fd=f._nodeMap;
gd=c._nodeMap;Sc=c._readOnly;hd=new Map(a._keyToDOMMap);let ja=new Map;id=ja;wd("root",null);id=hd=Pc=gd=fd=ed=dd=Qc=O=void 0;w=ja}catch(D){D instanceof Error&&a._onError(D);if(mf)throw D;uf(a,null,d,c);Eb(a);a._dirtyType=2;mf=!0;tf(a,f);mf=!1;return}finally{r.observe(d,nf),a._updating=l,T=m,V=q,U=n}}c._readOnly||(c._readOnly=!0);var R=a._dirtyLeaves,X=a._dirtyElements,Wa=a._normalizedNodes,ma=a._updateTags,Uc=a._deferred;k&&(a._dirtyType=0,a._cloneNotNeeded.clear(),a._dirtyLeaves=new Set,a._dirtyElements=
new Map,a._normalizedNodes=new Set,a._updateTags=new Set);var De=a._decorators,Qb=a._pendingDecorators||De,Ff=c._nodeMap,Vc;for(Vc in Qb)Ff.has(Vc)||(Qb===De&&(Qb=jc(a)),delete Qb[Vc]);var ka=e?null:yb(a._window);if(a._editable&&null!==ka&&(k||null===h||h.dirty)){U=a;T=c;try{null!==r&&r.disconnect();if(k||null===h||h.dirty){let D=a._blockCursorElement;null!==D&&Gc(D,a,d);a:{let P=ka.anchorNode,Q=ka.focusNode,ja=ka.anchorOffset,lb=ka.focusOffset,Y=document.activeElement;if(!(ma.has("collaboration")&&
Y!==d||null!==Y&&Wb(Y)))if(C(h)){var mb=h.anchor,Wc=h.focus,Ee=mb.key,Gf=Wc.key,Fe=yc(a,Ee),Ge=yc(a,Gf),Rb=mb.offset,He=Wc.offset,Xc=h.format,Yc=h.style,Ie=h.isCollapsed(),nb=Fe,Sb=Ge,Zc=!1;if("text"===mb.type){nb=ac(Fe);let Z=mb.getNode();Zc=Z.getFormat()!==Xc||Z.getStyle()!==Yc}else C(g)&&"text"===g.anchor.type&&(Zc=!0);"text"===Wc.type&&(Sb=ac(Ge));if(null!==nb&&null!==Sb){if(Ie&&(null===g||Zc||C(g)&&(g.format!==Xc||g.style!==Yc))){var Hf=performance.now();Rd=[Xc,Yc,Rb,Ee,Hf]}if(ja===Rb&&lb===
He&&P===nb&&Q===Sb&&("Range"!==ka.type||!Ie)&&(null!==Y&&d.contains(Y)||d.focus({preventScroll:!0}),"element"!==mb.type))break a;try{ka.setBaseAndExtent(nb,Rb,Sb,He)}catch(Z){}if(!ma.has("skip-scroll-into-view")&&h.isCollapsed()&&null!==d&&d===document.activeElement){let Z=h instanceof Xe&&"element"===h.anchor.type?nb.childNodes[Rb]||null:0<ka.rangeCount?ka.getRangeAt(0):null;if(null!==Z){let aa;if(Z instanceof Text){let W=document.createRange();W.selectNode(Z);aa=W.getBoundingClientRect()}else aa=
Z.getBoundingClientRect();let ya=d.ownerDocument,Fa=ya.defaultView;if(null!==Fa)for(var {top:$c,bottom:ad}=aa,Tb,Ub,ra=d;null!==ra;){let W=ra===ya.body;if(W)Tb=0,Ub=Fb(a).innerHeight;else{let Vb=ra.getBoundingClientRect();Tb=Vb.top;Ub=Vb.bottom}let Ga=0;$c<Tb?Ga=-(Tb-$c):ad>Ub&&(Ga=ad-Ub);if(0!==Ga)if(W)Fa.scrollBy(0,Ga);else{let Vb=ra.scrollTop;ra.scrollTop+=Ga;let Je=ra.scrollTop-Vb;$c-=Je;ad-=Je}if(W)break;ra=Zb(ra)}}}Nd=!0}}else null!==g&&Xb(a,P,Q)&&ka.removeAllRanges()}}a:{let D=a._blockCursorElement;
if(C(h)&&h.isCollapsed()&&"element"===h.anchor.type&&d.contains(document.activeElement)){let P=h.anchor,Q=P.getNode(),ja=P.offset,lb=Q.getChildrenSize(),Y=!1,Z=null;if(ja===lb){let aa=Q.getChildAtIndex(ja-1);Fc(aa)&&(Y=!0)}else{let aa=Q.getChildAtIndex(ja);if(Fc(aa)){let ya=aa.getPreviousSibling();if(null===ya||Fc(ya))Y=!0,Z=a.getElementByKey(aa.__key)}}if(Y){let aa=a.getElementByKey(Q.__key);if(null===D){let ya=a._config.theme,Fa=document.createElement("div");Fa.contentEditable="false";Fa.setAttribute("data-lexical-cursor",
"true");let W=ya.blockCursor;if(void 0!==W){if("string"===typeof W){let Ga=qb(W);W=ya.blockCursor=Ga}void 0!==W&&Fa.classList.add(...W)}a._blockCursorElement=D=Fa}d.style.caretColor="transparent";null===Z?aa.appendChild(D):aa.insertBefore(D,Z);break a}}null!==D&&Gc(D,a,d)}null!==r&&r.observe(d,nf)}finally{U=n,T=m}}if(null!==w){var If=w;let D=Array.from(a._listeners.mutation),P=D.length;for(let Q=0;Q<P;Q++){let [ja,lb]=D[Q],Y=If.get(lb);void 0!==Y&&ja(Y,{dirtyLeaves:R,prevEditorState:f,updateTags:ma})}}C(h)||
null===h||null!==g&&g.is(h)||a.dispatchCommand(ba,void 0);var bd=a._pendingDecorators;null!==bd&&(a._decorators=bd,a._pendingDecorators=null,vf("decorator",a,!0,bd));var Jf=kc(b||f),Ke=kc(c);Jf!==Ke&&vf("textcontent",a,!0,Ke);vf("update",a,!0,{dirtyElements:X,dirtyLeaves:R,editorState:c,normalizedNodes:Wa,prevEditorState:b||f,tags:ma});a._deferred=[];if(0!==Uc.length){let D=a._updating;a._updating=!0;try{for(let P=0;P<Uc.length;P++)Uc[P]()}finally{a._updating=D}}var Le=a._updates;if(0!==Le.length){let D=
Le.shift();if(D){let [P,Q]=D;wf(a,P,Q)}}}}function vf(a,b,c,...d){let e=b._updating;b._updating=c;try{let f=Array.from(b._listeners[a]);for(a=0;a<f.length;a++)f[a].apply(null,d)}finally{b._updating=e}}
function S(a,b,c){if(!1===a._updating||U!==a){let f=!1;a.update(()=>{f=S(a,b,c)});return f}let d=oc(a);for(let f=4;0<=f;f--)for(let g=0;g<d.length;g++){var e=d[g]._commands.get(b);if(void 0!==e&&(e=e[f],void 0!==e)){e=Array.from(e);let h=e.length;for(let k=0;k<h;k++)if(!0===e[k](c,a))return!0}}return!1}
function xf(a,b){let c=a._updates;for(b=b||!1;0!==c.length;){var d=c.shift();if(d){let [e,f]=d,g;void 0!==f&&(d=f.onUpdate,g=f.tag,f.skipTransforms&&(b=!0),d&&a._deferred.push(d),g&&a._updateTags.add(g));e()}}return b}
function wf(a,b,c){let d=a._updateTags;var e,f=e=!1;if(void 0!==c){var g=c.onUpdate;e=c.tag;null!=e&&d.add(e);e=c.skipTransforms||!1;f=c.discrete||!1}g&&a._deferred.push(g);c=a._editorState;g=a._pendingEditorState;let h=!1;if(null===g||g._readOnly)g=a._pendingEditorState=new yf(new Map((g||c)._nodeMap)),h=!0;g._flushSync=f;f=T;let k=V,m=U,q=a._updating;T=g;V=!1;a._updating=!0;U=a;try{h&&(a._headless?null!==c._selection&&(g._selection=c._selection.clone()):g._selection=hf(a));let n=a._compositionKey;
b();e=xf(a,e);kf(g,a);0!==a._dirtyType&&(e?pf(g,a):qf(g,a),xf(a),Mc(c,g,a._dirtyLeaves,a._dirtyElements));n!==a._compositionKey&&(g._flushSync=!0);let l=g._selection;if(C(l)){let r=g._nodeMap,w=l.focus.key;void 0!==r.get(l.anchor.key)&&void 0!==r.get(w)||p(19)}else $d(l)&&0===l._nodes.size&&(g._selection=null)}catch(n){n instanceof Error&&a._onError(n);a._pendingEditorState=c;a._dirtyType=2;a._cloneNotNeeded.clear();a._dirtyLeaves=new Set;a._dirtyElements.clear();tf(a);return}finally{T=f,V=k,U=m,
a._updating=q,dc=0}0!==a._dirtyType||zf(g,a)?g._flushSync?(g._flushSync=!1,tf(a)):h&&Pb(()=>{tf(a)}):(g._flushSync=!1,h&&(d.clear(),a._deferred=[],a._pendingEditorState=null))}function v(a,b,c){a._updating?a._updates.push([b,c]):wf(a,b,c)}class Af extends he{constructor(a){super(a)}decorate(){p(47)}isIsolated(){return!1}isInline(){return!0}isKeyboardSelectable(){return!0}}function x(a){return a instanceof Af}
class Bf extends he{constructor(a){super(a);this.__last=this.__first=null;this.__indent=this.__format=this.__size=0;this.__dir=null}getFormat(){return this.getLatest().__format}getFormatType(){let a=this.getFormat();return kb[a]||""}getIndent(){return this.getLatest().__indent}getChildren(){let a=[],b=this.getFirstChild();for(;null!==b;)a.push(b),b=b.getNextSibling();return a}getChildrenKeys(){let a=[],b=this.getFirstChild();for(;null!==b;)a.push(b.__key),b=b.getNextSibling();return a}getChildrenSize(){return this.getLatest().__size}isEmpty(){return 0===
this.getChildrenSize()}isDirty(){let a=F()._dirtyElements;return null!==a&&a.has(this.__key)}isLastChild(){let a=this.getLatest(),b=this.getParentOrThrow().getLastChild();return null!==b&&b.is(a)}getAllTextNodes(){let a=[],b=this.getFirstChild();for(;null!==b;){B(b)&&a.push(b);if(E(b)){let c=b.getAllTextNodes();a.push(...c)}b=b.getNextSibling()}return a}getFirstDescendant(){let a=this.getFirstChild();for(;E(a);){let b=a.getFirstChild();if(null===b)break;a=b}return a}getLastDescendant(){let a=this.getLastChild();
for(;E(a);){let b=a.getLastChild();if(null===b)break;a=b}return a}getDescendantByIndex(a){let b=this.getChildren(),c=b.length;if(a>=c)return a=b[c-1],E(a)&&a.getLastDescendant()||a||null;a=b[a];return E(a)&&a.getFirstDescendant()||a||null}getFirstChild(){let a=this.getLatest().__first;return null===a?null:I(a)}getFirstChildOrThrow(){let a=this.getFirstChild();null===a&&p(45,this.__key);return a}getLastChild(){let a=this.getLatest().__last;return null===a?null:I(a)}getLastChildOrThrow(){let a=this.getLastChild();
null===a&&p(96,this.__key);return a}getChildAtIndex(a){var b=this.getChildrenSize();let c;if(a<b/2){c=this.getFirstChild();for(b=0;null!==c&&b<=a;){if(b===a)return c;c=c.getNextSibling();b++}return null}c=this.getLastChild();for(--b;null!==c&&b>=a;){if(b===a)return c;c=c.getPreviousSibling();b--}return null}getTextContent(){let a="",b=this.getChildren(),c=b.length;for(let d=0;d<c;d++){let e=b[d];a+=e.getTextContent();E(e)&&d!==c-1&&!e.isInline()&&(a+="\n\n")}return a}getTextContentSize(){let a=0,
b=this.getChildren(),c=b.length;for(let d=0;d<c;d++){let e=b[d];a+=e.getTextContentSize();E(e)&&d!==c-1&&!e.isInline()&&(a+=2)}return a}getDirection(){return this.getLatest().__dir}hasFormat(a){return""!==a?(a=jb[a],0!==(this.getFormat()&a)):!1}select(a,b){G();let c=u(),d=a,e=b;var f=this.getChildrenSize();if(!this.canBeEmpty())if(0===a&&0===b){if(a=this.getFirstChild(),B(a)||E(a))return a.select(0,0)}else if(!(void 0!==a&&a!==f||void 0!==b&&b!==f)&&(a=this.getLastChild(),B(a)||E(a)))return a.select();
void 0===d&&(d=f);void 0===e&&(e=f);f=this.__key;if(C(c))c.anchor.set(f,d,"element"),c.focus.set(f,e,"element"),c.dirty=!0;else return ze(f,d,f,e,"element","element");return c}selectStart(){let a=this.getFirstDescendant();return a?a.selectStart():this.select()}selectEnd(){let a=this.getLastDescendant();return a?a.selectEnd():this.select()}clear(){let a=this.getWritable();this.getChildren().forEach(b=>b.remove());return a}append(...a){return this.splice(this.getChildrenSize(),0,a)}setDirection(a){let b=
this.getWritable();b.__dir=a;return b}setFormat(a){this.getWritable().__format=""!==a?jb[a]:0;return this}setIndent(a){this.getWritable().__indent=a;return this}splice(a,b,c){let d=c.length,e=this.getChildrenSize(),f=this.getWritable(),g=f.__key;var h=[],k=[];let m=this.getChildAtIndex(a+b),q=null,n=e-b+d;if(0!==a)if(a===e)q=this.getLastChild();else{var l=this.getChildAtIndex(a);null!==l&&(q=l.getPreviousSibling())}if(0<b){var r=null===q?this.getFirstChild():q.getNextSibling();for(l=0;l<b;l++){null===
r&&p(100);var w=r.getNextSibling(),A=r.__key;r=r.getWritable();fc(r);k.push(A);r=w}}l=q;for(w=0;w<d;w++){A=c[w];null!==l&&A.is(l)&&(q=l=l.getPreviousSibling());r=A.getWritable();r.__parent===g&&n--;fc(r);let y=A.__key;null===l?(f.__first=y,r.__prev=null):(l=l.getWritable(),l.__next=y,r.__prev=l.__key);A.__key===g&&p(76);r.__parent=g;h.push(y);l=A}a+b===e?null!==l&&(l.getWritable().__next=null,f.__last=l.__key):null!==m&&(a=m.getWritable(),null!==l?(b=l.getWritable(),a.__prev=l.__key,b.__next=m.__key):
a.__prev=null);f.__size=n;if(k.length&&(a=u(),C(a))){k=new Set(k);h=new Set(h);let {anchor:y,focus:z}=a;Cf(y,k,h)&&fe(y,y.getNode(),this,q,m);Cf(z,k,h)&&fe(z,z.getNode(),this,q,m);0!==n||this.canBeEmpty()||Bc(this)||this.remove()}return f}exportJSON(){return{children:[],direction:this.getDirection(),format:this.getFormatType(),indent:this.getIndent(),type:"element",version:1}}insertNewAfter(){return null}canIndent(){return!0}collapseAtStart(){return!1}excludeFromCopy(){return!1}canReplaceWith(){return!0}canInsertAfter(){return!0}canBeEmpty(){return!0}canInsertTextBefore(){return!0}canInsertTextAfter(){return!0}isInline(){return!1}isShadowRoot(){return!1}canMergeWith(){return!1}extractWithChild(){return!1}}
function E(a){return a instanceof Bf}function Cf(a,b,c){for(a=a.getNode();a;){let d=a.__key;if(b.has(d)&&!c.has(d))return!0;a=a.getParent()}return!1}
class Df extends Bf{static getType(){return"root"}static clone(){return new Df}constructor(){super("root");this.__cachedText=null}getTopLevelElementOrThrow(){p(51)}getTextContent(){let a=this.__cachedText;return!ic()&&0!==F()._dirtyType||null===a?super.getTextContent():a}remove(){p(52)}replace(){p(53)}insertBefore(){p(54)}insertAfter(){p(55)}updateDOM(){return!1}append(...a){for(let b=0;b<a.length;b++){let c=a[b];E(c)||x(c)||p(56)}return super.append(...a)}static importJSON(a){let b=J();b.setFormat(a.format);
b.setIndent(a.indent);b.setDirection(a.direction);return b}exportJSON(){return{children:[],direction:this.getDirection(),format:this.getFormatType(),indent:this.getIndent(),type:"root",version:1}}collapseAtStart(){return!0}}function L(a){return a instanceof Df}function zf(a,b){b=b.getEditorState()._selection;a=a._selection;if(null!==a){if(a.dirty||!a.is(b))return!0}else if(null!==b)return!0;return!1}function Ef(){return new yf(new Map([["root",new Df]]))}
function Kf(a){let b=a.exportJSON();var c=a.constructor;b.type!==c.getType()&&p(130,c.name);if(E(a)){let d=b.children;Array.isArray(d)||p(59,c.name);a=a.getChildren();for(c=0;c<a.length;c++){let e=Kf(a[c]);d.push(e)}}return b}
class yf{constructor(a,b){this._nodeMap=a;this._selection=b||null;this._readOnly=this._flushSync=!1}isEmpty(){return 1===this._nodeMap.size&&null===this._selection}read(a){return sf(this,a)}clone(a){a=new yf(this._nodeMap,void 0===a?this._selection:a);a._readOnly=!0;return a}toJSON(){return sf(this,()=>({root:Kf(J())}))}}
class Vd extends Bf{constructor(a){super(a);this.__textFormat=0}static getType(){return"paragraph"}getTextFormat(){return this.getLatest().__textFormat}setTextFormat(a){let b=this.getWritable();b.__textFormat=a;return b}hasTextFormat(a){a=hb[a];return 0!==(this.getTextFormat()&a)}static clone(a){return new Vd(a.__key)}createDOM(a){let b=document.createElement("p");a=tc(a.theme,"paragraph");void 0!==a&&b.classList.add(...a);return b}updateDOM(){return!1}static importDOM(){return{p:()=>({conversion:Lf,
priority:0})}}exportDOM(a){({element:a}=super.exportDOM(a));if(a&&Hc(a)){this.isEmpty()&&a.append(document.createElement("br"));var b=this.getFormatType();a.style.textAlign=b;if(b=this.getDirection())a.dir=b;b=this.getIndent();0<b&&(a.style.textIndent=`${20*b}px`)}return{element:a}}static importJSON(a){let b=je();b.setFormat(a.format);b.setIndent(a.indent);b.setDirection(a.direction);b.setTextFormat(a.textFormat);return b}exportJSON(){return{...super.exportJSON(),textFormat:this.getTextFormat(),type:"paragraph",
version:1}}insertNewAfter(a,b){let c=je();c.setTextFormat(a.format);a=this.getDirection();c.setDirection(a);c.setFormat(this.getFormatType());this.insertAfter(c,b);return c}collapseAtStart(){let a=this.getChildren();if(0===a.length||B(a[0])&&""===a[0].getTextContent().trim()){if(null!==this.getNextSibling())return this.selectNext(),this.remove(),!0;if(null!==this.getPreviousSibling())return this.selectPrevious(),this.remove(),!0}return!1}}
function Lf(a){let b=je();a.style&&(b.setFormat(a.style.textAlign),a=parseInt(a.style.textIndent,10)/20,0<a&&b.setIndent(a));return{node:b}}function je(){return Dc(new Vd)}function yd(a){return a instanceof Vd}
function uf(a,b,c,d){let e=a._keyToDOMMap;e.clear();a._editorState=Ef();a._pendingEditorState=d;a._compositionKey=null;a._dirtyType=0;a._cloneNotNeeded.clear();a._dirtyLeaves=new Set;a._dirtyElements.clear();a._normalizedNodes=new Set;a._updateTags=new Set;a._updates=[];a._blockCursorElement=null;d=a._observer;null!==d&&(d.disconnect(),a._observer=null);null!==b&&(b.textContent="");null!==c&&(c.textContent="",e.set("root",c))}
function Mf(a,b){let c=new Map,d=new Set,e=f=>{Object.keys(f).forEach(g=>{let h=c.get(g);void 0===h&&(h=[],c.set(g,h));h.push(f[g])})};a.forEach(f=>{let g=f.klass.importDOM;null==g||d.has(g)||(d.add(g),f=g.call(f.klass),null!==f&&e(f))});b&&e(b);return c}
class Nf{constructor(a,b,c,d,e,f,g){this._parentEditor=b;this._rootElement=null;this._editorState=a;this._compositionKey=this._pendingEditorState=null;this._deferred=[];this._keyToDOMMap=new Map;this._updates=[];this._updating=!1;this._listeners={decorator:new Set,editable:new Set,mutation:new Map,root:new Set,textcontent:new Set,update:new Set};this._commands=new Map;this._config=d;this._nodes=c;this._decorators={};this._pendingDecorators=null;this._dirtyType=0;this._cloneNotNeeded=new Set;this._dirtyLeaves=
new Set;this._dirtyElements=new Map;this._normalizedNodes=new Set;this._updateTags=new Set;this._observer=null;this._key=pc();this._onError=e;this._htmlConversions=f;this._editable=g;this._headless=null!==b&&b._headless;this._blockCursorElement=this._window=null}isComposing(){return null!=this._compositionKey}registerUpdateListener(a){let b=this._listeners.update;b.add(a);return()=>{b.delete(a)}}registerEditableListener(a){let b=this._listeners.editable;b.add(a);return()=>{b.delete(a)}}registerDecoratorListener(a){let b=
this._listeners.decorator;b.add(a);return()=>{b.delete(a)}}registerTextContentListener(a){let b=this._listeners.textcontent;b.add(a);return()=>{b.delete(a)}}registerRootListener(a){let b=this._listeners.root;a(this._rootElement,null);b.add(a);return()=>{a(null,this._rootElement);b.delete(a)}}registerCommand(a,b,c){void 0===c&&p(35);let d=this._commands;d.has(a)||d.set(a,[new Set,new Set,new Set,new Set,new Set]);let e=d.get(a);void 0===e&&p(36,String(a));let f=e[c];f.add(b);return()=>{f.delete(b);
e.every(g=>0===g.size)&&d.delete(a)}}registerMutationListener(a,b){void 0===this._nodes.get(a.getType())&&p(37,a.name);let c=this._listeners.mutation;c.set(b,a);return()=>{c.delete(b)}}registerNodeTransformToKlass(a,b){var c=a.getType();c=this._nodes.get(c);void 0===c&&p(37,a.name);c.transforms.add(b);return c}registerNodeTransform(a,b){var c=this.registerNodeTransformToKlass(a,b);let d=[c];c=c.replaceWithKlass;null!=c&&(c=this.registerNodeTransformToKlass(c,b),d.push(c));lc(this,a.getType());return()=>
{d.forEach(e=>e.transforms.delete(b))}}hasNode(a){return this._nodes.has(a.getType())}hasNodes(a){return a.every(this.hasNode.bind(this))}dispatchCommand(a,b){return S(this,a,b)}getDecorators(){return this._decorators}getRootElement(){return this._rootElement}getKey(){return this._key}setRootElement(a){let b=this._rootElement;if(a!==b){let f=tc(this._config.theme,"root");var c=this._pendingEditorState||this._editorState;this._rootElement=a;uf(this,b,a,c);if(null!==b){if(!this._config.disableEvents){var d=
b.ownerDocument,e=Md.get(d);if(void 0===e)throw Error("Root element not registered");Md.set(d,e-1);0===Md.get(d)&&d.removeEventListener("selectionchange",ce);d=b.__lexicalEditor;null!==d&&void 0!==d&&(null!==d._parentEditor?(e=oc(d),e=e[e.length-1]._key,be.get(e)===d&&be.delete(e)):be.delete(d._key),b.__lexicalEditor=null);d=ae(b);for(e=0;e<d.length;e++)d[e]();b.__lexicalEventHandles=[]}null!=f&&b.classList.remove(...f)}null!==a?(c=(c=a.ownerDocument)&&c.defaultView||null,d=a.style,d.userSelect="text",
d.whiteSpace="pre-wrap",d.wordBreak="break-word",a.setAttribute("data-lexical-editor","true"),this._window=c,this._dirtyType=2,Eb(this),this._updateTags.add("history-merge"),tf(this),this._config.disableEvents||de(a,this),null!=f&&a.classList.add(...f)):(this._editorState=c,this._window=this._pendingEditorState=null);vf("root",this,!1,a,b)}}getElementByKey(a){return this._keyToDOMMap.get(a)||null}getEditorState(){return this._editorState}setEditorState(a,b){a.isEmpty()&&p(38);Db(this);let c=this._pendingEditorState,
d=this._updateTags;b=void 0!==b?b.tag:null;null===c||c.isEmpty()||(null!=b&&d.add(b),tf(this));this._pendingEditorState=a;this._dirtyType=2;this._dirtyElements.set("root",!1);this._compositionKey=null;null!=b&&d.add(b);tf(this)}parseEditorState(a,b){a="string"===typeof a?JSON.parse(a):a;let c=Ef(),d=T,e=V,f=U,g=this._dirtyElements,h=this._dirtyLeaves,k=this._cloneNotNeeded,m=this._dirtyType;this._dirtyElements=new Map;this._dirtyLeaves=new Set;this._cloneNotNeeded=new Set;this._dirtyType=0;T=c;V=
!1;U=this;try{rf(a.root,this._nodes),b&&b(),c._readOnly=!0}catch(q){q instanceof Error&&this._onError(q)}finally{this._dirtyElements=g,this._dirtyLeaves=h,this._cloneNotNeeded=k,this._dirtyType=m,T=d,V=e,U=f}return c}update(a,b){v(this,a,b)}focus(a,b={}){let c=this._rootElement;null!==c&&(c.setAttribute("autocapitalize","off"),v(this,()=>{let d=u(),e=J();null!==d?d.dirty=!0:0!==e.getChildrenSize()&&("rootStart"===b.defaultSelection?e.selectStart():e.selectEnd())},{onUpdate:()=>{c.removeAttribute("autocapitalize");
a&&a()},tag:"focus"}),null===this._pendingEditorState&&c.removeAttribute("autocapitalize"))}blur(){var a=this._rootElement;null!==a&&a.blur();a=yb(this._window);null!==a&&a.removeAllRanges()}isEditable(){return this._editable}setEditable(a){this._editable!==a&&(this._editable=a,vf("editable",this,!0,a))}toJSON(){return{editorState:this._editorState.toJSON()}}}exports.$addUpdateTag=function(a){G();F()._updateTags.add(a)};exports.$applyNodeReplacement=Dc;exports.$copyNode=Cc;
exports.$createLineBreakNode=oe;exports.$createNodeSelection=cf;exports.$createParagraphNode=je;exports.$createPoint=Se;exports.$createRangeSelection=function(){let a=Se("root",0,"element"),b=Se("root",0,"element");return new Xe(a,b,0,"")};exports.$createRangeSelectionFromDom=function(a,b){return Wd(null,a,b,null)};exports.$createTabNode=Ce;exports.$createTextNode=K;exports.$getAdjacentNode=wc;exports.$getCharacterOffsets=Ye;exports.$getEditor=function(){return F()};
exports.$getNearestNodeFromDOMNode=xb;exports.$getNearestRootOrShadowRoot=Ac;exports.$getNodeByKey=I;exports.$getPreviousSelection=rc;exports.$getRoot=J;exports.$getSelection=u;exports.$getTextContent=function(){let a=u();return null===a?"":a.getTextContent()};exports.$hasAncestor=zc;exports.$hasUpdateTag=function(a){return F()._updateTags.has(a)};exports.$insertNodes=function(a){let b=u()||rc();null===b&&(b=J().selectEnd());b.insertNodes(a)};exports.$isBlockElementNode=function(a){return E(a)&&!a.isInline()};
exports.$isDecoratorNode=x;exports.$isElementNode=E;exports.$isInlineElementOrDecoratorNode=function(a){return E(a)&&a.isInline()||x(a)&&a.isInline()};exports.$isLeafNode=function(a){return B(a)||Jc(a)||x(a)};exports.$isLineBreakNode=Jc;exports.$isMergeableNode=Nb;exports.$isNodeSelection=$d;exports.$isParagraphNode=yd;exports.$isRangeSelection=C;exports.$isRootNode=L;exports.$isRootOrShadowRoot=Bc;exports.$isTabNode=Qe;exports.$isTextNode=B;
exports.$nodesOfType=function(a){var b=ec();let c=b._readOnly,d=a.getType();b=b._nodeMap;let e=[];for(let [,f]of b)f instanceof a&&f.__type===d&&(c||f.isAttached())&&e.push(f);return e};exports.$normalizeSelection__EXPERIMENTAL=Kb;exports.$parseSerializedNode=function(a){return rf(a,F()._nodes)};exports.$selectAll=function(){var a=J();a=a.select(0,a.getChildrenSize());Bb(Kb(a))};exports.$setCompositionKey=H;exports.$setSelection=Bb;
exports.$splitNode=function(a,b){let c=a.getChildAtIndex(b);null==c&&(c=a);Bc(a)&&p(102);let d=g=>{const h=g.getParentOrThrow(),k=Bc(h),m=g!==c||k?Cc(g):g;if(k)return E(g)&&E(m)||p(133),g.insertAfter(m),[g,m,m];const [q,n,l]=d(h);g=g.getNextSiblings();l.append(m,...g);return[q,n,m]},[e,f]=d(c);return[e,f]};exports.BLUR_COMMAND=Ra;exports.CAN_REDO_COMMAND={};exports.CAN_UNDO_COMMAND={};exports.CLEAR_EDITOR_COMMAND={};exports.CLEAR_HISTORY_COMMAND={};exports.CLICK_COMMAND=ca;
exports.COMMAND_PRIORITY_CRITICAL=4;exports.COMMAND_PRIORITY_EDITOR=0;exports.COMMAND_PRIORITY_HIGH=3;exports.COMMAND_PRIORITY_LOW=1;exports.COMMAND_PRIORITY_NORMAL=2;exports.CONTROLLED_TEXT_INSERTION_COMMAND=ha;exports.COPY_COMMAND=Na;exports.CUT_COMMAND=Oa;exports.DELETE_CHARACTER_COMMAND=da;exports.DELETE_LINE_COMMAND=oa;exports.DELETE_WORD_COMMAND=na;exports.DRAGEND_COMMAND=Ma;exports.DRAGOVER_COMMAND=La;exports.DRAGSTART_COMMAND=Ka;exports.DROP_COMMAND=Ja;exports.DecoratorNode=Af;
exports.ElementNode=Bf;exports.FOCUS_COMMAND=Qa;exports.FORMAT_ELEMENT_COMMAND={};exports.FORMAT_TEXT_COMMAND=pa;exports.INDENT_CONTENT_COMMAND={};exports.INSERT_LINE_BREAK_COMMAND=ea;exports.INSERT_PARAGRAPH_COMMAND=fa;exports.INSERT_TAB_COMMAND={};exports.KEY_ARROW_DOWN_COMMAND=Aa;exports.KEY_ARROW_LEFT_COMMAND=wa;exports.KEY_ARROW_RIGHT_COMMAND=ua;exports.KEY_ARROW_UP_COMMAND=za;exports.KEY_BACKSPACE_COMMAND=Da;exports.KEY_DELETE_COMMAND=Ha;exports.KEY_DOWN_COMMAND=ta;
exports.KEY_ENTER_COMMAND=Ba;exports.KEY_ESCAPE_COMMAND=Ea;exports.KEY_MODIFIER_COMMAND=Sa;exports.KEY_SPACE_COMMAND=Ca;exports.KEY_TAB_COMMAND=Ia;exports.LineBreakNode=le;exports.MOVE_TO_END=va;exports.MOVE_TO_START=xa;exports.OUTDENT_CONTENT_COMMAND={};exports.PASTE_COMMAND=ia;exports.ParagraphNode=Vd;exports.REDO_COMMAND=sa;exports.REMOVE_TEXT_COMMAND=la;exports.RootNode=Df;exports.SELECTION_CHANGE_COMMAND=ba;exports.SELECTION_INSERT_CLIPBOARD_NODES_COMMAND={};exports.SELECT_ALL_COMMAND=Pa;
exports.TabNode=Pe;exports.TextNode=ue;exports.UNDO_COMMAND=qa;exports.createCommand=function(){return{}};
exports.createEditor=function(a){var b=a||{},c=U;let d=b.theme||{},e=void 0===a?c:b.parentEditor||null,f=b.disableEvents||!1,g=Ef(),h=b.namespace||(null!==e?e._config.namespace:pc()),k=b.editorState,m=[Df,ue,le,Pe,Vd,...(b.nodes||[])],{onError:q,html:n}=b,l=void 0!==b.editable?b.editable:!0;if(void 0===a&&null!==c)a=c._nodes;else for(a=new Map,c=0;c<m.length;c++){let w=m[c],A=null;var r=null;"function"!==typeof w&&(r=w,w=r.replace,A=r.with,r=r.withKlass||null);let y=w.getType(),z=w.transform(),R=
new Set;null!==z&&R.add(z);a.set(y,{exportDOM:n&&n.export?n.export.get(w):void 0,klass:w,replace:A,replaceWithKlass:r,transforms:R})}b=new Nf(g,e,a,{customGetAdjacentNode:b.customGetAdjacentNode,disableEvents:f,namespace:h,theme:d},q?q:console.error,Mf(a,n?n.import:void 0),l);void 0!==k&&(b._pendingEditorState=k,b._dirtyType=2);return b};exports.getNearestEditorFromDOMNode=Yb;exports.isCurrentlyReadOnlyMode=ic;exports.isHTMLAnchorElement=function(a){return Hc(a)&&"A"===a.tagName};
exports.isHTMLElement=Hc;exports.isSelectionCapturedInDecoratorInput=Wb;exports.isSelectionWithinEditor=Xb
