/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

'use strict';let ba={},ca={},da={},ea={},fa={},ha={},ia={},la={},na={},oa={},pa={},qa={},sa={},ta={},ua={},va={},wa={},xa={},za={},Aa={},Ba={},Ca={},Da={},Ea={},Ha={},Ia={},Ja={},Ka={},La={},Ma={},Na={},Oa={},Pa={},Qa={},Ra={},Sa={};var n;
function Ta(a){let b=new URLSearchParams;b.append("code",a);for(let c=1;c<arguments.length;c++)b.append("v",arguments[c]);throw Error(`Minified Lexical error #${a}; visit https://lexical.dev/docs/error?${b} for the full message or `+"use the non-minified dev environment for full errors and additional helpful warnings.");}n=Ta&&Ta.__esModule&&Object.prototype.hasOwnProperty.call(Ta,"default")?Ta["default"]:Ta;
let Ua="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement,Va=Ua&&"documentMode"in document?document.documentMode:null,t=Ua&&/Mac|iPod|iPhone|iPad/.test(navigator.platform),Wa=Ua&&/^(?!.*Seamonkey)(?=.*Firefox).*/i.test(navigator.userAgent),Ya=Ua&&"InputEvent"in window&&!Va?"getTargetRanges"in new window.InputEvent("input"):!1,Za=Ua&&/Version\/[\d.]+.*Safari/.test(navigator.userAgent),$a=Ua&&/iPad|iPhone|iPod/.test(navigator.userAgent)&&
!window.MSStream,ab=Ua&&/Android/.test(navigator.userAgent),bb=Ua&&/^(?=.*Chrome).*/i.test(navigator.userAgent),cb=Ua&&ab&&bb,db=Ua&&/AppleWebKit\/[\d.]+/.test(navigator.userAgent)&&!bb,eb=Za||$a||db?"\u00a0":"\u200b",fb=Wa?"\u00a0":eb,gb=/^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\ufb1d-\ufdfd\ufe70-\ufefc]/,hb=/^[^\u0591-\u07ff\ufb1d-\ufdfd\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]/,
ib={bold:1,code:16,highlight:128,italic:2,strikethrough:4,subscript:32,superscript:64,underline:8},jb={directionless:1,unmergeable:2},kb={center:2,end:6,justify:4,left:1,right:3,start:5},lb={2:"center",6:"end",4:"justify",1:"left",3:"right",5:"start"},pb={normal:0,segmented:2,token:1},qb={0:"normal",2:"segmented",1:"token"};function rb(...a){let b=[];for(let c of a)if(c&&"string"===typeof c)for(let [d]of c.matchAll(/\S+/g))b.push(d);return b}let sb=!1,tb=0;
function ub(a){tb=a.timeStamp}function vb(a,b,c){return b.__lexicalLineBreak===a||void 0!==a[`__lexicalKey_${c._key}`]}function wb(a){return a.getEditorState().read(()=>{let b=u();return null!==b?b.clone():null})}
function xb(a,b,c){sb=!0;let d=100<performance.now()-tb;try{v(a,()=>{let e=u()||wb(a);var f=new Map,g=a.getRootElement(),h=a._editorState,k=a._blockCursorElement;let m=!1,p="";for(var q=0;q<b.length;q++){var l=b[q],r=l.type,w=l.target,A=yb(w,h);if(!(null===A&&w!==g||x(A)))if("characterData"===r){if(l=d&&B(A))a:{l=e;r=w;var y=A;if(C(l)){var z=l.anchor.getNode();if(z.is(y)&&l.format!==z.getFormat()){l=!1;break a}}l=3===r.nodeType&&y.isAttached()}l&&(y=zb(a._window),r=l=null,null!==y&&y.anchorNode===
w&&(l=y.anchorOffset,r=y.focusOffset),w=w.nodeValue,null!==w&&Ab(A,w,l,r,!1))}else if("childList"===r){m=!0;r=l.addedNodes;for(y=0;y<r.length;y++){z=r[y];var R=Bb(z),X=z.parentNode;null==X||z===k||null!==R||"BR"===z.nodeName&&vb(z,X,a)||(Wa&&(R=z.innerText||z.nodeValue)&&(p+=R),X.removeChild(z))}l=l.removedNodes;r=l.length;if(0<r){y=0;for(z=0;z<r;z++)if(X=l[z],"BR"===X.nodeName&&vb(X,w,a)||k===X)w.appendChild(X),y++;r!==y&&(w===g&&(A=h._nodeMap.get("root")),f.set(w,A))}}}if(0<f.size)for(let [Xa,ma]of f)if(E(ma))for(f=
ma.getChildrenKeys(),g=Xa.firstChild,h=0;h<f.length;h++)k=a.getElementByKey(f[h]),null!==k&&(null==g?(Xa.appendChild(k),g=k):g!==k&&Xa.replaceChild(k,g),g=g.nextSibling);else B(ma)&&ma.markDirty();f=c.takeRecords();if(0<f.length){for(g=0;g<f.length;g++)for(k=f[g],h=k.addedNodes,k=k.target,q=0;q<h.length;q++)A=h[q],w=A.parentNode,null==w||"BR"!==A.nodeName||vb(A,k,a)||w.removeChild(A);c.takeRecords()}null!==e&&(m&&(e.dirty=!0,Cb(e)),Wa&&Db(a)&&e.insertRawText(p))})}finally{sb=!1}}
function Eb(a){let b=a._observer;if(null!==b){let c=b.takeRecords();xb(a,c,b)}}function Fb(a){0===tb&&Gb(a).addEventListener("textInput",ub,!0);a._observer=new MutationObserver((b,c)=>{xb(a,b,c)})}function Hb(a,b){let c=a.__mode,d=a.__format;a=a.__style;let e=b.__mode,f=b.__format;b=b.__style;return(null===c||c===e)&&(null===d||d===f)&&(null===a||a===b)}function Ib(a,b){let c=a.mergeWithSibling(b),d=F()._normalizedNodes;d.add(a.__key);d.add(b.__key);return c}
function Jb(a,b){let c=a.mergeWithSibling(b),d=F()._normalizedNodes;d.add(a.__key);d.add(b.__key);return c}function Kb(a){if(""===a.__text&&a.isSimpleText()&&!a.isUnmergeable())a.remove();else{for(var b;null!==(b=a.getPreviousSibling())&&B(b)&&b.isSimpleText()&&!b.isUnmergeable();)if(""===b.__text)b.remove();else{Hb(b,a)&&(a=Ib(b,a));break}for(var c;null!==(c=a.getNextSibling())&&B(c)&&c.isSimpleText()&&!c.isUnmergeable();)if(""===c.__text)c.remove();else{Hb(a,c)&&Ib(a,c);break}}}
function Lb(a){Mb(a.anchor);Mb(a.focus);return a}function Nb(a){let b;null!==(b=a.getPreviousSibling())&&Ob(b)&&b.__type===a.__type&&(a=Jb(b,a));let c;null!==(c=a.getNextSibling())&&Ob(c)&&c.__type===a.__type&&Jb(a,c)}
function Mb(a){for(;"element"===a.type;){var b=a.getNode(),c=a.offset;c===b.getChildrenSize()?(b=b.getChildAtIndex(c-1),c=!0):(b=b.getChildAtIndex(c),c=!1);if(B(b)){a.set(b.__key,c?b.getTextContentSize():0,"text");break}else if(!E(b))break;a.set(b.__key,c?b.getChildrenSize():0,"element")}}let Pb=1,Qb="function"===typeof queueMicrotask?queueMicrotask:a=>{Promise.resolve().then(a)};
function Rb(a){let b=document.activeElement;if(null===b)return!1;let c=b.nodeName;return x(yb(a))&&("INPUT"===c||"TEXTAREA"===c||"true"===b.contentEditable&&null==b.__lexicalEditor)}function Sb(a,b,c){let d=a.getRootElement();try{return null!==d&&d.contains(b)&&d.contains(c)&&null!==b&&!Rb(b)&&Zb(b)===a}catch(e){return!1}}function Zb(a){for(;null!=a;){let b=a.__lexicalEditor;if(null!=b)return b;a=$b(a)}return null}function ac(a){return a.isToken()||a.isSegmented()}
function bc(a){for(;null!=a;){if(3===a.nodeType)return a;a=a.firstChild}return null}function cc(a,b,c){let d=ib[b];if(null!==c&&(a&d)===(c&d))return a;a^=d;"subscript"===b?a&=~ib.superscript:"superscript"===b&&(a&=~ib.subscript);return a}function dc(a,b){if(null!=b)a.__key=b;else{G();99<ec&&n(14);b=F();var c=fc(),d=""+Pb++;c._nodeMap.set(d,a);E(a)?b._dirtyElements.set(d,!0):b._dirtyLeaves.add(d);b._cloneNotNeeded.add(d);b._dirtyType=1;a.__key=d}}
function gc(a){var b=a.getParent();if(null!==b){let e=a.getWritable();b=b.getWritable();var c=a.getPreviousSibling();a=a.getNextSibling();if(null===c)if(null!==a){var d=a.getWritable();b.__first=a.__key;d.__prev=null}else b.__first=null;else{d=c.getWritable();if(null!==a){let f=a.getWritable();f.__prev=d.__key;d.__next=f.__key}else d.__next=null;e.__prev=null}null===a?null!==c?(a=c.getWritable(),b.__last=c.__key,a.__next=null):b.__last=null:(a=a.getWritable(),null!==c?(c=c.getWritable(),c.__next=
a.__key,a.__prev=c.__key):a.__prev=null,e.__next=null);b.__size--;e.__parent=null}}function hc(a){99<ec&&n(14);var b=a.getLatest(),c=b.__parent,d=fc();let e=F(),f=d._nodeMap;d=e._dirtyElements;if(null!==c)a:for(;null!==c;){if(d.has(c))break a;let g=f.get(c);if(void 0===g)break;d.set(c,!1);c=g.__parent}b=b.__key;e._dirtyType=1;E(a)?d.set(b,!0):e._dirtyLeaves.add(b)}
function H(a){G();var b=F();let c=b._compositionKey;a!==c&&(b._compositionKey=a,null!==c&&(b=I(c),null!==b&&b.getWritable()),null!==a&&(a=I(a),null!==a&&a.getWritable()))}function ic(){return jc()?null:F()._compositionKey}function I(a,b){a=(b||fc())._nodeMap.get(a);return void 0===a?null:a}function Bb(a,b){let c=F();a=a[`__lexicalKey_${c._key}`];return void 0!==a?I(a,b):null}function yb(a,b){for(;null!=a;){let c=Bb(a,b);if(null!==c)return c;a=$b(a)}return null}
function kc(a){let b=Object.assign({},a._decorators);return a._pendingDecorators=b}function lc(a){return a.read(()=>J().getTextContent())}function mc(a,b){v(a,()=>{var c=fc();if(!c.isEmpty())if("root"===b)J().markDirty();else{c=c._nodeMap;for(let [,d]of c)d.markDirty()}},null===a._pendingEditorState?{tag:"history-merge"}:void 0)}function J(){return fc()._nodeMap.get("root")}function Cb(a){G();let b=fc();null!==a&&(a.dirty=!0,a.setCachedNodes(null));b._selection=a}
function nc(a){var b=F(),c;a:{for(c=a;null!=c;){let d=c[`__lexicalKey_${b._key}`];if(void 0!==d){c=d;break a}c=$b(c)}c=null}return null===c?(b=b.getRootElement(),a===b?I("root"):null):I(c)}function oc(a){return/[\uD800-\uDBFF][\uDC00-\uDFFF]/g.test(a)}function pc(a){let b=[];for(;null!==a;)b.push(a),a=a._parentEditor;return b}function qc(){return Math.random().toString(36).replace(/[^a-z]+/g,"").substr(0,5)}
function rc(a,b,c){b=zb(b._window);if(null!==b){var d=b.anchorNode,{anchorOffset:e,focusOffset:f}=b;if(null!==d&&(b=3===d.nodeType?d.nodeValue:null,d=yb(d),null!==b&&B(d))){if(b===eb&&c){let g=c.length;b=c;f=e=g}null!==b&&Ab(d,b,e,f,a)}}}
function Ab(a,b,c,d,e){let f=a;if(f.isAttached()&&(e||!f.isDirty())){let m=f.isComposing(),p=b;(m||e)&&b[b.length-1]===eb&&(p=b.slice(0,-1));b=f.getTextContent();if(e||p!==b)if(""===p)if(H(null),Za||$a||db)f.remove();else{let q=F();setTimeout(()=>{q.update(()=>{f.isAttached()&&f.remove()})},20)}else{e=f.getParent();b=sc();var g=f.getTextContentSize(),h=ic(),k=f.getKey();f.isToken()||null!==h&&k===h&&!m||C(b)&&(null!==e&&!e.canInsertTextBefore()&&0===b.anchor.offset||b.anchor.key===a.__key&&0===b.anchor.offset&&
!f.canInsertTextBefore()&&!m||b.focus.key===a.__key&&b.focus.offset===g&&!f.canInsertTextAfter()&&!m)?f.markDirty():(a=u(),C(a)&&null!==c&&null!==d&&(a.setTextNodeRange(f,c,f,d),f.isSegmented()&&(c=f.getTextContent(),c=K(c),f.replace(c),f=c)),f.setTextContent(p))}}}
function tc(a,b){if(b.isSegmented())return!0;if(!a.isCollapsed())return!1;a=a.anchor.offset;let c=b.getParentOrThrow(),d=b.isToken();return 0===a?((a=!b.canInsertTextBefore()||!c.canInsertTextBefore()&&!b.isComposing()||d)||(b=b.getPreviousSibling(),a=(B(b)||E(b)&&b.isInline())&&!b.canInsertTextAfter()),a):a===b.getTextContentSize()?!b.canInsertTextAfter()||!c.canInsertTextAfter()&&!b.isComposing()||d:!1}function uc(a){return"Backspace"===a}
function vc(a,b){void 0===a.__lexicalClassNameCache&&(a.__lexicalClassNameCache={});let c=a.__lexicalClassNameCache,d=c[b];if(void 0!==d)return d;a=a[b];return"string"===typeof a?(a=rb(a),c[b]=a):a}function wc(a,b,c,d,e){0!==c.size&&(c=d.__type,d=d.__key,b=b.get(c),void 0===b&&n(33,c),c=b.klass,b=a.get(c),void 0===b&&(b=new Map,a.set(c,b)),a=b.get(d),c="destroyed"===a&&"created"===e,(void 0===a||c)&&b.set(d,c?"updated":e))}
function xc(a,b,c){let d=a.getParent(),e=c;null!==d&&(b&&0===c?(e=a.getIndexWithinParent(),a=d):b||c!==a.getChildrenSize()||(e=a.getIndexWithinParent()+1,a=d));return a.getChildAtIndex(b?e-1:e)}
function yc(a,b){var c=F()._config.customGetAdjacentNode;if(c&&(c=c(a,b)))return c;c=a.offset;if("element"===a.type)return a=a.getNode(),xc(a,b,c);a=a.getNode();return b&&0===c||!b&&c===a.getTextContentSize()?(c=b?a.getPreviousSibling():a.getNextSibling(),null===c?xc(a.getParentOrThrow(),b,a.getIndexWithinParent()+(b?0:1)):c):null}function Db(a){a=(a=Gb(a).event)&&a.inputType;return"insertFromPaste"===a||"insertFromPasteAsQuotation"===a}
function zc(a){return!L(a)&&!a.isLastChild()&&!a.isInline()}function Ac(a,b){a=a._keyToDOMMap.get(b);void 0===a&&n(75,b);return a}function $b(a){a=a.assignedSlot||a.parentElement;return null!==a&&11===a.nodeType?a.host:a}function Bc(a,b){for(a=a.getParent();null!==a;){if(a.is(b))return!0;a=a.getParent()}return!1}function Gb(a){a=a._window;null===a&&n(78);return a}function Cc(a){for(a=a.getParentOrThrow();null!==a&&!Dc(a);)a=a.getParentOrThrow();return a}
function Dc(a){return L(a)||E(a)&&a.isShadowRoot()}function Ec(a){a=a.constructor.clone(a);dc(a,null);return a}function Fc(a){var b=F();let c=a.constructor.getType();b=b._nodes.get(c);void 0===b&&n(97);b=b.replace;return null!==b?(b=b(a),b instanceof a.constructor||n(98),b):a}function Gc(a,b){a=a.getParent();!L(a)||E(b)||x(b)||n(99)}function Hc(a){return(x(a)||E(a)&&!a.canBeEmpty())&&!a.isInline()}
function Ic(a,b,c){c.style.removeProperty("caret-color");b._blockCursorElement=null;b=a.parentElement;null!==b&&b.removeChild(a)}function zb(a){return Ua?(a||window).getSelection():null}function Jc(a){return 1===a.nodeType}function Kc(a){return null!==a.nodeName.match(new RegExp(/^(a|abbr|acronym|b|cite|code|del|em|i|ins|kbd|label|output|q|ruby|s|samp|span|strong|sub|sup|time|u|tt|var|#text)$/,"i"))}
function Lc(a){if(L(a)||x(a)&&!a.isInline())return!0;if(!E(a)||Dc(a))return!1;var b=a.getFirstChild();b=null===b||Mc(b)||B(b)||b.isInline();return!a.isInline()&&!1!==a.canBeEmpty()&&b}function Nc(a,b){for(;null!==a&&null!==a.getParent()&&!b(a);)a=a.getParentOrThrow();return b(a)?a:null}function Oc(a,b,c,d,e,f){for(a=a.getFirstChild();null!==a;){let g=a.__key;a.__parent===b&&(E(a)&&Oc(a,g,c,d,e,f),c.has(g)||f.delete(g),e.push(g));a=a.getNextSibling()}}
function Pc(a,b,c,d){a=a._nodeMap;b=b._nodeMap;let e=[];for(let [f]of d){let g=b.get(f);void 0===g||g.isAttached()||(E(g)&&Oc(g,f,a,b,e,d),a.has(f)||d.delete(f),e.push(f))}for(let f of e)b.delete(f);for(let f of c)d=b.get(f),void 0===d||d.isAttached()||(a.has(f)||c.delete(f),b.delete(f))}let M="",N="",Qc=null,Rc="",Sc,O,Tc,Uc=!1,Vc=!1,ed,fd=null,gd,hd,id,jd,kd,ld;
function md(a,b){let c=id.get(a);if(null!==b){let d=nd(a);d.parentNode===b&&b.removeChild(d)}jd.has(a)||O._keyToDOMMap.delete(a);E(c)&&(a=od(c,id),pd(a,0,a.length-1,null));void 0!==c&&wc(ld,Tc,ed,c,"destroyed")}function pd(a,b,c,d){for(;b<=c;++b){let e=a[b];void 0!==e&&md(e,d)}}function qd(a,b){a.setProperty("text-align",b)}
function rd(a,b){var c=Sc.theme.indent;if("string"===typeof c){let d=a.classList.contains(c);0<b&&!d?a.classList.add(c):1>b&&d&&a.classList.remove(c)}c=getComputedStyle(a).getPropertyValue("--lexical-indent-base-value")||"40px";a.style.setProperty("padding-inline-start",0===b?"":`calc(${b} * ${c})`)}function sd(a,b){a=a.style;0===b?qd(a,""):1===b?qd(a,"left"):2===b?qd(a,"center"):3===b?qd(a,"right"):4===b?qd(a,"justify"):5===b?qd(a,"start"):6===b&&qd(a,"end")}
function td(a,b,c){let d=jd.get(a);void 0===d&&n(60);let e=d.createDOM(Sc,O);var f=O._keyToDOMMap;e["__lexicalKey_"+O._key]=a;f.set(a,e);B(d)?e.setAttribute("data-lexical-text","true"):x(d)&&e.setAttribute("data-lexical-decorator","true");if(E(d)){a=d.__indent;f=d.__size;0!==a&&rd(e,a);if(0!==f){--f;a=od(d,jd);var g=N;N="";ud(a,d,0,f,e,null);vd(d,e);N=g}a=d.__format;0!==a&&sd(e,a);d.isInline()||wd(null,d,e);zc(d)&&(M+="\n\n",Rc+="\n\n")}else f=d.getTextContent(),x(d)?(g=d.decorate(O,Sc),null!==g&&
xd(a,g),e.contentEditable="false"):B(d)&&(d.isDirectionless()||(N+=f)),M+=f,Rc+=f;null!==b&&(null!=c?b.insertBefore(e,c):(c=b.__lexicalLineBreak,null!=c?b.insertBefore(e,c):b.appendChild(e)));wc(ld,Tc,ed,d,"created");return e}function ud(a,b,c,d,e,f){let g=M;for(M="";c<=d;++c){td(a[c],e,f);let h=jd.get(a[c]);null!==h&&null===Qc&&B(h)&&(Qc=h.getFormat())}zc(b)&&(M+="\n\n");e.__lexicalTextContent=M;M=g+M}function yd(a,b){a=b.get(a);return Mc(a)||x(a)&&a.isInline()}
function wd(a,b,c){a=null!==a&&(0===a.__size||yd(a.__last,id));b=0===b.__size||yd(b.__last,jd);a?b||(b=c.__lexicalLineBreak,null!=b&&c.removeChild(b),c.__lexicalLineBreak=null):b&&(b=document.createElement("br"),c.__lexicalLineBreak=b,c.appendChild(b))}
function vd(a,b){var c=b.__lexicalDir;if(b.__lexicalDirTextContent!==N||c!==fd){let f=""===N;if(f)var d=fd;else d=N,d=gb.test(d)?"rtl":hb.test(d)?"ltr":null;if(d!==c){let g=b.classList,h=Sc.theme;var e=null!==c?h[c]:void 0;let k=null!==d?h[d]:void 0;void 0!==e&&("string"===typeof e&&(e=rb(e),e=h[c]=e),g.remove(...e));null===d||f&&"ltr"===d?b.removeAttribute("dir"):(void 0!==k&&("string"===typeof k&&(c=rb(k),k=h[d]=c),void 0!==k&&g.add(...k)),b.dir=d);Vc||(a.getWritable().__dir=d)}fd=d;b.__lexicalDirTextContent=
N;b.__lexicalDir=d}}function od(a,b){let c=[];for(a=a.__first;null!==a;){let d=b.get(a);void 0===d&&n(101);c.push(a);a=d.__next}return c}
function zd(a,b){var c=id.get(a),d=jd.get(a);void 0!==c&&void 0!==d||n(61);var e=Uc||hd.has(a)||gd.has(a);let f=Ac(O,a);if(c===d&&!e)return E(c)?(d=f.__lexicalTextContent,void 0!==d&&(M+=d,Rc+=d),d=f.__lexicalDirTextContent,void 0!==d&&(N+=d)):(d=c.getTextContent(),B(c)&&!c.isDirectionless()&&(N+=d),Rc+=d,M+=d),f;c!==d&&e&&wc(ld,Tc,ed,d,"updated");d.updateDOMProperties(c,f,Sc);if(d.updateDOM(c,f,Sc))return d=td(a,null,null),null===b&&n(62),b.replaceChild(d,f),md(a,null),d;if(E(c)&&E(d)){a=d.__indent;
a!==c.__indent&&rd(f,a);a=d.__format;a!==c.__format&&sd(f,a);if(e){a=N;N="";Qc=null;e=M;var g=c.__size,h=d.__size;M="";if(1===g&&1===h){var k=c.__first,m=d.__first;if(k===m)zd(k,f);else{b=nd(k);var p=td(m,null,null);f.replaceChild(p,b);md(k,null)}k=jd.get(m);null===Qc&&B(k)&&(Qc=k.getFormat())}else{b=od(c,id);var q=od(d,jd);if(0===g)0!==h&&ud(q,d,0,h-1,f,null);else if(0===h)0!==g&&(k=null==f.__lexicalLineBreak,pd(b,0,g-1,k?null:f),k&&(f.textContent=""));else{p=b;b=q;q=g-1;g=h-1;let w=f.firstChild,
A=0;for(h=0;A<=q&&h<=g;){var l=p[A],r=b[h];if(l===r)w=Ad(zd(r,f)),A++,h++;else{void 0===k&&(k=new Set(p));void 0===m&&(m=new Set(b));let y=m.has(l),z=k.has(r);y?(z?(l=Ac(O,r),l===w?w=Ad(zd(r,f)):(null!=w?f.insertBefore(l,w):f.appendChild(l),zd(r,f)),A++):td(r,f,w),h++):(w=Ad(nd(l)),md(l,f),A++)}r=jd.get(r);null!==r&&null===Qc&&B(r)&&(Qc=r.getFormat())}k=A>q;m=h>g;k&&!m?(k=b[g+1],k=void 0===k?null:O.getElementByKey(k),ud(b,d,h,g,f,k)):m&&!k&&pd(p,A,q,f)}}zc(d)&&(M+="\n\n");f.__lexicalTextContent=M;
M=e+M;vd(d,f);Bd(d)&&null!=Qc&&Qc!==d.__textFormat&&d.setTextFormat(Qc);N=a;Qc=null;L(d)||d.isInline()||wd(c,d,f)}zc(d)&&(M+="\n\n",Rc+="\n\n")}else c=d.getTextContent(),x(d)?(e=d.decorate(O,Sc),null!==e&&xd(a,e)):B(d)&&!d.isDirectionless()&&(N+=c),M+=c,Rc+=c;!Vc&&L(d)&&d.__cachedText!==Rc&&(d.getWritable().__cachedText=Rc);return f}function xd(a,b){let c=O._pendingDecorators,d=O._decorators;if(null===c){if(d[a]===b)return;c=kc(O)}c[a]=b}
function Ad(a){a=a.nextSibling;null!==a&&a===O._blockCursorElement&&(a=a.nextSibling);return a}function nd(a){let b=kd.get(a);void 0===b&&n(75,a);return b}let Cd=Object.freeze({}),Jd=[["keydown",Dd],["pointerdown",Ed],["compositionstart",Fd],["compositionend",Gd],["input",Hd],["click",Id],["cut",Cd],["copy",Cd],["dragstart",Cd],["dragover",Cd],["dragend",Cd],["paste",Cd],["focus",Cd],["blur",Cd],["drop",Cd]];Ya&&Jd.push(["beforeinput",(a,b)=>Kd(a,b)]);
let Ld=0,Md=null,Nd=0,Od=null,Pd=new WeakMap,Qd=!1,Rd=!1,Sd=!1,Td=!1,Ud=[0,"",0,"root",0];
function Vd(a,b,c,d,e){let f=a.anchor,g=a.focus,h=f.getNode();var k=F();let m=zb(k._window),p=null!==m?m.anchorNode:null,q=f.key;k=k.getElementByKey(q);let l=c.length;return q!==g.key||!B(h)||(!e&&(!Ya||Nd<d+50)||h.isDirty()&&2>l||oc(c))&&f.offset!==g.offset&&!h.isComposing()||ac(h)||h.isDirty()&&1<l||(e||!Ya)&&null!==k&&!h.isComposing()&&p!==bc(k)||null!==m&&null!==b&&(!b.collapsed||b.startContainer!==m.anchorNode||b.startOffset!==m.anchorOffset)||h.getFormat()!==a.format||h.getStyle()!==a.style||
tc(a,h)}function Wd(a,b){return null!==a&&null!==a.nodeValue&&3===a.nodeType&&0!==b&&b!==a.nodeValue.length}
function Xd(a,b,c){let {anchorNode:d,anchorOffset:e,focusNode:f,focusOffset:g}=a;if(Qd&&(Qd=!1,Wd(d,e)&&Wd(f,g)))return;v(b,()=>{if(!c)Cb(null);else if(Sb(b,d,f)){var h=u();if(C(h)){var k=h.anchor,m=k.getNode();if(h.isCollapsed()){"Range"===a.type&&a.anchorNode===a.focusNode&&(h.dirty=!0);var p=Gb(b).event;p=p?p.timeStamp:performance.now();let [A,y,z,R,X]=Ud;var q=J();q=!1===b.isComposing()&&""===q.getTextContent();p<X+200&&k.offset===z&&k.key===R?(h.format=A,h.style=y):"text"===k.type?(B(m)||n(141),
h.format=m.getFormat(),h.style=m.getStyle()):"element"!==k.type||q||(k=k.getNode(),k instanceof Yd&&0===k.getChildrenSize()?h.format=k.getTextFormat():h.format=0,h.style="")}else{var l=k.key,r=h.focus.key;k=h.getNodes();m=k.length;var w=h.isBackward();p=w?g:e;q=w?e:g;let A=w?r:l;l=w?l:r;r=255;w=!1;for(let y=0;y<m;y++){let z=k[y],R=z.getTextContentSize();if(B(z)&&0!==R&&!(0===y&&z.__key===A&&p===R||y===m-1&&z.__key===l&&0===q)&&(w=!0,r&=z.getFormat(),0===r))break}h.format=w?r:0}}S(b,ba,void 0)}})}
function Id(a,b){v(b,()=>{let c=u();var d=zb(b._window);let e=sc();if(d)if(C(c)){let g=c.anchor;var f=g.getNode();"element"===g.type&&0===g.offset&&c.isCollapsed()&&!L(f)&&1===J().getChildrenSize()&&f.getTopLevelElementOrThrow().isEmpty()&&null!==e&&c.is(e)?(d.removeAllRanges(),c.dirty=!0):3!==a.detail||c.isCollapsed()||(d=c.focus.getNode(),f!==d&&(E(f)?f.select(0):f.getParentOrThrow().select(0)))}else"touch"===a.pointerType&&(f=d.anchorNode,null!==f&&(f=f.nodeType,1===f||3===f))&&(d=Zd(e,d,b,a),
Cb(d));S(b,ca,a)})}function Ed(a,b){let c=a.target;a=a.pointerType;c instanceof Node&&"touch"!==a&&v(b,()=>{x(yb(c))||(Rd=!0)})}function $d(a){if(!a.getTargetRanges)return null;a=a.getTargetRanges();return 0===a.length?null:a[0]}function ae(a,b){return a!==b||E(a)||E(b)||!a.isToken()||!b.isToken()}
function Kd(a,b){let c=a.inputType,d=$d(a);"deleteCompositionText"===c||Wa&&Db(b)||"insertCompositionText"!==c&&v(b,()=>{var e=u();if("deleteContentBackward"===c){if(null===e){var f=sc();if(!C(f))return;Cb(f.clone())}if(C(e)){f=e.anchor.key===e.focus.key;if("Delete"===Md&&a.timeStamp<Ld+30&&b.isComposing()&&f)H(null),Ld=0,setTimeout(()=>{v(b,()=>{H(null)})},30),C(e)&&(f=e.anchor.getNode(),f.markDirty(),e.format=f.getFormat(),B(f)||n(142),e.style=f.getStyle());else{H(null);a.preventDefault();var g=
e.anchor.getNode().getTextContent();e=0===e.anchor.offset&&e.focus.offset===g.length;cb&&f&&!e||S(b,da,!0)}return}}if(C(e)){f=a.data;null!==Od&&rc(!1,b,Od);e.dirty&&null===Od||!e.isCollapsed()||L(e.anchor.getNode())||null===d||e.applyDOMRange(d);Od=null;var h=e.focus;g=e.anchor.getNode();h=h.getNode();if("insertText"===c||"insertTranspose"===c)"\n"===f?(a.preventDefault(),S(b,ea,!1)):"\n\n"===f?(a.preventDefault(),S(b,fa,void 0)):null==f&&a.dataTransfer?(f=a.dataTransfer.getData("text/plain"),a.preventDefault(),
e.insertRawText(f)):null!=f&&Vd(e,d,f,a.timeStamp,!0)?(a.preventDefault(),S(b,ha,f)):Od=f,Nd=a.timeStamp;else switch(a.preventDefault(),c){case "insertFromYank":case "insertFromDrop":case "insertReplacementText":S(b,ha,a);break;case "insertFromComposition":H(null);S(b,ha,a);break;case "insertLineBreak":H(null);S(b,ea,!1);break;case "insertParagraph":H(null);Sd&&!$a?(Sd=!1,S(b,ea,!1)):S(b,fa,void 0);break;case "insertFromPaste":case "insertFromPasteAsQuotation":S(b,ia,a);break;case "deleteByComposition":ae(g,
h)&&S(b,la,a);break;case "deleteByDrag":case "deleteByCut":S(b,la,a);break;case "deleteContent":S(b,da,!1);break;case "deleteWordBackward":S(b,na,!0);break;case "deleteWordForward":S(b,na,!1);break;case "deleteHardLineBackward":case "deleteSoftLineBackward":S(b,oa,!0);break;case "deleteContentForward":case "deleteHardLineForward":case "deleteSoftLineForward":S(b,oa,!1);break;case "formatStrikeThrough":S(b,pa,"strikethrough");break;case "formatBold":S(b,pa,"bold");break;case "formatItalic":S(b,pa,
"italic");break;case "formatUnderline":S(b,pa,"underline");break;case "historyUndo":S(b,qa,void 0);break;case "historyRedo":S(b,sa,void 0)}}})}
function Hd(a,b){a.stopPropagation();v(b,()=>{var c=u(),d=a.data,e=$d(a);if(null!=d&&C(c)&&Vd(c,e,d,a.timeStamp,!1)){Td&&(be(b,d),Td=!1);var f=c.anchor.getNode();e=zb(b._window);if(null===e)return;var g=c.isBackward();let h=g?c.anchor.offset:c.focus.offset,k=g?c.focus.offset:c.anchor.offset;if(g=Ya&&!c.isCollapsed()&&B(f)&&null!==e.anchorNode)f=f.getTextContent().slice(0,h)+d+f.getTextContent().slice(h+k),e=e.anchorNode,g=f===(3===e.nodeType?e.nodeValue:null);g||S(b,ha,d);d=d.length;Wa&&1<d&&"insertCompositionText"===
a.inputType&&!b.isComposing()&&(c.anchor.offset-=d);Za||$a||db||!b.isComposing()||(Ld=0,H(null))}else rc(!1,b,null!==d?d:void 0),Td&&(be(b,d||void 0),Td=!1);G();c=F();Eb(c)});Od=null}function Fd(a,b){v(b,()=>{let c=u();if(C(c)&&!b.isComposing()){let d=c.anchor,e=c.anchor.getNode();H(d.key);(a.timeStamp<Ld+30||"element"===d.type||!c.isCollapsed()||e.getFormat()!==c.format||B(e)&&e.getStyle()!==c.style)&&S(b,ha,fb)}})}
function be(a,b){var c=a._compositionKey;H(null);if(null!==c&&null!=b){if(""===b){b=I(c);a=bc(a.getElementByKey(c));null!==a&&null!==a.nodeValue&&B(b)&&Ab(b,a.nodeValue,null,null,!0);return}if("\n"===b[b.length-1]&&(c=u(),C(c))){b=c.focus;c.anchor.set(b.key,b.offset,b.type);S(a,Ba,null);return}}rc(!0,a,b)}function Gd(a,b){Wa?Td=!0:v(b,()=>{be(b,a.data)})}
function Dd(a,b){Ld=a.timeStamp;Md=a.code;if(!b.isComposing()){var {code:c,shiftKey:d,ctrlKey:e,metaKey:f,altKey:g}=a;if(!S(b,ta,a)){if("ArrowRight"!==c||e||f||g)if("ArrowRight"!==c||g||d||!e&&!f)if("ArrowLeft"!==c||e||f||g)if("ArrowLeft"!==c||g||d||!e&&!f)if("ArrowUp"!==c||e||f)if("ArrowDown"!==c||e||f)if("Enter"===c&&d)Sd=!0,S(b,Ba,a);else if("Space"===c)S(b,Ca,a);else if(t&&e&&"KeyO"===c)a.preventDefault(),Sd=!0,S(b,ea,!0);else if("Enter"!==c||d){var h=t?g||f?!1:uc(c)||"KeyH"===c&&e:e||g||f?!1:
uc(c);h?uc(c)?S(b,Da,a):(a.preventDefault(),S(b,da,!0)):"Escape"===c?S(b,Ea,a):(h=t?d||g||f?!1:"Delete"===c||"KeyD"===c&&e:e||g||f?!1:"Delete"===c,h?"Delete"===c?S(b,Ha,a):(a.preventDefault(),S(b,da,!1)):uc(c)&&(t?g:e)?(a.preventDefault(),S(b,na,!0)):"Delete"===c&&(t?g:e)?(a.preventDefault(),S(b,na,!1)):t&&f&&uc(c)?(a.preventDefault(),S(b,oa,!0)):t&&f&&"Delete"===c?(a.preventDefault(),S(b,oa,!1)):"KeyB"===c&&!g&&(t?f:e)?(a.preventDefault(),S(b,pa,"bold")):"KeyU"===c&&!g&&(t?f:e)?(a.preventDefault(),
S(b,pa,"underline")):"KeyI"===c&&!g&&(t?f:e)?(a.preventDefault(),S(b,pa,"italic")):"Tab"!==c||g||e||f?"KeyZ"===c&&!d&&(t?f:e)?(a.preventDefault(),S(b,qa,void 0)):(h=t?"KeyZ"===c&&f&&d:"KeyY"===c&&e||"KeyZ"===c&&e&&d,h?(a.preventDefault(),S(b,sa,void 0)):ce(b._editorState._selection)?(h=d?!1:"KeyC"===c?t?f:e:!1,h?(a.preventDefault(),S(b,Na,a)):(h=d?!1:"KeyX"===c?t?f:e:!1,h?(a.preventDefault(),S(b,Oa,a)):"KeyA"===c&&(t?f:e)&&(a.preventDefault(),S(b,Pa,a)))):!Wa&&"KeyA"===c&&(t?f:e)&&(a.preventDefault(),
S(b,Pa,a))):S(b,Ia,a))}else Sd=!1,S(b,Ba,a);else S(b,Aa,a);else S(b,za,a);else S(b,xa,a);else S(b,wa,a);else S(b,va,a);else S(b,ua,a);(e||d||g||f)&&S(b,Sa,a)}}}function de(a){let b=a.__lexicalEventHandles;void 0===b&&(b=[],a.__lexicalEventHandles=b);return b}let ee=new Map;
function fe(a){var b=a.target;let c=zb(null==b?null:9===b.nodeType?b.defaultView:b.ownerDocument.defaultView);if(null!==c){var d=Zb(c.anchorNode);if(null!==d){Rd&&(Rd=!1,v(d,()=>{var h=sc(),k=c.anchorNode;null!==k&&(k=k.nodeType,1===k||3===k)&&(h=Zd(h,c,d,a),Cb(h))}));b=pc(d);b=b[b.length-1];var e=b._key,f=ee.get(e),g=f||b;g!==d&&Xd(c,g,!1);Xd(c,d,!0);d!==b?ee.set(e,d):f&&ee.delete(e)}}}
function ge(a,b){var c=a.ownerDocument,d=Pd.get(c);(void 0===d||1>d)&&c.addEventListener("selectionchange",fe);Pd.set(c,(d||0)+1);a.__lexicalEditor=b;c=de(a);for(d=0;d<Jd.length;d++){let [e,f]=Jd[d],g="function"===typeof f?h=>{!0!==h._lexicalHandled&&(h._lexicalHandled=!0,(b.isEditable()||"click"===e)&&f(h,b))}:h=>{if(!0!==h._lexicalHandled&&(h._lexicalHandled=!0,b.isEditable()))switch(e){case "cut":return S(b,Oa,h);case "copy":return S(b,Na,h);case "paste":return S(b,ia,h);case "dragstart":return S(b,
Ka,h);case "dragover":return S(b,La,h);case "dragend":return S(b,Ma,h);case "focus":return S(b,Qa,h);case "blur":return S(b,Ra,h);case "drop":return S(b,Ja,h)}};a.addEventListener(e,g);c.push(()=>{a.removeEventListener(e,g)})}}
function he(a,b,c){G();var d=a.__key;let e=a.getParent();if(null!==e){var f=u();if(C(f)&&E(a)){var {anchor:g,focus:h}=f;var k=g.getNode();var m=h.getNode();Bc(k,a)&&g.set(a.__key,0,"element");Bc(m,a)&&h.set(a.__key,0,"element")}k=f;m=!1;if(C(k)&&b){f=k.anchor;let p=k.focus;f.key===d&&(ie(f,a,e,a.getPreviousSibling(),a.getNextSibling()),m=!0);p.key===d&&(ie(p,a,e,a.getPreviousSibling(),a.getNextSibling()),m=!0)}else ce(k)&&b&&a.isSelected()&&a.selectPrevious();C(k)&&b&&!m?(d=a.getIndexWithinParent(),
gc(a),je(k,e,d,-1)):gc(a);c||Dc(e)||e.canBeEmpty()||!e.isEmpty()||he(e,b);b&&L(e)&&e.isEmpty()&&e.selectEnd()}}
class ke{static getType(){n(64,this.name)}static clone(){n(65,this.name)}constructor(a){this.__type=this.constructor.getType();this.__next=this.__prev=this.__parent=null;dc(this,a)}getType(){return this.__type}isInline(){n(137,this.constructor.name)}isAttached(){for(var a=this.__key;null!==a;){if("root"===a)return!0;a=I(a);if(null===a)break;a=a.__parent}return!1}isSelected(a){a=a||u();if(null==a)return!1;let b=a.getNodes().some(c=>c.__key===this.__key);return B(this)?b:C(a)&&"element"===a.anchor.type&&
"element"===a.focus.type&&a.anchor.key===a.focus.key&&a.anchor.offset===a.focus.offset?!1:b}getKey(){return this.__key}getIndexWithinParent(){var a=this.getParent();if(null===a)return-1;a=a.getFirstChild();let b=0;for(;null!==a;){if(this.is(a))return b;b++;a=a.getNextSibling()}return-1}getParent(){let a=this.getLatest().__parent;return null===a?null:I(a)}getParentOrThrow(){let a=this.getParent();null===a&&n(66,this.__key);return a}getTopLevelElement(){let a=this;for(;null!==a;){let b=a.getParent();
if(Dc(b))return E(a)||n(138),a;a=b}return null}getTopLevelElementOrThrow(){let a=this.getTopLevelElement();null===a&&n(67,this.__key);return a}getParents(){let a=[],b=this.getParent();for(;null!==b;)a.push(b),b=b.getParent();return a}getParentKeys(){let a=[],b=this.getParent();for(;null!==b;)a.push(b.__key),b=b.getParent();return a}getPreviousSibling(){let a=this.getLatest().__prev;return null===a?null:I(a)}getPreviousSiblings(){let a=[];var b=this.getParent();if(null===b)return a;for(b=b.getFirstChild();null!==
b&&!b.is(this);)a.push(b),b=b.getNextSibling();return a}getNextSibling(){let a=this.getLatest().__next;return null===a?null:I(a)}getNextSiblings(){let a=[],b=this.getNextSibling();for(;null!==b;)a.push(b),b=b.getNextSibling();return a}getCommonAncestor(a){let b=this.getParents();var c=a.getParents();E(this)&&b.unshift(this);E(a)&&c.unshift(a);a=b.length;var d=c.length;if(0===a||0===d||b[a-1]!==c[d-1])return null;c=new Set(c);for(d=0;d<a;d++){let e=b[d];if(c.has(e))return e}return null}is(a){return null==
a?!1:this.__key===a.__key}isBefore(a){if(this===a)return!1;if(a.isParentOf(this))return!0;if(this.isParentOf(a))return!1;var b=this.getCommonAncestor(a);let c=this;for(;;){var d=c.getParentOrThrow();if(d===b){d=c.getIndexWithinParent();break}c=d}for(c=a;;){a=c.getParentOrThrow();if(a===b){b=c.getIndexWithinParent();break}c=a}return d<b}isParentOf(a){let b=this.__key;if(b===a.__key)return!1;for(;null!==a;){if(a.__key===b)return!0;a=a.getParent()}return!1}getNodesBetween(a){let b=this.isBefore(a),c=
[],d=new Set;for(var e=this;null!==e;){var f=e.__key;d.has(f)||(d.add(f),c.push(e));if(e===a)break;f=E(e)?b?e.getFirstChild():e.getLastChild():null;if(null!==f)e=f;else if(f=b?e.getNextSibling():e.getPreviousSibling(),null!==f)e=f;else{e=e.getParentOrThrow();d.has(e.__key)||c.push(e);if(e===a)break;f=e;do if(null===f&&n(68),e=b?f.getNextSibling():f.getPreviousSibling(),f=f.getParent(),null!==f)null!==e||d.has(f.__key)||c.push(f);else break;while(null===e)}}b||c.reverse();return c}isDirty(){let a=
F()._dirtyLeaves;return null!==a&&a.has(this.__key)}getLatest(){let a=I(this.__key);null===a&&n(113);return a}getWritable(){G();var a=fc(),b=F();a=a._nodeMap;let c=this.__key,d=this.getLatest(),e=d.__parent;b=b._cloneNotNeeded;var f=u();null!==f&&f.setCachedNodes(null);if(b.has(c))return hc(d),d;f=d.constructor.clone(d);f.__parent=e;f.__next=d.__next;f.__prev=d.__prev;E(d)&&E(f)?(Bd(d)&&Bd(f)&&(f.__textFormat=d.__textFormat),f.__first=d.__first,f.__last=d.__last,f.__size=d.__size,f.__indent=d.__indent,
f.__format=d.__format,f.__dir=d.__dir):B(d)&&B(f)&&(f.__format=d.__format,f.__style=d.__style,f.__mode=d.__mode,f.__detail=d.__detail);b.add(c);f.__key=c;hc(f);a.set(c,f);return f}getTextContent(){return""}getTextContentSize(){return this.getTextContent().length}createDOM(){n(70)}updateDOM(){n(71)}updateDOMProperties(){}exportDOM(a){return{element:this.createDOM(a._config,a)}}exportJSON(){n(72)}static importJSON(){n(18,this.name)}static transform(){return null}remove(a){he(this,!0,a)}replace(a,b){G();
var c=u();null!==c&&(c=c.clone());Gc(this,a);let d=this.getLatest(),e=this.__key,f=a.__key,g=a.getWritable();a=this.getParentOrThrow().getWritable();let h=a.__size;gc(g);let k=d.getPreviousSibling(),m=d.getNextSibling(),p=d.__prev,q=d.__next,l=d.__parent;he(d,!1,!0);null===k?a.__first=f:k.getWritable().__next=f;g.__prev=p;null===m?a.__last=f:m.getWritable().__prev=f;g.__next=q;g.__parent=l;a.__size=h;b&&(E(this)&&E(g)||n(139),this.getChildren().forEach(r=>{g.append(r)}));C(c)&&(Cb(c),b=c.anchor,c=
c.focus,b.key===e&&le(b,g),c.key===e&&le(c,g));ic()===e&&H(f);return g}insertAfter(a,b=!0){G();Gc(this,a);var c=this.getWritable();let d=a.getWritable();var e=d.getParent();let f=u();var g=!1,h=!1;if(null!==e){var k=a.getIndexWithinParent();gc(d);C(f)&&(h=e.__key,g=f.anchor,e=f.focus,g="element"===g.type&&g.key===h&&g.offset===k+1,h="element"===e.type&&e.key===h&&e.offset===k+1)}e=this.getNextSibling();k=this.getParentOrThrow().getWritable();let m=d.__key,p=c.__next;null===e?k.__last=m:e.getWritable().__prev=
m;k.__size++;c.__next=m;d.__next=p;d.__prev=c.__key;d.__parent=c.__parent;b&&C(f)&&(b=this.getIndexWithinParent(),je(f,k,b+1),c=k.__key,g&&f.anchor.set(c,b+2,"element"),h&&f.focus.set(c,b+2,"element"));return a}insertBefore(a,b=!0){G();Gc(this,a);var c=this.getWritable();let d=a.getWritable(),e=d.__key;gc(d);let f=this.getPreviousSibling(),g=this.getParentOrThrow().getWritable(),h=c.__prev,k=this.getIndexWithinParent();null===f?g.__first=e:f.getWritable().__next=e;g.__size++;c.__prev=e;d.__prev=h;
d.__next=c.__key;d.__parent=c.__parent;c=u();b&&C(c)&&(b=this.getParentOrThrow(),je(c,b,k));return a}isParentRequired(){return!1}createParentElementNode(){return me()}selectStart(){return this.selectPrevious()}selectEnd(){return this.selectNext(0,0)}selectPrevious(a,b){G();let c=this.getPreviousSibling(),d=this.getParentOrThrow();return null===c?d.select(0,0):E(c)?c.select():B(c)?c.select(a,b):(a=c.getIndexWithinParent()+1,d.select(a,a))}selectNext(a,b){G();let c=this.getNextSibling(),d=this.getParentOrThrow();
return null===c?d.select():E(c)?c.select(0,0):B(c)?c.select(a,b):(a=c.getIndexWithinParent(),d.select(a,a))}markDirty(){this.getWritable()}}function ne(a,b){let c=b.getParentOrThrow().getLastChild(),d=b;for(b=[b];d!==c;)d.getNextSibling()||n(140),d=d.getNextSibling(),b.push(d);for(let e of b)a=a.insertAfter(e)}
class oe extends ke{static getType(){return"linebreak"}static clone(a){return new oe(a.__key)}constructor(a){super(a)}getTextContent(){return"\n"}createDOM(){return document.createElement("br")}updateDOM(){return!1}static importDOM(){return{br:a=>{a:{var b=a.parentElement;if(null!==b){let c=b.firstChild;if(c===a||c.nextSibling===a&&pe(c))if(b=b.lastChild,b===a||b.previousSibling===a&&pe(b)){a=!0;break a}}a=!1}return a?null:{conversion:qe,priority:0}}}}static importJSON(){return re()}exportJSON(){return{type:"linebreak",
version:1}}}function qe(){return{node:re()}}function re(){return Fc(new oe)}function Mc(a){return a instanceof oe}function pe(a){return 3===a.nodeType&&/^( |\t|\r?\n)+$/.test(a.textContent||"")}function se(a,b){return b&16?"code":b&128?"mark":b&32?"sub":b&64?"sup":null}function te(a,b){return b&1?"strong":b&2?"em":"span"}
function ue(a,b,c,d,e){a=d.classList;d=vc(e,"base");void 0!==d&&a.add(...d);d=vc(e,"underlineStrikethrough");let f=!1,g=b&8&&b&4;var h=c&8&&c&4;void 0!==d&&(h?(f=!0,g||a.add(...d)):g&&a.remove(...d));for(let k in ib)h=ib[k],d=vc(e,k),void 0!==d&&(c&h?!f||"underline"!==k&&"strikethrough"!==k?(0===(b&h)||g&&"underline"===k||"strikethrough"===k)&&a.add(...d):b&h&&a.remove(...d):b&h&&a.remove(...d))}
function ve(a,b,c){let d=b.firstChild;c=c.isComposing();a+=c?eb:"";if(null==d)b.textContent=a;else if(b=d.nodeValue,b!==a)if(c||Wa){c=b.length;let e=a.length,f=0,g=0;for(;f<c&&f<e&&b[f]===a[f];)f++;for(;g+f<c&&g+f<e&&b[c-g-1]===a[e-g-1];)g++;a=[f,c-f-g,a.slice(f,e-g)];let [h,k,m]=a;0!==k&&d.deleteData(h,k);d.insertData(h,m)}else d.nodeValue=a}function we(a,b){b=document.createElement(b);b.appendChild(a);return b}
class xe extends ke{static getType(){return"text"}static clone(a){return new xe(a.__text,a.__key)}constructor(a,b){super(b);this.__text=a;this.__format=0;this.__style="";this.__detail=this.__mode=0}getFormat(){return this.getLatest().__format}getDetail(){return this.getLatest().__detail}getMode(){let a=this.getLatest();return qb[a.__mode]}getStyle(){return this.getLatest().__style}isToken(){return 1===this.getLatest().__mode}isComposing(){return this.__key===ic()}isSegmented(){return 2===this.getLatest().__mode}isDirectionless(){return 0!==
(this.getLatest().__detail&1)}isUnmergeable(){return 0!==(this.getLatest().__detail&2)}hasFormat(a){a=ib[a];return 0!==(this.getFormat()&a)}isSimpleText(){return"text"===this.__type&&0===this.__mode}getTextContent(){return this.getLatest().__text}getFormatFlags(a,b){let c=this.getLatest().__format;return cc(c,a,b)}canHaveFormat(){return!0}createDOM(a){var b=this.__format,c=se(this,b);let d=te(this,b),e=document.createElement(null===c?d:c),f=e;this.hasFormat("code")&&e.setAttribute("spellcheck","false");
null!==c&&(f=document.createElement(d),e.appendChild(f));c=f;ve(this.__text,c,this);a=a.theme.text;void 0!==a&&ue(d,0,b,c,a);b=this.__style;""!==b&&(e.style.cssText=b);return e}updateDOM(a,b,c){let d=this.__text;var e=a.__format,f=this.__format,g=se(this,e);let h=se(this,f);var k=te(this,e);let m=te(this,f);if((null===g?k:g)!==(null===h?m:h))return!0;if(g===h&&k!==m)return e=b.firstChild,null==e&&n(48),a=g=document.createElement(m),ve(d,a,this),c=c.theme.text,void 0!==c&&ue(m,0,f,a,c),b.replaceChild(g,
e),!1;k=b;null!==h&&null!==g&&(k=b.firstChild,null==k&&n(49));ve(d,k,this);c=c.theme.text;void 0!==c&&e!==f&&ue(m,e,f,k,c);f=this.__style;a.__style!==f&&(b.style.cssText=f);return!1}static importDOM(){return{"#text":()=>({conversion:ye,priority:0}),b:()=>({conversion:ze,priority:0}),code:()=>({conversion:Ae,priority:0}),em:()=>({conversion:Ae,priority:0}),i:()=>({conversion:Ae,priority:0}),s:()=>({conversion:Ae,priority:0}),span:()=>({conversion:Be,priority:0}),strong:()=>({conversion:Ae,priority:0}),
sub:()=>({conversion:Ae,priority:0}),sup:()=>({conversion:Ae,priority:0}),u:()=>({conversion:Ae,priority:0})}}static importJSON(a){let b=K(a.text);b.setFormat(a.format);b.setDetail(a.detail);b.setMode(a.mode);b.setStyle(a.style);return b}exportDOM(a){({element:a}=super.exportDOM(a));null!==a&&Jc(a)||n(132);a.style.whiteSpace="pre-wrap";this.hasFormat("bold")&&(a=we(a,"b"));this.hasFormat("italic")&&(a=we(a,"i"));this.hasFormat("strikethrough")&&(a=we(a,"s"));this.hasFormat("underline")&&(a=we(a,"u"));
return{element:a}}exportJSON(){return{detail:this.getDetail(),format:this.getFormat(),mode:this.getMode(),style:this.getStyle(),text:this.getTextContent(),type:"text",version:1}}selectionTransform(){}setFormat(a){let b=this.getWritable();b.__format="string"===typeof a?ib[a]:a;return b}setDetail(a){let b=this.getWritable();b.__detail="string"===typeof a?jb[a]:a;return b}setStyle(a){let b=this.getWritable();b.__style=a;return b}toggleFormat(a){let b=this.getFormat();a=cc(b,a,null);return this.setFormat(a)}toggleDirectionless(){let a=
this.getWritable();a.__detail^=1;return a}toggleUnmergeable(){let a=this.getWritable();a.__detail^=2;return a}setMode(a){a=pb[a];if(this.__mode===a)return this;let b=this.getWritable();b.__mode=a;return b}setTextContent(a){if(this.__text===a)return this;let b=this.getWritable();b.__text=a;return b}select(a,b){G();let c=u();var d=this.getTextContent();let e=this.__key;"string"===typeof d?(d=d.length,void 0===a&&(a=d),void 0===b&&(b=d)):b=a=0;if(C(c))d=ic(),d!==c.anchor.key&&d!==c.focus.key||H(e),c.setTextNodeRange(this,
a,this,b);else return Ce(e,a,e,b,"text","text");return c}selectStart(){return this.select(0,0)}selectEnd(){let a=this.getTextContentSize();return this.select(a,a)}spliceText(a,b,c,d){let e=this.getWritable(),f=e.__text,g=c.length,h=a;0>h&&(h=g+h,0>h&&(h=0));let k=u();d&&C(k)&&(a+=g,k.setTextNodeRange(e,a,e,a));b=f.slice(0,h)+c+f.slice(h+b);e.__text=b;return e}canInsertTextBefore(){return!0}canInsertTextAfter(){return!0}splitText(...a){G();var b=this.getLatest(),c=b.getTextContent(),d=b.__key,e=ic(),
f=new Set(a);a=[];var g=c.length,h="";for(var k=0;k<g;k++)""!==h&&f.has(k)&&(a.push(h),h=""),h+=c[k];""!==h&&a.push(h);f=a.length;if(0===f)return[];if(a[0]===c)return[b];var m=a[0];c=b.getParentOrThrow();k=b.getFormat();let p=b.getStyle(),q=b.__detail;g=!1;b.isSegmented()?(h=K(m),h.__format=k,h.__style=p,h.__detail=q,g=!0):(h=b.getWritable(),h.__text=m);b=u();h=[h];m=m.length;for(let w=1;w<f;w++){var l=a[w],r=l.length;l=K(l).getWritable();l.__format=k;l.__style=p;l.__detail=q;let A=l.__key;r=m+r;
if(C(b)){let y=b.anchor,z=b.focus;y.key===d&&"text"===y.type&&y.offset>m&&y.offset<=r&&(y.key=A,y.offset-=m,b.dirty=!0);z.key===d&&"text"===z.type&&z.offset>m&&z.offset<=r&&(z.key=A,z.offset-=m,b.dirty=!0)}e===d&&H(A);m=r;h.push(l)}d=this.getPreviousSibling();e=this.getNextSibling();null!==d&&hc(d);null!==e&&hc(e);d=c.getWritable();e=this.getIndexWithinParent();g?(d.splice(e,0,h),this.remove()):d.splice(e,1,h);C(b)&&je(b,c,e,f-1);return h}mergeWithSibling(a){var b=a===this.getPreviousSibling();b||
a===this.getNextSibling()||n(50);var c=this.__key;let d=a.__key,e=this.__text,f=e.length;ic()===d&&H(c);let g=u();if(C(g)){let h=g.anchor,k=g.focus;null!==h&&h.key===d&&(De(h,b,c,a,f),g.dirty=!0);null!==k&&k.key===d&&(De(k,b,c,a,f),g.dirty=!0)}c=a.__text;this.setTextContent(b?c+e:e+c);b=this.getWritable();a.remove();return b}isTextEntity(){return!1}}
function Be(a){a=a.style;let b=a.fontWeight,c=a.textDecoration.split(" "),d="700"===b||"bold"===b,e=c.includes("line-through"),f="italic"===a.fontStyle,g=c.includes("underline"),h=a.verticalAlign;return{forChild:k=>{if(!B(k))return k;d&&k.toggleFormat("bold");e&&k.toggleFormat("strikethrough");f&&k.toggleFormat("italic");g&&k.toggleFormat("underline");"sub"===h&&k.toggleFormat("subscript");"super"===h&&k.toggleFormat("superscript");return k},node:null}}
function ze(a){let b="normal"===a.style.fontWeight;return{forChild:c=>{B(c)&&!b&&c.toggleFormat("bold");return c},node:null}}let Ee=new WeakMap;
function ye(a){null===a.parentElement&&n(129);for(var b=a.textContent||"",c,d=a.parentNode,e=[a];null!==d&&void 0===(c=Ee.get(d))&&!("PRE"===d.nodeName||1===d.nodeType&&void 0!==d.style&&void 0!==d.style.whiteSpace&&d.style.whiteSpace.startsWith("pre"));)e.push(d),d=d.parentNode;c=void 0===c?d:c;for(d=0;d<e.length;d++)Ee.set(e[d],c);if(null!==c){b=b.split(/(\r?\n|\t)/);a=[];e=b.length;for(c=0;c<e;c++)d=b[c],"\n"===d||"\r\n"===d?a.push(re()):"\t"===d?a.push(Oe()):""!==d&&a.push(K(d));return{node:a}}b=
b.replace(/\r/g,"").replace(/[ \t\n]+/g," ");if(""===b)return{node:null};if(" "===b[0]){e=a;for(c=!0;null!==e&&null!==(e=Pe(e,!1));)if(d=e.textContent||"",0<d.length){/[ \t\n]$/.test(d)&&(b=b.slice(1));c=!1;break}c&&(b=b.slice(1))}if(" "===b[b.length-1]){for(e=!0;null!==a&&null!==(a=Pe(a,!0));)if(0<(a.textContent||"").replace(/^( |\t|\r?\n)+/,"").length){e=!1;break}e&&(b=b.slice(0,b.length-1))}return""===b?{node:null}:{node:K(b)}}
function Pe(a,b){for(;;){for(var c=void 0;null===(c=b?a.nextSibling:a.previousSibling);)if(a=a.parentElement,null===a)return null;a=c;if(1===a.nodeType&&(c=a.style.display,""===c&&!Kc(a)||""!==c&&!c.startsWith("inline")))return null;for(;null!==(c=b?a.firstChild:a.lastChild);)a=c;if(3===a.nodeType)return a;if("BR"===a.nodeName)return null}}let Qe={code:"code",em:"italic",i:"italic",s:"strikethrough",strong:"bold",sub:"subscript",sup:"superscript",u:"underline"};
function Ae(a){let b=Qe[a.nodeName.toLowerCase()];return void 0===b?{node:null}:{forChild:c=>{B(c)&&!c.hasFormat(b)&&c.toggleFormat(b);return c},node:null}}function K(a=""){return Fc(new xe(a))}function B(a){return a instanceof xe}
class Re extends xe{static getType(){return"tab"}static clone(a){let b=new Re(a.__key);b.__text=a.__text;b.__format=a.__format;b.__style=a.__style;return b}constructor(a){super("\t",a);this.__detail=2}static importDOM(){return null}static importJSON(a){let b=Oe();b.setFormat(a.format);b.setStyle(a.style);return b}exportJSON(){return{...super.exportJSON(),type:"tab",version:1}}setTextContent(){n(126)}setDetail(){n(127)}setMode(){n(128)}canInsertTextBefore(){return!1}canInsertTextAfter(){return!1}}
function Oe(){return Fc(new Re)}function Se(a){return a instanceof Re}
class Te{constructor(a,b,c){this._selection=null;this.key=a;this.offset=b;this.type=c}is(a){return this.key===a.key&&this.offset===a.offset&&this.type===a.type}isBefore(a){let b=this.getNode(),c=a.getNode(),d=this.offset;a=a.offset;if(E(b)){var e=b.getDescendantByIndex(d);b=null!=e?e:b}E(c)&&(e=c.getDescendantByIndex(a),c=null!=e?e:c);return b===c?d<a:b.isBefore(c)}getNode(){let a=I(this.key);null===a&&n(20);return a}set(a,b,c){let d=this._selection,e=this.key;this.key=a;this.offset=b;this.type=c;
jc()||(ic()===e&&H(a),null!==d&&(d.setCachedNodes(null),d.dirty=!0))}}function Ue(a,b,c){return new Te(a,b,c)}function Ve(a,b){let c=b.__key,d=a.offset,e="element";if(B(b))e="text",b=b.getTextContentSize(),d>b&&(d=b);else if(!E(b)){var f=b.getNextSibling();if(B(f))c=f.__key,d=0,e="text";else if(f=b.getParent())c=f.__key,d=b.getIndexWithinParent()+1}a.set(c,d,e)}function le(a,b){if(E(b)){let c=b.getLastDescendant();E(c)||B(c)?Ve(a,c):Ve(a,b)}else Ve(a,b)}
function We(a,b,c,d){a.key=b;a.offset=c;a.type=d}
class Xe{constructor(a){this._cachedNodes=null;this._nodes=a;this.dirty=!1}getCachedNodes(){return this._cachedNodes}setCachedNodes(a){this._cachedNodes=a}is(a){if(!ce(a))return!1;let b=this._nodes,c=a._nodes;return b.size===c.size&&Array.from(b).every(d=>c.has(d))}isCollapsed(){return!1}isBackward(){return!1}getStartEndPoints(){return null}add(a){this.dirty=!0;this._nodes.add(a);this._cachedNodes=null}delete(a){this.dirty=!0;this._nodes.delete(a);this._cachedNodes=null}clear(){this.dirty=!0;this._nodes.clear();
this._cachedNodes=null}has(a){return this._nodes.has(a)}clone(){return new Xe(new Set(this._nodes))}extract(){return this.getNodes()}insertRawText(){}insertText(){}insertNodes(a){let b=this.getNodes(),c=b.length;var d=b[c-1];if(B(d))d=d.select();else{let e=d.getIndexWithinParent()+1;d=d.getParentOrThrow().select(e,e)}d.insertNodes(a);for(a=0;a<c;a++)b[a].remove()}getNodes(){var a=this._cachedNodes;if(null!==a)return a;var b=this._nodes;a=[];for(let c of b)b=I(c),null!==b&&a.push(b);jc()||(this._cachedNodes=
a);return a}getTextContent(){let a=this.getNodes(),b="";for(let c=0;c<a.length;c++)b+=a[c].getTextContent();return b}}function C(a){return a instanceof Ye}
class Ye{constructor(a,b,c,d){this.anchor=a;this.focus=b;a._selection=this;b._selection=this;this._cachedNodes=null;this.format=c;this.style=d;this.dirty=!1}getCachedNodes(){return this._cachedNodes}setCachedNodes(a){this._cachedNodes=a}is(a){return C(a)?this.anchor.is(a.anchor)&&this.focus.is(a.focus)&&this.format===a.format&&this.style===a.style:!1}isCollapsed(){return this.anchor.is(this.focus)}getNodes(){var a=this._cachedNodes;if(null!==a)return a;a=this.anchor;var b=this.focus,c=a.isBefore(b),
d=c?a:b;c=c?b:a;a=d.getNode();b=c.getNode();let e=d.offset;d=c.offset;E(a)&&(c=a.getDescendantByIndex(e),a=null!=c?c:a);E(b)&&(c=b.getDescendantByIndex(d),null!==c&&c!==a&&b.getChildAtIndex(d)===c&&(c=c.getPreviousSibling()),b=null!=c?c:b);a=a.is(b)?E(a)&&0<a.getChildrenSize()?[]:[a]:a.getNodesBetween(b);jc()||(this._cachedNodes=a);return a}setTextNodeRange(a,b,c,d){We(this.anchor,a.__key,b,"text");We(this.focus,c.__key,d,"text");this._cachedNodes=null;this.dirty=!0}getTextContent(){let a=this.getNodes();
if(0===a.length)return"";let b=a[0],c=a[a.length-1],d=this.anchor,e=this.focus,f=d.isBefore(e),[g,h]=Ze(this),k="",m=!0;for(let p=0;p<a.length;p++){let q=a[p];if(E(q)&&!q.isInline())m||(k+="\n"),m=q.isEmpty()?!1:!0;else if(m=!1,B(q)){let l=q.getTextContent();if(q===b)if(q===c){if("element"!==d.type||"element"!==e.type||e.offset===d.offset)l=g<h?l.slice(g,h):l.slice(h,g)}else l=f?l.slice(g):l.slice(h);else q===c&&(l=f?l.slice(0,h):l.slice(0,g));k+=l}else!x(q)&&!Mc(q)||q===c&&this.isCollapsed()||(k+=
q.getTextContent())}return k}applyDOMRange(a){let b=F(),c=b.getEditorState()._selection;a=$e(a.startContainer,a.startOffset,a.endContainer,a.endOffset,b,c);if(null!==a){var [d,e]=a;We(this.anchor,d.key,d.offset,d.type);We(this.focus,e.key,e.offset,e.type);this._cachedNodes=null}}clone(){let a=this.anchor,b=this.focus;return new Ye(Ue(a.key,a.offset,a.type),Ue(b.key,b.offset,b.type),this.format,this.style)}toggleFormat(a){this.format=cc(this.format,a,null);this.dirty=!0}setStyle(a){this.style=a;this.dirty=
!0}hasFormat(a){return 0!==(this.format&ib[a])}insertRawText(a){a=a.split(/(\r?\n|\t)/);let b=[],c=a.length;for(let d=0;d<c;d++){let e=a[d];"\n"===e||"\r\n"===e?b.push(re()):"\t"===e?b.push(Oe()):b.push(K(e))}this.insertNodes(b)}insertText(a){var b=this.anchor,c=this.focus,d=this.format,e=this.style,f=b,g=c;!this.isCollapsed()&&c.isBefore(b)&&(f=c,g=b);if("element"===f.type){b=f;c=g;var h=b.getNode(),k=h.getChildAtIndex(b.offset),m=K(),p=L(h)?me().append(m):m;m.setFormat(d);m.setStyle(e);null===k?
h.append(p):k.insertBefore(p);b.is(c)&&c.set(m.__key,0,"text");b.set(m.__key,0,"text")}c=f.offset;p=g.offset;h=this.getNodes();k=h.length;b=h[0];B(b)||n(26);m=b.getTextContent().length;var q=b.getParentOrThrow(),l=h[k-1];1===k&&"element"===g.type&&(p=m,g.set(f.key,p,"text"));if(this.isCollapsed()&&c===m&&(b.isSegmented()||b.isToken()||!b.canInsertTextAfter()||!q.canInsertTextAfter()&&null===b.getNextSibling())){if(f=b.getNextSibling(),B(f)&&f.canInsertTextBefore()&&!ac(f)||(f=K(),f.setFormat(d),q.canInsertTextAfter()?
b.insertAfter(f):q.insertAfter(f)),f.select(0,0),b=f,""!==a){this.insertText(a);return}}else if(this.isCollapsed()&&0===c&&(b.isSegmented()||b.isToken()||!b.canInsertTextBefore()||!q.canInsertTextBefore()&&null===b.getPreviousSibling())){f=b.getPreviousSibling();if(!B(f)||ac(f))f=K(),f.setFormat(d),q.canInsertTextBefore()?b.insertBefore(f):q.insertBefore(f);f.select();b=f;if(""!==a){this.insertText(a);return}}else if(b.isSegmented()&&c!==m)f=K(b.getTextContent()),f.setFormat(d),b.replace(f),b=f;else if(!(this.isCollapsed()||
""===a||(f=l.getParent(),q.canInsertTextBefore()&&q.canInsertTextAfter()&&(!E(f)||f.canInsertTextBefore()&&f.canInsertTextAfter())))){this.insertText("");af(this.anchor,this.focus,null);this.insertText(a);return}if(1===k)if(b.isToken())a=K(a),a.select(),b.replace(a);else{h=b.getFormat();k=b.getStyle();if(c===p&&(h!==d||k!==e))if(""===b.getTextContent())b.setFormat(d),b.setStyle(e);else{h=K(a);h.setFormat(d);h.setStyle(e);h.select();0===c?b.insertBefore(h,!1):([b]=b.splitText(c),b.insertAfter(h,!1));
h.isComposing()&&"text"===this.anchor.type&&(this.anchor.offset-=a.length);return}else if(Se(b)){a=K(a);a.setFormat(d);a.setStyle(e);a.select();b.replace(a);return}b=b.spliceText(c,p-c,a,!0);""===b.getTextContent()?b.remove():"text"===this.anchor.type&&(b.isComposing()?this.anchor.offset-=a.length:(this.format=h,this.style=k))}else{d=new Set([...b.getParentKeys(),...l.getParentKeys()]);q=E(b)?b:b.getParentOrThrow();e=E(l)?l:l.getParentOrThrow();f=l;if(!q.is(e)&&e.isInline()){do f=e,e=e.getParentOrThrow();
while(e.isInline())}if("text"===g.type&&(0!==p||""===l.getTextContent())||"element"===g.type&&l.getIndexWithinParent()<p)if(B(l)&&!l.isToken()&&p!==l.getTextContentSize()){if(l.isSegmented()){var r=K(l.getTextContent());l.replace(r);l=r}L(g.getNode())||"text"!==g.type||(l=l.spliceText(0,p,""));d.add(l.__key)}else g=l.getParentOrThrow(),g.canBeEmpty()||1!==g.getChildrenSize()?l.remove():g.remove();else d.add(l.__key);g=e.getChildren();p=new Set(h);l=q.is(e);q=q.isInline()&&null===b.getNextSibling()?
q:b;for(r=g.length-1;0<=r;r--){let w=g[r];if(w.is(b)||E(w)&&w.isParentOf(b))break;w.isAttached()&&(!p.has(w)||w.is(f)?l||q.insertAfter(w,!1):w.remove())}if(!l)for(g=e,e=null;null!==g;){p=g.getChildren();l=p.length;if(0===l||p[l-1].is(e))d.delete(g.__key),e=g;g=g.getParent()}b.isToken()?c===m?b.select():(a=K(a),a.select(),b.replace(a)):(b=b.spliceText(c,m-c,a,!0),""===b.getTextContent()?b.remove():b.isComposing()&&"text"===this.anchor.type&&(this.anchor.offset-=a.length));for(a=1;a<k;a++)b=h[a],d.has(b.__key)||
b.remove()}}removeText(){this.insertText("")}formatText(a){if(this.isCollapsed())this.toggleFormat(a),H(null);else{var b=this.getNodes(),c=[];for(var d of b)B(d)&&c.push(d);var e=c.length;if(0===e)this.toggleFormat(a),H(null);else{d=this.anchor;var f=this.focus,g=this.isBackward();b=g?f:d;d=g?d:f;var h=0,k=c[0];f="element"===b.type?0:b.offset;"text"===b.type&&f===k.getTextContentSize()&&(h=1,k=c[1],f=0);if(null!=k){g=k.getFormatFlags(a,null);var m=e-1,p=c[m];e="text"===d.type?d.offset:p.getTextContentSize();
if(k.is(p))f!==e&&(0===f&&e===k.getTextContentSize()?k.setFormat(g):(a=k.splitText(f,e),a=0===f?a[0]:a[1],a.setFormat(g),"text"===b.type&&b.set(a.__key,0,"text"),"text"===d.type&&d.set(a.__key,e-f,"text")),this.format=g);else{0!==f&&([,k]=k.splitText(f),f=0);k.setFormat(g);var q=p.getFormatFlags(a,g);0<e&&(e!==p.getTextContentSize()&&([p]=p.splitText(e)),p.setFormat(q));for(h+=1;h<m;h++){let l=c[h];if(!l.isToken()){let r=l.getFormatFlags(a,q);l.setFormat(r)}}"text"===b.type&&b.set(k.__key,f,"text");
"text"===d.type&&d.set(p.__key,e,"text");this.format=g|q}}}}}insertNodes(a){if(0!==a.length){if("root"===this.anchor.key){this.insertParagraph();var b=u();C(b)||n(134);return b.insertNodes(a)}b=this.isBackward()?this.focus:this.anchor;var c=Nc(b.getNode(),Lc);b=a[a.length-1];if("__language"in c&&E(c))if("__language"in a[0])this.insertText(a[0].getTextContent());else{var d=bf(this);c.splice(d,0,a);b.selectEnd()}else if(a.some(g=>(E(g)||x(g))&&!g.isInline())){b=cf(a);a=b.getLastDescendant();var e=b.getChildren();
b=E(c)&&c.isEmpty()?null:this.insertParagraph();d=e[e.length-1];var f=e[0];(g=>E(g)&&Lc(g)&&!g.isEmpty()&&E(c)&&(!c.isEmpty()||"__value"in c&&"__checked"in c))(f)&&(E(c)||n(135),c.append(...f.getChildren()),f=e[1]);f&&ne(c,f);e=Nc(a,Lc);b&&E(e)&&("__value"in b&&"__checked"in b||Lc(d))&&(e.append(...b.getChildren()),b.remove());E(c)&&c.isEmpty()&&c.remove();a.selectEnd();a=E(c)?c.getLastChild():null;Mc(a)&&e!==c&&a.remove()}else E(c)||n(135),d=bf(this),c.splice(d,0,a),b.selectEnd()}}insertParagraph(){if("root"===
this.anchor.key){var a=me();J().splice(this.anchor.offset,0,[a]);a.select();return a}var b=bf(this);a=Nc(this.anchor.getNode(),Lc);E(a)||n(136);b=(b=a.getChildAtIndex(b))?[b,...b.getNextSiblings()]:[];return(a=a.insertNewAfter(this,!1))?(a.append(...b),a.selectStart(),a):null}insertLineBreak(a){var b=re();this.insertNodes([b]);a&&(a=b.getParentOrThrow(),b=b.getIndexWithinParent(),a.select(b,b))}extract(){var a=this.getNodes(),b=a.length,c=b-1,d=this.anchor;let e=this.focus;var f=a[0];let g=a[c],[h,
k]=Ze(this);if(0===b)return[];if(1===b)return B(f)&&!this.isCollapsed()?(a=h>k?k:h,c=f.splitText(a,h>k?h:k),a=0===a?c[0]:c[1],null!=a?[a]:[]):[f];b=d.isBefore(e);B(f)&&(d=b?h:k,d===f.getTextContentSize()?a.shift():0!==d&&([,f]=f.splitText(d),a[0]=f));B(g)&&(f=g.getTextContent().length,b=b?k:h,0===b?a.pop():b!==f&&([g]=g.splitText(b),a[c]=g));return a}modify(a,b,c){var d=this.focus,e=this.anchor,f="move"===a,g=yc(d,b);if(x(g)&&!g.isIsolated())f&&g.isKeyboardSelectable()?(b=df(),b.add(g.__key),Cb(b)):
(a=b?g.getPreviousSibling():g.getNextSibling(),B(a)?(g=a.__key,b=b?a.getTextContent().length:0,d.set(g,b,"text"),f&&e.set(g,b,"text")):(c=g.getParentOrThrow(),E(a)?(c=a.__key,g=b?a.getChildrenSize():0):(g=g.getIndexWithinParent(),c=c.__key,b||g++),d.set(c,g,"element"),f&&e.set(c,g,"element")));else if(e=F(),d=zb(e._window)){var h=e._blockCursorElement,k=e._rootElement;null===k||null===h||!E(g)||g.isInline()||g.canBeEmpty()||Ic(h,e,k);d.modify(a,b?"backward":"forward",c);if(0<d.rangeCount&&(g=d.getRangeAt(0),
e=this.anchor.getNode(),e=L(e)?e:Cc(e),this.applyDOMRange(g),this.dirty=!0,!f)){f=this.getNodes();a=[];c=!1;for(h=0;h<f.length;h++)k=f[h],Bc(k,e)?a.push(k):c=!0;c&&0<a.length&&(b?(b=a[0],E(b)?b.selectStart():b.getParentOrThrow().selectStart()):(b=a[a.length-1],E(b)?b.selectEnd():b.getParentOrThrow().selectEnd()));if(d.anchorNode!==g.startContainer||d.anchorOffset!==g.startOffset)b=this.focus,f=this.anchor,d=f.key,g=f.offset,e=f.type,We(f,b.key,b.offset,b.type),We(b,d,g,e),this._cachedNodes=null}}}forwardDeletion(a,
b,c){return!c&&("element"===a.type&&E(b)&&a.offset===b.getChildrenSize()||"text"===a.type&&a.offset===b.getTextContentSize())&&(a=b.getParent(),b=b.getNextSibling()||(null===a?null:a.getNextSibling()),E(b)&&b.isShadowRoot())?!0:!1}deleteCharacter(a){let b=this.isCollapsed();if(this.isCollapsed()){var c=this.anchor,d=c.getNode();if(this.forwardDeletion(c,d,a))return;var e=this.focus,f=yc(e,a);if(x(f)&&!f.isIsolated()){f.isKeyboardSelectable()&&E(d)&&0===d.getChildrenSize()?(d.remove(),a=df(),a.add(f.__key),
Cb(a)):(f.remove(),F().dispatchCommand(ba,void 0));return}if(!a&&E(f)&&E(d)&&d.isEmpty()){d.remove();f.selectStart();return}this.modify("extend",a,"character");if(!this.isCollapsed()){f="text"===e.type?e.getNode():null;d="text"===c.type?c.getNode():null;if(null!==f&&f.isSegmented()){if(c=e.offset,e=f.getTextContentSize(),f.is(d)||a&&c!==e||!a&&0!==c){ef(f,a,c);return}}else if(null!==d&&d.isSegmented()&&(c=c.offset,e=d.getTextContentSize(),d.is(f)||a&&0!==c||!a&&c!==e)){ef(d,a,c);return}d=this.anchor;
f=this.focus;c=d.getNode();e=f.getNode();if(c===e&&"text"===d.type&&"text"===f.type){var g=d.offset,h=f.offset;let k=g<h;e=k?g:h;h=k?h:g;g=h-1;e!==g&&(c=c.getTextContent().slice(e,h),oc(c)||(a?f.offset=g:d.offset=g))}}else if(a&&0===c.offset&&("element"===c.type?c.getNode():c.getNode().getParentOrThrow()).collapseAtStart(this))return}this.removeText();a&&!b&&this.isCollapsed()&&"element"===this.anchor.type&&0===this.anchor.offset&&(a=this.anchor.getNode(),a.isEmpty()&&L(a.getParent())&&0===a.getIndexWithinParent()&&
a.collapseAtStart(this))}deleteLine(a){this.isCollapsed()&&("text"===this.anchor.type&&this.modify("extend",a,"lineboundary"),0===(a?this.focus:this.anchor).offset&&this.modify("extend",a,"character"));this.removeText()}deleteWord(a){if(this.isCollapsed()){let b=this.anchor,c=b.getNode();if(this.forwardDeletion(b,c,a))return;this.modify("extend",a,"word")}this.removeText()}isBackward(){return this.focus.isBefore(this.anchor)}getStartEndPoints(){return[this.anchor,this.focus]}}
function ce(a){return a instanceof Xe}function ff(a){let b=a.offset;if("text"===a.type)return b;a=a.getNode();return b===a.getChildrenSize()?a.getTextContent().length:0}function Ze(a){a=a.getStartEndPoints();if(null===a)return[0,0];let [b,c]=a;return"element"===b.type&&"element"===c.type&&b.key===c.key&&b.offset===c.offset?[0,0]:[ff(b),ff(c)]}
function ef(a,b,c){let d=a.getTextContent().split(/(?=\s)/g),e=d.length,f=0,g=0;for(let h=0;h<e;h++){let k=d[h],m=h===e-1;g=f;f+=k.length;if(b&&f===c||f>c||m){d.splice(h,1);m&&(g=void 0);break}}b=d.join("").trim();""===b?a.remove():(a.setTextContent(b),a.select(g,g))}
function gf(a,b,c,d){let e=b;if(1===a.nodeType){var f=!1;var g=a.childNodes;var h=g.length;d=d._blockCursorElement;e===h&&(f=!0,e=h-1);let k=g[e];h=!1;k===d?(k=g[e+1],h=!0):null!==d&&(g=d.parentNode,a===g&&(g=Array.prototype.indexOf.call(g.children,d),b>g&&e--));g=nc(k);if(B(g))e=f?g.getTextContentSize():0;else{d=nc(a);if(null===d)return null;if(E(d)){e=Math.min(d.getChildrenSize(),e);a=d.getChildAtIndex(e);if(b=E(a))b=a.getParent(),b=null===c||null===b||!b.canBeEmpty()||b!==c.getNode();b&&(c=f?a.getLastDescendant():
a.getFirstDescendant(),null===c?d=a:(a=c,d=E(a)?a:a.getParentOrThrow()),e=0);B(a)?(g=a,d=null,e=f?a.getTextContentSize():0):a!==d&&f&&!h&&e++}else f=d.getIndexWithinParent(),e=0===b&&x(d)&&nc(a)===d?f:f+1,d=d.getParentOrThrow();if(E(d))return Ue(d.__key,e,"element")}}else g=nc(a);return B(g)?Ue(g.__key,e,"text"):null}
function hf(a,b,c){var d=a.offset,e=a.getNode();0===d?(d=e.getPreviousSibling(),e=e.getParent(),b)?(c||!b)&&null===d&&E(e)&&e.isInline()&&(b=e.getPreviousSibling(),B(b)&&(a.key=b.__key,a.offset=b.getTextContent().length)):E(d)&&!c&&d.isInline()?(a.key=d.__key,a.offset=d.getChildrenSize(),a.type="element"):B(d)&&(a.key=d.__key,a.offset=d.getTextContent().length):d===e.getTextContent().length&&(d=e.getNextSibling(),e=e.getParent(),b&&E(d)&&d.isInline()?(a.key=d.__key,a.offset=0,a.type="element"):(c||
b)&&null===d&&E(e)&&e.isInline()&&!e.canInsertTextAfter()&&(b=e.getNextSibling(),B(b)&&(a.key=b.__key,a.offset=0)))}function af(a,b,c){if("text"===a.type&&"text"===b.type){var d=a.isBefore(b);let e=a.is(b);hf(a,d,e);hf(b,!d,e);e&&(b.key=a.key,b.offset=a.offset,b.type=a.type);d=F();d.isComposing()&&d._compositionKey!==a.key&&C(c)&&(d=c.anchor,c=c.focus,We(a,d.key,d.offset,d.type),We(b,c.key,c.offset,c.type))}}
function $e(a,b,c,d,e,f){if(null===a||null===c||!Sb(e,a,c))return null;b=gf(a,b,C(f)?f.anchor:null,e);if(null===b)return null;d=gf(c,d,C(f)?f.focus:null,e);if(null===d||"element"===b.type&&"element"===d.type&&(a=nc(a),c=nc(c),x(a)&&x(c)))return null;af(b,d,f);return[b,d]}function Ce(a,b,c,d,e,f){let g=fc();a=new Ye(Ue(a,b,e),Ue(c,d,f),0,"");a.dirty=!0;return g._selection=a}function df(){return new Xe(new Set)}
function jf(a){let b=a.getEditorState()._selection,c=zb(a._window);return C(b)||null==b?Zd(b,c,a,null):b.clone()}
function Zd(a,b,c,d){var e=c._window;if(null===e)return null;var f=(e=d||e.event)?e.type:void 0;d="selectionchange"===f;e=!sb&&(d||"beforeinput"===f||"compositionstart"===f||"compositionend"===f||"click"===f&&e&&3===e.detail||"drop"===f||void 0===f);let g;if(!C(a)||e){if(null===b)return null;e=b.anchorNode;f=b.focusNode;g=b.anchorOffset;b=b.focusOffset;if(d&&C(a)&&!Sb(c,e,f))return a.clone()}else return a.clone();c=$e(e,g,f,b,c,a);if(null===c)return null;let [h,k]=c;return new Ye(h,k,C(a)?a.format:
0,C(a)?a.style:"")}function u(){return fc()._selection}function sc(){return F()._editorState._selection}
function je(a,b,c,d=1){var e=a.anchor,f=a.focus,g=e.getNode(),h=f.getNode();if(b.is(g)||b.is(h)){g=b.__key;if(a.isCollapsed()){if(b=e.offset,c<=b&&0<d||c<b&&0>d)c=Math.max(0,b+d),e.set(g,c,"element"),f.set(g,c,"element"),kf(a)}else{let m=a.isBackward();h=m?f:e;var k=h.getNode();e=m?e:f;f=e.getNode();b.is(k)&&(k=h.offset,(c<=k&&0<d||c<k&&0>d)&&h.set(g,Math.max(0,k+d),"element"));b.is(f)&&(b=e.offset,(c<=b&&0<d||c<b&&0>d)&&e.set(g,Math.max(0,b+d),"element"))}kf(a)}}
function kf(a){var b=a.anchor,c=b.offset;let d=a.focus;var e=d.offset,f=b.getNode(),g=d.getNode();if(a.isCollapsed())E(f)&&(g=f.getChildrenSize(),g=(e=c>=g)?f.getChildAtIndex(g-1):f.getChildAtIndex(c),B(g)&&(c=0,e&&(c=g.getTextContentSize()),b.set(g.__key,c,"text"),d.set(g.__key,c,"text")));else{if(E(f)){let h=f.getChildrenSize();c=(a=c>=h)?f.getChildAtIndex(h-1):f.getChildAtIndex(c);B(c)&&(f=0,a&&(f=c.getTextContentSize()),b.set(c.__key,f,"text"))}E(g)&&(c=g.getChildrenSize(),e=(b=e>=c)?g.getChildAtIndex(c-
1):g.getChildAtIndex(e),B(e)&&(g=0,b&&(g=e.getTextContentSize()),d.set(e.__key,g,"text")))}}function lf(a,b){b=b.getEditorState()._selection;a=a._selection;if(C(a)){var c=a.anchor;let d=a.focus,e;"text"===c.type&&(e=c.getNode(),e.selectionTransform(b,a));"text"===d.type&&(c=d.getNode(),e!==c&&c.selectionTransform(b,a))}}
function ie(a,b,c,d,e){let f=null,g=0,h=null;null!==d?(f=d.__key,B(d)?(g=d.getTextContentSize(),h="text"):E(d)&&(g=d.getChildrenSize(),h="element")):null!==e&&(f=e.__key,B(e)?h="text":E(e)&&(h="element"));null!==f&&null!==h?a.set(f,g,h):(g=b.getIndexWithinParent(),-1===g&&(g=c.getChildrenSize()),a.set(c.__key,g,"element"))}function De(a,b,c,d,e){"text"===a.type?(a.key=c,b||(a.offset+=e)):a.offset>d.getIndexWithinParent()&&--a.offset}
function bf(a){var b=a;a.isCollapsed()||b.removeText();a=u();C(a)&&(b=a);C(b)||n(161);a=b.anchor;b=a.getNode();for(a=a.offset;!Lc(b);)[b,a]=mf(b,a);return a}
function mf(a,b){var c=a.getParent();if(!c)return c=me(),J().append(c),c.select(),[J(),0];if(B(a)){var d=a.splitText(b);if(0===d.length)return[c,a.getIndexWithinParent()];a=0===b?0:1;a=d[0].getIndexWithinParent()+a;return[c,a]}if(!E(a)||0===b)return[c,a.getIndexWithinParent()];if(d=a.getChildAtIndex(b))b=new Ye(Ue(a.__key,b,"element"),Ue(a.__key,b,"element"),0,""),(b=a.insertNewAfter(b))&&b.append(d,...d.getNextSiblings());return[c,a.getIndexWithinParent()+1]}
function cf(a){let b=me(),c=null;for(let d=0;d<a.length;d++){let e=a[d],f=Mc(e);if(f||x(e)&&e.isInline()||E(e)&&e.isInline()||B(e)||e.isParentRequired()){if(null===c&&(c=e.createParentElementNode(),b.append(c),f))continue;null!==c&&c.append(e)}else b.append(e),c=null}return b}function Ob(a){return"object"===typeof a&&null!==a&&"mergeWithSibling"in a&&"function"===typeof a.mergeWithSibling}let T=null,U=null,V=!1,nf=!1,ec=0,of={characterData:!0,childList:!0,subtree:!0};
function jc(){return V||null!==T&&T._readOnly}function G(){V&&n(13)}function fc(){null===T&&n(15);return T}function F(){null===U&&n(16);return U}function pf(a,b,c){var d=b.__type;let e=a._nodes.get(d);void 0===e&&n(30,d);a=c.get(d);void 0===a&&(a=Array.from(e.transforms),c.set(d,a));c=a.length;for(d=0;d<c&&(a[d](b),b.isAttached());d++);}function qf(a,b){b=b._dirtyLeaves;a=a._nodeMap;for(let c of b)b=a.get(c),B(b)&&b.isAttached()&&b.isSimpleText()&&!b.isUnmergeable()&&Kb(b)}
function rf(a,b){let c=b._dirtyLeaves,d=b._dirtyElements;a=a._nodeMap;let e=ic(),f=new Map;var g=c;let h=g.size;for(var k=d,m=k.size;0<h||0<m;){if(0<h){b._dirtyLeaves=new Set;for(let p of g)g=a.get(p),B(g)&&g.isAttached()&&g.isSimpleText()&&!g.isUnmergeable()&&Kb(g),g&&Ob(g)&&!B(g)&&Nb(g),void 0!==g&&void 0!==g&&g.__key!==e&&g.isAttached()&&pf(b,g,f),c.add(p);g=b._dirtyLeaves;h=g.size;if(0<h){ec++;continue}}b._dirtyLeaves=new Set;b._dirtyElements=new Map;for(let p of k)if(k=p[0],m=p[1],"root"===k||
m)g=a.get(k),void 0!==g&&void 0!==g&&g.__key!==e&&g.isAttached()&&pf(b,g,f),void 0!==g&&Ob(g)&&Nb(g),d.set(k,m);g=b._dirtyLeaves;h=g.size;k=b._dirtyElements;m=k.size;ec++}b._dirtyLeaves=c;b._dirtyElements=d}function sf(a,b){var c=a.type,d=b.get(c);void 0===d&&n(17,c);c=d.klass;a.type!==c.getType()&&n(18,c.name);c=c.importJSON(a);a=a.children;if(E(c)&&Array.isArray(a))for(d=0;d<a.length;d++){let e=sf(a[d],b);c.append(e)}return c}
function tf(a,b){let c=T,d=V,e=U;T=a;V=!0;U=null;try{return b()}finally{T=c,V=d,U=e}}
function uf(a,b){let c=a._pendingEditorState,d=a._rootElement,e=a._headless||null===d;if(null!==c){var f=a._editorState,g=f._selection,h=c._selection,k=0!==a._dirtyType,m=T,p=V,q=U,l=a._updating,r=a._observer,w=null;a._pendingEditorState=null;a._editorState=c;if(!e&&k&&null!==r){U=a;T=c;V=!1;a._updating=!0;try{let D=a._dirtyType,P=a._dirtyElements,Q=a._dirtyLeaves;r.disconnect();var A=D,y=P,z=Q;N=Rc=M="";Uc=2===A;fd=null;O=a;Sc=a._config;Tc=a._nodes;ed=O._listeners.mutation;gd=y;hd=z;id=f._nodeMap;
jd=c._nodeMap;Vc=c._readOnly;kd=new Map(a._keyToDOMMap);let ja=new Map;ld=ja;zd("root",null);ld=kd=Sc=jd=id=hd=gd=Tc=O=void 0;w=ja}catch(D){D instanceof Error&&a._onError(D);if(nf)throw D;vf(a,null,d,c);Fb(a);a._dirtyType=2;nf=!0;uf(a,f);nf=!1;return}finally{r.observe(d,of),a._updating=l,T=m,V=p,U=q}}c._readOnly||(c._readOnly=!0);var R=a._dirtyLeaves,X=a._dirtyElements,Xa=a._normalizedNodes,ma=a._updateTags,Wc=a._deferred;k&&(a._dirtyType=0,a._cloneNotNeeded.clear(),a._dirtyLeaves=new Set,a._dirtyElements=
new Map,a._normalizedNodes=new Set,a._updateTags=new Set);var Fe=a._decorators,Tb=a._pendingDecorators||Fe,Hf=c._nodeMap,Xc;for(Xc in Tb)Hf.has(Xc)||(Tb===Fe&&(Tb=kc(a)),delete Tb[Xc]);var ka=e?null:zb(a._window);if(a._editable&&null!==ka&&(k||null===h||h.dirty)){U=a;T=c;try{null!==r&&r.disconnect();if(k||null===h||h.dirty){let D=a._blockCursorElement;null!==D&&Ic(D,a,d);a:{let P=ka.anchorNode,Q=ka.focusNode,ja=ka.anchorOffset,mb=ka.focusOffset,Y=document.activeElement;if(!(ma.has("collaboration")&&
Y!==d||null!==Y&&Rb(Y)))if(C(h)){var nb=h.anchor,Yc=h.focus,Ge=nb.key,If=Yc.key,He=Ac(a,Ge),Ie=Ac(a,If),Ub=nb.offset,Je=Yc.offset,Zc=h.format,$c=h.style,Ke=h.isCollapsed(),ob=He,Vb=Ie,ad=!1;if("text"===nb.type){ob=bc(He);let Z=nb.getNode();ad=Z.getFormat()!==Zc||Z.getStyle()!==$c}else C(g)&&"text"===g.anchor.type&&(ad=!0);"text"===Yc.type&&(Vb=bc(Ie));if(null!==ob&&null!==Vb){if(Ke&&(null===g||ad||C(g)&&(g.format!==Zc||g.style!==$c))){var Jf=performance.now();Ud=[Zc,$c,Ub,Ge,Jf]}if(ja===Ub&&mb===
Je&&P===ob&&Q===Vb&&("Range"!==ka.type||!Ke)&&(null!==Y&&d.contains(Y)||d.focus({preventScroll:!0}),"element"!==nb.type))break a;try{ka.setBaseAndExtent(ob,Ub,Vb,Je)}catch(Z){}if(!ma.has("skip-scroll-into-view")&&h.isCollapsed()&&null!==d&&d===document.activeElement){let Z=h instanceof Ye&&"element"===h.anchor.type?ob.childNodes[Ub]||null:0<ka.rangeCount?ka.getRangeAt(0):null;if(null!==Z){let aa;if(Z instanceof Text){let W=document.createRange();W.selectNode(Z);aa=W.getBoundingClientRect()}else aa=
Z.getBoundingClientRect();let ya=d.ownerDocument,Fa=ya.defaultView;if(null!==Fa)for(var {top:bd,bottom:cd}=aa,Wb,Xb,ra=d;null!==ra;){let W=ra===ya.body;if(W)Wb=0,Xb=Gb(a).innerHeight;else{let Yb=ra.getBoundingClientRect();Wb=Yb.top;Xb=Yb.bottom}let Ga=0;bd<Wb?Ga=-(Wb-bd):cd>Xb&&(Ga=cd-Xb);if(0!==Ga)if(W)Fa.scrollBy(0,Ga);else{let Yb=ra.scrollTop;ra.scrollTop+=Ga;let Le=ra.scrollTop-Yb;bd-=Le;cd-=Le}if(W)break;ra=$b(ra)}}}Qd=!0}}else null!==g&&Sb(a,P,Q)&&ka.removeAllRanges()}}a:{let D=a._blockCursorElement;
if(C(h)&&h.isCollapsed()&&"element"===h.anchor.type&&d.contains(document.activeElement)){let P=h.anchor,Q=P.getNode(),ja=P.offset,mb=Q.getChildrenSize(),Y=!1,Z=null;if(ja===mb){let aa=Q.getChildAtIndex(ja-1);Hc(aa)&&(Y=!0)}else{let aa=Q.getChildAtIndex(ja);if(Hc(aa)){let ya=aa.getPreviousSibling();if(null===ya||Hc(ya))Y=!0,Z=a.getElementByKey(aa.__key)}}if(Y){let aa=a.getElementByKey(Q.__key);if(null===D){let ya=a._config.theme,Fa=document.createElement("div");Fa.contentEditable="false";Fa.setAttribute("data-lexical-cursor",
"true");let W=ya.blockCursor;if(void 0!==W){if("string"===typeof W){let Ga=rb(W);W=ya.blockCursor=Ga}void 0!==W&&Fa.classList.add(...W)}a._blockCursorElement=D=Fa}d.style.caretColor="transparent";null===Z?aa.appendChild(D):aa.insertBefore(D,Z);break a}}null!==D&&Ic(D,a,d)}null!==r&&r.observe(d,of)}finally{U=q,T=m}}if(null!==w){var Kf=w;let D=Array.from(a._listeners.mutation),P=D.length;for(let Q=0;Q<P;Q++){let [ja,mb]=D[Q],Y=Kf.get(mb);void 0!==Y&&ja(Y,{dirtyLeaves:R,prevEditorState:f,updateTags:ma})}}C(h)||
null===h||null!==g&&g.is(h)||a.dispatchCommand(ba,void 0);var dd=a._pendingDecorators;null!==dd&&(a._decorators=dd,a._pendingDecorators=null,wf("decorator",a,!0,dd));var Lf=lc(b||f),Me=lc(c);Lf!==Me&&wf("textcontent",a,!0,Me);wf("update",a,!0,{dirtyElements:X,dirtyLeaves:R,editorState:c,normalizedNodes:Xa,prevEditorState:b||f,tags:ma});a._deferred=[];if(0!==Wc.length){let D=a._updating;a._updating=!0;try{for(let P=0;P<Wc.length;P++)Wc[P]()}finally{a._updating=D}}var Ne=a._updates;if(0!==Ne.length){let D=
Ne.shift();if(D){let [P,Q]=D;xf(a,P,Q)}}}}function wf(a,b,c,...d){let e=b._updating;b._updating=c;try{let f=Array.from(b._listeners[a]);for(a=0;a<f.length;a++)f[a].apply(null,d)}finally{b._updating=e}}
function S(a,b,c){if(!1===a._updating||U!==a){let f=!1;a.update(()=>{f=S(a,b,c)});return f}let d=pc(a);for(let f=4;0<=f;f--)for(let g=0;g<d.length;g++){var e=d[g]._commands.get(b);if(void 0!==e&&(e=e[f],void 0!==e)){e=Array.from(e);let h=e.length;for(let k=0;k<h;k++)if(!0===e[k](c,a))return!0}}return!1}
function yf(a,b){let c=a._updates;for(b=b||!1;0!==c.length;){var d=c.shift();if(d){let [e,f]=d,g;void 0!==f&&(d=f.onUpdate,g=f.tag,f.skipTransforms&&(b=!0),d&&a._deferred.push(d),g&&a._updateTags.add(g));e()}}return b}
function xf(a,b,c){let d=a._updateTags;var e,f=e=!1;if(void 0!==c){var g=c.onUpdate;e=c.tag;null!=e&&d.add(e);e=c.skipTransforms||!1;f=c.discrete||!1}g&&a._deferred.push(g);c=a._editorState;g=a._pendingEditorState;let h=!1;if(null===g||g._readOnly)g=a._pendingEditorState=new zf(new Map((g||c)._nodeMap)),h=!0;g._flushSync=f;f=T;let k=V,m=U,p=a._updating;T=g;V=!1;a._updating=!0;U=a;try{h&&(a._headless?null!==c._selection&&(g._selection=c._selection.clone()):g._selection=jf(a));let q=a._compositionKey;
b();e=yf(a,e);lf(g,a);0!==a._dirtyType&&(e?qf(g,a):rf(g,a),yf(a),Pc(c,g,a._dirtyLeaves,a._dirtyElements));q!==a._compositionKey&&(g._flushSync=!0);let l=g._selection;if(C(l)){let r=g._nodeMap,w=l.focus.key;void 0!==r.get(l.anchor.key)&&void 0!==r.get(w)||n(19)}else ce(l)&&0===l._nodes.size&&(g._selection=null)}catch(q){q instanceof Error&&a._onError(q);a._pendingEditorState=c;a._dirtyType=2;a._cloneNotNeeded.clear();a._dirtyLeaves=new Set;a._dirtyElements.clear();uf(a);return}finally{T=f,V=k,U=m,
a._updating=p,ec=0}0!==a._dirtyType||Af(g,a)?g._flushSync?(g._flushSync=!1,uf(a)):h&&Qb(()=>{uf(a)}):(g._flushSync=!1,h&&(d.clear(),a._deferred=[],a._pendingEditorState=null))}function v(a,b,c){a._updating?a._updates.push([b,c]):xf(a,b,c)}class Bf extends ke{constructor(a){super(a)}decorate(){n(47)}isIsolated(){return!1}isInline(){return!0}isKeyboardSelectable(){return!0}}function x(a){return a instanceof Bf}
class Cf extends ke{constructor(a){super(a);this.__last=this.__first=null;this.__indent=this.__format=this.__size=0;this.__dir=null}getFormat(){return this.getLatest().__format}getFormatType(){let a=this.getFormat();return lb[a]||""}getIndent(){return this.getLatest().__indent}getChildren(){let a=[],b=this.getFirstChild();for(;null!==b;)a.push(b),b=b.getNextSibling();return a}getChildrenKeys(){let a=[],b=this.getFirstChild();for(;null!==b;)a.push(b.__key),b=b.getNextSibling();return a}getChildrenSize(){return this.getLatest().__size}isEmpty(){return 0===
this.getChildrenSize()}isDirty(){let a=F()._dirtyElements;return null!==a&&a.has(this.__key)}isLastChild(){let a=this.getLatest(),b=this.getParentOrThrow().getLastChild();return null!==b&&b.is(a)}getAllTextNodes(){let a=[],b=this.getFirstChild();for(;null!==b;){B(b)&&a.push(b);if(E(b)){let c=b.getAllTextNodes();a.push(...c)}b=b.getNextSibling()}return a}getFirstDescendant(){let a=this.getFirstChild();for(;E(a);){let b=a.getFirstChild();if(null===b)break;a=b}return a}getLastDescendant(){let a=this.getLastChild();
for(;E(a);){let b=a.getLastChild();if(null===b)break;a=b}return a}getDescendantByIndex(a){let b=this.getChildren(),c=b.length;if(a>=c)return a=b[c-1],E(a)&&a.getLastDescendant()||a||null;a=b[a];return E(a)&&a.getFirstDescendant()||a||null}getFirstChild(){let a=this.getLatest().__first;return null===a?null:I(a)}getFirstChildOrThrow(){let a=this.getFirstChild();null===a&&n(45,this.__key);return a}getLastChild(){let a=this.getLatest().__last;return null===a?null:I(a)}getLastChildOrThrow(){let a=this.getLastChild();
null===a&&n(96,this.__key);return a}getChildAtIndex(a){var b=this.getChildrenSize();let c;if(a<b/2){c=this.getFirstChild();for(b=0;null!==c&&b<=a;){if(b===a)return c;c=c.getNextSibling();b++}return null}c=this.getLastChild();for(--b;null!==c&&b>=a;){if(b===a)return c;c=c.getPreviousSibling();b--}return null}getTextContent(){let a="",b=this.getChildren(),c=b.length;for(let d=0;d<c;d++){let e=b[d];a+=e.getTextContent();E(e)&&d!==c-1&&!e.isInline()&&(a+="\n\n")}return a}getTextContentSize(){let a=0,
b=this.getChildren(),c=b.length;for(let d=0;d<c;d++){let e=b[d];a+=e.getTextContentSize();E(e)&&d!==c-1&&!e.isInline()&&(a+=2)}return a}getDirection(){return this.getLatest().__dir}hasFormat(a){return""!==a?(a=kb[a],0!==(this.getFormat()&a)):!1}select(a,b){G();let c=u(),d=a,e=b;var f=this.getChildrenSize();if(!this.canBeEmpty())if(0===a&&0===b){if(a=this.getFirstChild(),B(a)||E(a))return a.select(0,0)}else if(!(void 0!==a&&a!==f||void 0!==b&&b!==f)&&(a=this.getLastChild(),B(a)||E(a)))return a.select();
void 0===d&&(d=f);void 0===e&&(e=f);f=this.__key;if(C(c))c.anchor.set(f,d,"element"),c.focus.set(f,e,"element"),c.dirty=!0;else return Ce(f,d,f,e,"element","element");return c}selectStart(){let a=this.getFirstDescendant();return a?a.selectStart():this.select()}selectEnd(){let a=this.getLastDescendant();return a?a.selectEnd():this.select()}clear(){let a=this.getWritable();this.getChildren().forEach(b=>b.remove());return a}append(...a){return this.splice(this.getChildrenSize(),0,a)}setDirection(a){let b=
this.getWritable();b.__dir=a;return b}setFormat(a){this.getWritable().__format=""!==a?kb[a]:0;return this}setIndent(a){this.getWritable().__indent=a;return this}splice(a,b,c){let d=c.length,e=this.getChildrenSize(),f=this.getWritable(),g=f.__key;var h=[],k=[];let m=this.getChildAtIndex(a+b),p=null,q=e-b+d;if(0!==a)if(a===e)p=this.getLastChild();else{var l=this.getChildAtIndex(a);null!==l&&(p=l.getPreviousSibling())}if(0<b){var r=null===p?this.getFirstChild():p.getNextSibling();for(l=0;l<b;l++){null===
r&&n(100);var w=r.getNextSibling(),A=r.__key;r=r.getWritable();gc(r);k.push(A);r=w}}l=p;for(w=0;w<d;w++){A=c[w];null!==l&&A.is(l)&&(p=l=l.getPreviousSibling());r=A.getWritable();r.__parent===g&&q--;gc(r);let y=A.__key;null===l?(f.__first=y,r.__prev=null):(l=l.getWritable(),l.__next=y,r.__prev=l.__key);A.__key===g&&n(76);r.__parent=g;h.push(y);l=A}a+b===e?null!==l&&(l.getWritable().__next=null,f.__last=l.__key):null!==m&&(a=m.getWritable(),null!==l?(b=l.getWritable(),a.__prev=l.__key,b.__next=m.__key):
a.__prev=null);f.__size=q;if(k.length&&(a=u(),C(a))){k=new Set(k);h=new Set(h);let {anchor:y,focus:z}=a;Df(y,k,h)&&ie(y,y.getNode(),this,p,m);Df(z,k,h)&&ie(z,z.getNode(),this,p,m);0!==q||this.canBeEmpty()||Dc(this)||this.remove()}return f}exportJSON(){return{children:[],direction:this.getDirection(),format:this.getFormatType(),indent:this.getIndent(),type:"element",version:1}}insertNewAfter(){return null}canIndent(){return!0}collapseAtStart(){return!1}excludeFromCopy(){return!1}canReplaceWith(){return!0}canInsertAfter(){return!0}canBeEmpty(){return!0}canInsertTextBefore(){return!0}canInsertTextAfter(){return!0}isInline(){return!1}isShadowRoot(){return!1}canMergeWith(){return!1}extractWithChild(){return!1}}
function E(a){return a instanceof Cf}function Df(a,b,c){for(a=a.getNode();a;){let d=a.__key;if(b.has(d)&&!c.has(d))return!0;a=a.getParent()}return!1}
class Ef extends Cf{static getType(){return"root"}static clone(){return new Ef}constructor(){super("root");this.__cachedText=null}getTopLevelElementOrThrow(){n(51)}getTextContent(){let a=this.__cachedText;return!jc()&&0!==F()._dirtyType||null===a?super.getTextContent():a}remove(){n(52)}replace(){n(53)}insertBefore(){n(54)}insertAfter(){n(55)}updateDOM(){return!1}append(...a){for(let b=0;b<a.length;b++){let c=a[b];E(c)||x(c)||n(56)}return super.append(...a)}static importJSON(a){let b=J();b.setFormat(a.format);
b.setIndent(a.indent);b.setDirection(a.direction);return b}exportJSON(){return{children:[],direction:this.getDirection(),format:this.getFormatType(),indent:this.getIndent(),type:"root",version:1}}collapseAtStart(){return!0}}function L(a){return a instanceof Ef}function Af(a,b){b=b.getEditorState()._selection;a=a._selection;if(null!==a){if(a.dirty||!a.is(b))return!0}else if(null!==b)return!0;return!1}function Ff(){return new zf(new Map([["root",new Ef]]))}
function Gf(a){let b=a.exportJSON();var c=a.constructor;b.type!==c.getType()&&n(130,c.name);if(E(a)){let d=b.children;Array.isArray(d)||n(59,c.name);a=a.getChildren();for(c=0;c<a.length;c++){let e=Gf(a[c]);d.push(e)}}return b}
class zf{constructor(a,b){this._nodeMap=a;this._selection=b||null;this._readOnly=this._flushSync=!1}isEmpty(){return 1===this._nodeMap.size&&null===this._selection}read(a){return tf(this,a)}clone(a){a=new zf(this._nodeMap,void 0===a?this._selection:a);a._readOnly=!0;return a}toJSON(){return tf(this,()=>({root:Gf(J())}))}}class Mf extends Cf{static getType(){return"artificial"}createDOM(){return document.createElement("div")}}
class Yd extends Cf{constructor(a){super(a);this.__textFormat=0}static getType(){return"paragraph"}getTextFormat(){return this.getLatest().__textFormat}setTextFormat(a){let b=this.getWritable();b.__textFormat=a;return b}hasTextFormat(a){a=ib[a];return 0!==(this.getTextFormat()&a)}static clone(a){return new Yd(a.__key)}createDOM(a){let b=document.createElement("p");a=vc(a.theme,"paragraph");void 0!==a&&b.classList.add(...a);return b}updateDOM(){return!1}static importDOM(){return{p:()=>({conversion:Nf,
priority:0})}}exportDOM(a){({element:a}=super.exportDOM(a));if(a&&Jc(a)){this.isEmpty()&&a.append(document.createElement("br"));var b=this.getFormatType();a.style.textAlign=b;if(b=this.getDirection())a.dir=b;b=this.getIndent();0<b&&(a.style.textIndent=`${20*b}px`)}return{element:a}}static importJSON(a){let b=me();b.setFormat(a.format);b.setIndent(a.indent);b.setDirection(a.direction);b.setTextFormat(a.textFormat);return b}exportJSON(){return{...super.exportJSON(),textFormat:this.getTextFormat(),type:"paragraph",
version:1}}insertNewAfter(a,b){let c=me();c.setTextFormat(a.format);a=this.getDirection();c.setDirection(a);c.setFormat(this.getFormatType());this.insertAfter(c,b);return c}collapseAtStart(){let a=this.getChildren();if(0===a.length||B(a[0])&&""===a[0].getTextContent().trim()){if(null!==this.getNextSibling())return this.selectNext(),this.remove(),!0;if(null!==this.getPreviousSibling())return this.selectPrevious(),this.remove(),!0}return!1}}
function Nf(a){let b=me();a.style&&(b.setFormat(a.style.textAlign),a=parseInt(a.style.textIndent,10)/20,0<a&&b.setIndent(a));return{node:b}}function me(){return Fc(new Yd)}function Bd(a){return a instanceof Yd}
function vf(a,b,c,d){let e=a._keyToDOMMap;e.clear();a._editorState=Ff();a._pendingEditorState=d;a._compositionKey=null;a._dirtyType=0;a._cloneNotNeeded.clear();a._dirtyLeaves=new Set;a._dirtyElements.clear();a._normalizedNodes=new Set;a._updateTags=new Set;a._updates=[];a._blockCursorElement=null;d=a._observer;null!==d&&(d.disconnect(),a._observer=null);null!==b&&(b.textContent="");null!==c&&(c.textContent="",e.set("root",c))}
function Of(a,b){let c=new Map,d=new Set,e=f=>{Object.keys(f).forEach(g=>{let h=c.get(g);void 0===h&&(h=[],c.set(g,h));h.push(f[g])})};a.forEach(f=>{let g=f.klass.importDOM;null==g||d.has(g)||(d.add(g),f=g.call(f.klass),null!==f&&e(f))});b&&e(b);return c}
class Pf{constructor(a,b,c,d,e,f,g){this._parentEditor=b;this._rootElement=null;this._editorState=a;this._compositionKey=this._pendingEditorState=null;this._deferred=[];this._keyToDOMMap=new Map;this._updates=[];this._updating=!1;this._listeners={decorator:new Set,editable:new Set,mutation:new Map,root:new Set,textcontent:new Set,update:new Set};this._commands=new Map;this._config=d;this._nodes=c;this._decorators={};this._pendingDecorators=null;this._dirtyType=0;this._cloneNotNeeded=new Set;this._dirtyLeaves=
new Set;this._dirtyElements=new Map;this._normalizedNodes=new Set;this._updateTags=new Set;this._observer=null;this._key=qc();this._onError=e;this._htmlConversions=f;this._editable=g;this._headless=null!==b&&b._headless;this._blockCursorElement=this._window=null}isComposing(){return null!=this._compositionKey}registerUpdateListener(a){let b=this._listeners.update;b.add(a);return()=>{b.delete(a)}}registerEditableListener(a){let b=this._listeners.editable;b.add(a);return()=>{b.delete(a)}}registerDecoratorListener(a){let b=
this._listeners.decorator;b.add(a);return()=>{b.delete(a)}}registerTextContentListener(a){let b=this._listeners.textcontent;b.add(a);return()=>{b.delete(a)}}registerRootListener(a){let b=this._listeners.root;a(this._rootElement,null);b.add(a);return()=>{a(null,this._rootElement);b.delete(a)}}registerCommand(a,b,c){void 0===c&&n(35);let d=this._commands;d.has(a)||d.set(a,[new Set,new Set,new Set,new Set,new Set]);let e=d.get(a);void 0===e&&n(36,String(a));let f=e[c];f.add(b);return()=>{f.delete(b);
e.every(g=>0===g.size)&&d.delete(a)}}registerMutationListener(a,b){void 0===this._nodes.get(a.getType())&&n(37,a.name);let c=this._listeners.mutation;c.set(b,a);return()=>{c.delete(b)}}registerNodeTransformToKlass(a,b){var c=a.getType();c=this._nodes.get(c);void 0===c&&n(37,a.name);c.transforms.add(b);return c}registerNodeTransform(a,b){var c=this.registerNodeTransformToKlass(a,b);let d=[c];c=c.replaceWithKlass;null!=c&&(c=this.registerNodeTransformToKlass(c,b),d.push(c));mc(this,a.getType());return()=>
{d.forEach(e=>e.transforms.delete(b))}}hasNode(a){return this._nodes.has(a.getType())}hasNodes(a){return a.every(this.hasNode.bind(this))}dispatchCommand(a,b){return S(this,a,b)}getDecorators(){return this._decorators}getRootElement(){return this._rootElement}getKey(){return this._key}setRootElement(a){let b=this._rootElement;if(a!==b){let f=vc(this._config.theme,"root");var c=this._pendingEditorState||this._editorState;this._rootElement=a;vf(this,b,a,c);if(null!==b){if(!this._config.disableEvents){var d=
b.ownerDocument,e=Pd.get(d);void 0===e&&n(162);--e;0<=e||n(164);Pd.set(d,e);0===e&&d.removeEventListener("selectionchange",fe);d=b.__lexicalEditor;null!==d&&void 0!==d&&(null!==d._parentEditor?(e=pc(d),e=e[e.length-1]._key,ee.get(e)===d&&ee.delete(e)):ee.delete(d._key),b.__lexicalEditor=null);d=de(b);for(e=0;e<d.length;e++)d[e]();b.__lexicalEventHandles=[]}null!=f&&b.classList.remove(...f)}null!==a?(c=(c=a.ownerDocument)&&c.defaultView||null,d=a.style,d.userSelect="text",d.whiteSpace="pre-wrap",d.wordBreak=
"break-word",a.setAttribute("data-lexical-editor","true"),this._window=c,this._dirtyType=2,Fb(this),this._updateTags.add("history-merge"),uf(this),this._config.disableEvents||ge(a,this),null!=f&&a.classList.add(...f)):(this._editorState=c,this._window=this._pendingEditorState=null);wf("root",this,!1,a,b)}}getElementByKey(a){return this._keyToDOMMap.get(a)||null}getEditorState(){return this._editorState}setEditorState(a,b){a.isEmpty()&&n(38);Eb(this);let c=this._pendingEditorState,d=this._updateTags;
b=void 0!==b?b.tag:null;null===c||c.isEmpty()||(null!=b&&d.add(b),uf(this));this._pendingEditorState=a;this._dirtyType=2;this._dirtyElements.set("root",!1);this._compositionKey=null;null!=b&&d.add(b);uf(this)}parseEditorState(a,b){a="string"===typeof a?JSON.parse(a):a;let c=Ff(),d=T,e=V,f=U,g=this._dirtyElements,h=this._dirtyLeaves,k=this._cloneNotNeeded,m=this._dirtyType;this._dirtyElements=new Map;this._dirtyLeaves=new Set;this._cloneNotNeeded=new Set;this._dirtyType=0;T=c;V=!1;U=this;try{sf(a.root,
this._nodes),b&&b(),c._readOnly=!0}catch(p){p instanceof Error&&this._onError(p)}finally{this._dirtyElements=g,this._dirtyLeaves=h,this._cloneNotNeeded=k,this._dirtyType=m,T=d,V=e,U=f}return c}update(a,b){v(this,a,b)}focus(a,b={}){let c=this._rootElement;null!==c&&(c.setAttribute("autocapitalize","off"),v(this,()=>{let d=u(),e=J();null!==d?d.dirty=!0:0!==e.getChildrenSize()&&("rootStart"===b.defaultSelection?e.selectStart():e.selectEnd())},{onUpdate:()=>{c.removeAttribute("autocapitalize");a&&a()},
tag:"focus"}),null===this._pendingEditorState&&c.removeAttribute("autocapitalize"))}blur(){var a=this._rootElement;null!==a&&a.blur();a=zb(this._window);null!==a&&a.removeAllRanges()}isEditable(){return this._editable}setEditable(a){this._editable!==a&&(this._editable=a,wf("editable",this,!0,a))}toJSON(){return{editorState:this._editorState.toJSON()}}}exports.$addUpdateTag=function(a){G();F()._updateTags.add(a)};exports.$applyNodeReplacement=Fc;exports.$copyNode=Ec;exports.$createLineBreakNode=re;
exports.$createNodeSelection=df;exports.$createParagraphNode=me;exports.$createPoint=Ue;exports.$createRangeSelection=function(){let a=Ue("root",0,"element"),b=Ue("root",0,"element");return new Ye(a,b,0,"")};exports.$createRangeSelectionFromDom=function(a,b){return Zd(null,a,b,null)};exports.$createTabNode=Oe;exports.$createTextNode=K;exports.$getAdjacentNode=yc;exports.$getCharacterOffsets=Ze;exports.$getEditor=function(){return F()};exports.$getNearestNodeFromDOMNode=yb;
exports.$getNearestRootOrShadowRoot=Cc;exports.$getNodeByKey=I;exports.$getPreviousSelection=sc;exports.$getRoot=J;exports.$getSelection=u;exports.$getTextContent=function(){let a=u();return null===a?"":a.getTextContent()};exports.$hasAncestor=Bc;exports.$hasUpdateTag=function(a){return F()._updateTags.has(a)};exports.$insertNodes=function(a){let b=u()||sc();null===b&&(b=J().selectEnd());b.insertNodes(a)};exports.$isBlockElementNode=function(a){return E(a)&&!a.isInline()};
exports.$isDecoratorNode=x;exports.$isElementNode=E;exports.$isInlineElementOrDecoratorNode=function(a){return E(a)&&a.isInline()||x(a)&&a.isInline()};exports.$isLeafNode=function(a){return B(a)||Mc(a)||x(a)};exports.$isLineBreakNode=Mc;exports.$isMergeableNode=Ob;exports.$isNodeSelection=ce;exports.$isParagraphNode=Bd;exports.$isRangeSelection=C;exports.$isRootNode=L;exports.$isRootOrShadowRoot=Dc;exports.$isTabNode=Se;exports.$isTextNode=B;
exports.$nodesOfType=function(a){var b=fc();let c=b._readOnly,d=a.getType();b=b._nodeMap;let e=[];for(let [,f]of b)f instanceof a&&f.__type===d&&(c||f.isAttached())&&e.push(f);return e};exports.$normalizeSelection__EXPERIMENTAL=Lb;exports.$parseSerializedNode=function(a){return sf(a,F()._nodes)};exports.$selectAll=function(){var a=J();a=a.select(0,a.getChildrenSize());Cb(Lb(a))};exports.$setCompositionKey=H;exports.$setSelection=Cb;
exports.$splitNode=function(a,b){let c=a.getChildAtIndex(b);null==c&&(c=a);Dc(a)&&n(102);let d=g=>{const h=g.getParentOrThrow(),k=Dc(h),m=g!==c||k?Ec(g):g;if(k)return E(g)&&E(m)||n(133),g.insertAfter(m),[g,m,m];const [p,q,l]=d(h);g=g.getNextSiblings();l.append(m,...g);return[p,q,m]},[e,f]=d(c);return[e,f]};exports.ArtificialNode__DO_NOT_USE=Mf;exports.BLUR_COMMAND=Ra;exports.CAN_REDO_COMMAND={};exports.CAN_UNDO_COMMAND={};exports.CLEAR_EDITOR_COMMAND={};exports.CLEAR_HISTORY_COMMAND={};
exports.CLICK_COMMAND=ca;exports.COMMAND_PRIORITY_CRITICAL=4;exports.COMMAND_PRIORITY_EDITOR=0;exports.COMMAND_PRIORITY_HIGH=3;exports.COMMAND_PRIORITY_LOW=1;exports.COMMAND_PRIORITY_NORMAL=2;exports.CONTROLLED_TEXT_INSERTION_COMMAND=ha;exports.COPY_COMMAND=Na;exports.CUT_COMMAND=Oa;exports.DELETE_CHARACTER_COMMAND=da;exports.DELETE_LINE_COMMAND=oa;exports.DELETE_WORD_COMMAND=na;exports.DRAGEND_COMMAND=Ma;exports.DRAGOVER_COMMAND=La;exports.DRAGSTART_COMMAND=Ka;exports.DROP_COMMAND=Ja;
exports.DecoratorNode=Bf;exports.ElementNode=Cf;exports.FOCUS_COMMAND=Qa;exports.FORMAT_ELEMENT_COMMAND={};exports.FORMAT_TEXT_COMMAND=pa;exports.INDENT_CONTENT_COMMAND={};exports.INSERT_LINE_BREAK_COMMAND=ea;exports.INSERT_PARAGRAPH_COMMAND=fa;exports.INSERT_TAB_COMMAND={};exports.KEY_ARROW_DOWN_COMMAND=Aa;exports.KEY_ARROW_LEFT_COMMAND=wa;exports.KEY_ARROW_RIGHT_COMMAND=ua;exports.KEY_ARROW_UP_COMMAND=za;exports.KEY_BACKSPACE_COMMAND=Da;exports.KEY_DELETE_COMMAND=Ha;exports.KEY_DOWN_COMMAND=ta;
exports.KEY_ENTER_COMMAND=Ba;exports.KEY_ESCAPE_COMMAND=Ea;exports.KEY_MODIFIER_COMMAND=Sa;exports.KEY_SPACE_COMMAND=Ca;exports.KEY_TAB_COMMAND=Ia;exports.LineBreakNode=oe;exports.MOVE_TO_END=va;exports.MOVE_TO_START=xa;exports.OUTDENT_CONTENT_COMMAND={};exports.PASTE_COMMAND=ia;exports.ParagraphNode=Yd;exports.REDO_COMMAND=sa;exports.REMOVE_TEXT_COMMAND=la;exports.RootNode=Ef;exports.SELECTION_CHANGE_COMMAND=ba;exports.SELECTION_INSERT_CLIPBOARD_NODES_COMMAND={};exports.SELECT_ALL_COMMAND=Pa;
exports.TabNode=Re;exports.TextNode=xe;exports.UNDO_COMMAND=qa;exports.createCommand=function(){return{}};
exports.createEditor=function(a){var b=a||{},c=U;let d=b.theme||{},e=void 0===a?c:b.parentEditor||null,f=b.disableEvents||!1,g=Ff(),h=b.namespace||(null!==e?e._config.namespace:qc()),k=b.editorState,m=[Ef,xe,oe,Re,Yd,Mf,...(b.nodes||[])],{onError:p,html:q}=b,l=void 0!==b.editable?b.editable:!0;if(void 0===a&&null!==c)a=c._nodes;else for(a=new Map,c=0;c<m.length;c++){let w=m[c],A=null;var r=null;"function"!==typeof w&&(r=w,w=r.replace,A=r.with,r=r.withKlass||null);let y=w.getType(),z=w.transform(),
R=new Set;null!==z&&R.add(z);a.set(y,{exportDOM:q&&q.export?q.export.get(w):void 0,klass:w,replace:A,replaceWithKlass:r,transforms:R})}b=new Pf(g,e,a,{customGetAdjacentNode:b.customGetAdjacentNode,disableEvents:f,namespace:h,theme:d},p?p:console.error,Of(a,q?q.import:void 0),l);void 0!==k&&(b._pendingEditorState=k,b._dirtyType=2);return b};exports.getNearestEditorFromDOMNode=Zb;
exports.isBlockDomNode=function(a){return null!==a.nodeName.match(new RegExp(/^(address|article|aside|blockquote|canvas|dd|div|dl|dt|fieldset|figcaption|figure|footer|form|h1|h2|h3|h4|h5|h6|header|hr|li|main|nav|noscript|ol|p|pre|section|table|td|tfoot|ul|video)$/,"i"))};exports.isCurrentlyReadOnlyMode=jc;exports.isHTMLAnchorElement=function(a){return Jc(a)&&"A"===a.tagName};exports.isHTMLElement=Jc;exports.isInlineDomNode=Kc;exports.isSelectionCapturedInDecoratorInput=Rb;
exports.isSelectionWithinEditor=Sb
