/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';var k=require("@lexical/react/LexicalComposerContext"),l=require("lexical"),x=require("react"),y=require("@lexical/utils"),z="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement?x.useLayoutEffect:x.useEffect;class A{constructor(b){this.key=b;this.ref={current:null};this.setRefElement=this.setRefElement.bind(this)}setRefElement(b){this.ref={current:b}}}
let B=b=>{const a=document.getElementById("typeahead-menu");if(a){var c=a.getBoundingClientRect();c.top+c.height>window.innerHeight&&a.scrollIntoView({block:"center"});0>c.top&&a.scrollIntoView({block:"center"});b.scrollIntoView({block:"nearest"})}};
function C(b){var a=l.$getSelection();if(!l.$isRangeSelection(a)||!a.isCollapsed())return null;var c=a.anchor;if("text"!==c.type)return null;a=c.getNode();if(!a.isSimpleText())return null;c=c.offset;let e=a.getTextContent().slice(0,c);var f=b.matchingString;b=b.replaceableString.length;for(let t=b;t<=f.length;t++)e.substr(-t)===f.substr(0,t)&&(b=t);b=c-b;if(0>b)return null;let r;0===b?[r]=a.splitText(c):[,r]=a.splitText(b,c);return r}
function F(b,a){let c=getComputedStyle(b),e="absolute"===c.position;a=a?/(auto|scroll|hidden)/:/(auto|scroll)/;if("fixed"===c.position)return document.body;for(;b=b.parentElement;)if(c=getComputedStyle(b),(!e||"static"!==c.position)&&a.test(c.overflow+c.overflowY+c.overflowX))return b;return document.body}function G(b,a){b=b.getBoundingClientRect();a=a.getBoundingClientRect();return b.top>a.top&&b.top<a.bottom}
function H(b,a,c,e){let [f]=k.useLexicalComposerContext();x.useEffect(()=>{if(null!=a&&null!=b){let r=f.getRootElement(),t=null!=r?F(r,!1):document.body,n=!1,d=G(a,t),h=function(){n||(window.requestAnimationFrame(function(){c();n=!1}),n=!0);const p=G(a,t);p!==d&&(d=p,null!=e&&e(p))},q=new ResizeObserver(c);window.addEventListener("resize",c);document.addEventListener("scroll",h,{capture:!0,passive:!0});q.observe(a);return()=>{q.unobserve(a);window.removeEventListener("resize",c);document.removeEventListener("scroll",
h,!0)}}},[a,f,e,c,b])}let I=l.createCommand("SCROLL_TYPEAHEAD_OPTION_INTO_VIEW_COMMAND");
function J({close:b,editor:a,anchorElementRef:c,resolution:e,options:f,menuRenderFn:r,onSelectOption:t,shouldSplitNodeWithQuery:n=!1}){let [d,h]=x.useState(null);x.useEffect(()=>{h(0)},[e.match&&e.match.matchingString]);let q=x.useCallback(g=>{a.update(()=>{const m=null!=e.match&&n?C(e.match):null;t(g,m,b,e.match?e.match.matchingString:"")})},[a,n,e.match,t,b]),p=x.useCallback(g=>{const m=a.getRootElement();null!==m&&(m.setAttribute("aria-activedescendant","typeahead-item-"+g),h(g))},[a]);x.useEffect(()=>
()=>{let g=a.getRootElement();null!==g&&g.removeAttribute("aria-activedescendant")},[a]);z(()=>{null===f?h(null):null===d&&p(0)},[f,d,p]);x.useEffect(()=>y.mergeRegister(a.registerCommand(I,({option:g})=>g.ref&&null!=g.ref.current?(B(g.ref.current),!0):!1,l.COMMAND_PRIORITY_LOW)),[a,p]);x.useEffect(()=>y.mergeRegister(a.registerCommand(l.KEY_ARROW_DOWN_COMMAND,g=>{if(null!==f&&f.length&&null!==d){let m=d!==f.length-1?d+1:0;p(m);let u=f[m];null!=u.ref&&u.ref.current&&a.dispatchCommand(I,{index:m,option:u});
g.preventDefault();g.stopImmediatePropagation()}return!0},l.COMMAND_PRIORITY_LOW),a.registerCommand(l.KEY_ARROW_UP_COMMAND,g=>{if(null!==f&&f.length&&null!==d){var m=0!==d?d-1:f.length-1;p(m);m=f[m];null!=m.ref&&m.ref.current&&B(m.ref.current);g.preventDefault();g.stopImmediatePropagation()}return!0},l.COMMAND_PRIORITY_LOW),a.registerCommand(l.KEY_ESCAPE_COMMAND,g=>{g.preventDefault();g.stopImmediatePropagation();b();return!0},l.COMMAND_PRIORITY_LOW),a.registerCommand(l.KEY_TAB_COMMAND,g=>{if(null===
f||null===d||null==f[d])return!1;g.preventDefault();g.stopImmediatePropagation();q(f[d]);return!0},l.COMMAND_PRIORITY_LOW),a.registerCommand(l.KEY_ENTER_COMMAND,g=>{if(null===f||null===d||null==f[d])return!1;null!==g&&(g.preventDefault(),g.stopImmediatePropagation());q(f[d]);return!0},l.COMMAND_PRIORITY_LOW)),[q,b,a,f,d,p]);let v=x.useMemo(()=>({options:f,selectOptionAndCleanUp:q,selectedIndex:d,setHighlightedIndex:h}),[q,d,f]);return r(c,v,e.match?e.match.matchingString:"")}
function K(b,a,c){let [e]=k.useLexicalComposerContext(),f=x.useRef(document.createElement("div")),r=x.useCallback(()=>{const n=e.getRootElement(),d=f.current;var h=d.firstChild;if(null!==n&&null!==b){const {left:p,top:v,width:g,height:m}=b.getRect();d.style.top=`${v+window.pageYOffset}px`;d.style.left=`${p+window.pageXOffset}px`;d.style.height=`${m}px`;d.style.width=`${g}px`;if(null!==h){var q=h.getBoundingClientRect();h=q.height;q=q.width;const u=n.getBoundingClientRect();p+q>u.right&&(d.style.left=
`${u.right-q+window.pageXOffset}px`);(v+h>window.innerHeight||v+h>u.bottom)&&v-u.top>h&&(d.style.top=`${v-h+window.pageYOffset-(m+10)}px`)}d.isConnected||(null!=c&&(d.className=c),d.setAttribute("aria-label","Typeahead menu"),d.setAttribute("id","typeahead-menu"),d.setAttribute("role","listbox"),d.style.display="block",d.style.position="absolute",document.body.append(d));f.current=d;n.setAttribute("aria-controls","typeahead-menu")}},[e,b,c]);x.useEffect(()=>{let n=e.getRootElement();if(null!==b)return r(),
()=>{null!==n&&n.removeAttribute("aria-controls");let d=f.current;null!==d&&d.isConnected&&d.remove()}},[e,r,b]);let t=x.useCallback(n=>{null!==b&&(n||a(null))},[b,a]);H(b,f.current,r,t);return f}function L(b,a,c){var e=c.getSelection();if(null===e||!e.isCollapsed)return!1;c=e.anchorNode;e=e.anchorOffset;if(null==c||null==e)return!1;try{a.setStart(c,b),a.setEnd(c,e)}catch(f){return!1}return!0}
function M(b){let a=null;b.getEditorState().read(()=>{var c=l.$getSelection();if(l.$isRangeSelection(c)){var e=c.anchor;"text"!==e.type?a=null:(c=e.getNode(),c.isSimpleText()?(e=e.offset,a=c.getTextContent().slice(0,e)):a=null)}});return a}function N(b,a){return 0!==a?!1:b.getEditorState().read(()=>{var c=l.$getSelection();return l.$isRangeSelection(c)?(c=c.anchor.getNode().getPreviousSibling(),l.$isTextNode(c)&&c.isTextEntity()):!1})}function O(b){x.startTransition?x.startTransition(b):b()}
let P=l.createCommand("SCROLL_TYPEAHEAD_OPTION_INTO_VIEW_COMMAND");
exports.LexicalTypeaheadMenuPlugin=function({options:b,onQueryChange:a,onSelectOption:c,onOpen:e,onClose:f,menuRenderFn:r,triggerFn:t,anchorClassName:n}){let [d]=k.useLexicalComposerContext(),[h,q]=x.useState(null);n=K(h,q,n);let p=x.useCallback(()=>{q(null);null!=f&&null!==h&&f()},[f,h]),v=x.useCallback(g=>{q(g);null!=e&&null===h&&e(g)},[e,h]);x.useEffect(()=>{let g=d.registerUpdateListener(()=>{d.getEditorState().read(()=>{const m=d._window||window,u=m.document.createRange(),D=l.$getSelection(),
E=M(d);if(l.$isRangeSelection(D)&&D.isCollapsed()&&null!==E&&null!==u){var w=t(E,d);a(w?w.matchingString:null);null===w||N(d,w.leadOffset)||null===L(w.leadOffset,u,m)?p():O(()=>v({getRect:()=>u.getBoundingClientRect(),match:w}))}else p()})});return()=>{g()}},[d,t,a,h,p,v]);return null===h||null===d?null:x.createElement(J,{close:p,resolution:h,editor:d,anchorElementRef:n,options:b,menuRenderFn:r,shouldSplitNodeWithQuery:!0,onSelectOption:c})};exports.MenuOption=A;exports.PUNCTUATION="\\.,\\+\\*\\?\\$\\@\\|#{}\\(\\)\\^\\-\\[\\]\\\\/!%'\"~=<>_:;";
exports.SCROLL_TYPEAHEAD_OPTION_INTO_VIEW_COMMAND=P;exports.getScrollParent=function(b,a){let c=getComputedStyle(b),e="absolute"===c.position;a=a?/(auto|scroll|hidden)/:/(auto|scroll)/;if("fixed"===c.position)return document.body;for(;b=b.parentElement;)if(c=getComputedStyle(b),(!e||"static"!==c.position)&&a.test(c.overflow+c.overflowY+c.overflowX))return b;return document.body};
exports.useBasicTypeaheadTriggerMatch=function(b,{minLength:a=1,maxLength:c=75}){return x.useCallback(e=>{e=(new RegExp("(^|\\s|\\()(["+b+"]((?:[^"+(b+"\\.,\\+\\*\\?\\$\\@\\|#{}\\(\\)\\^\\-\\[\\]\\\\/!%'\"~=<>_:;\\s]){0,")+c+"}))$")).exec(e);if(null!==e){let f=e[1],r=e[3];if(r.length>=a)return{leadOffset:e.index+f.length,matchingString:r,replaceableString:e[2]}}return null},[c,a,b])};exports.useDynamicPositioning=H
